### ISSUE TITLE
Can't add same address twice with different ports

### ISSUE THREAD

**Issue by NettoHikari** [cockpit-project/cockpit#11796] opened 2019-05-11 11:04 UTC
**Cockpit version:** 193
**OS:** Arch Linux
**Package:** AUR / [cockpit-minimal](https://aur.archlinux.org/packages/cockpit-minimal/)
**Page:** Dashboard

**The issue:**
When adding a new machine using the web interface, the same address can't be used twice _(with different ports)_.

**Background:**
I'm using a single dynamic DNS domain to connect remotely to serveral machines behind my router at home.

I have 4 machines at home with SSH enabled and port forwarding configured in the router, but I can only add 1 of them, because Cockpit will not allow adding multiple machines on the same address. Configuring them in _/etc/cockpit/machines.d/05-machines.json_ doesn't work either.

Only workaround is to create multiple dynamic DNS domains, but I don't want that.

**Steps to reproduce:**
1. Go to Dashboard
2. Click on "Add"
3. Add another machine with an already used address, but different port

**Comment by jmakov** [comment] 2019-08-23 00:59
A quick workaround is to add in your `.ssh/config` a new host (alias for your machine) e.g. :
```
Host my_machine_1
    Hostname IP_mach_1
    Port port_1
Host my_machine_2
    Hostname IP_mach_1
    Port port_2
```

This issue is also a dup of https://github.com/cockpit-project/cockpit/issues/6719

**Comment by NettoHikari** [comment] 2019-08-28 16:13
Thank you very much! I created redundand DNS entries for now. Didn't find the existing issue before posting. Sorry.

**Comment by KKoukiou** [comment] 2019-09-20 15:53
Closing a duplicate of https://github.com/cockpit-project/cockpit/issues/6719

**Closed by KKoukiou** 2019-09-20 15:53 UTC
