### ISSUE TITLE
transient host name not shown in the host switcher

### ISSUE THREAD

**Issue by teppot** [cockpit-project/cockpit#9909] opened 2018-08-26 15:44 UTC
When a server is using a transient host name, the host name is displayed correctly on the System page but on the top of the sidebar it just says localhost. You can reproduce this by unsetting the host name with ``hostnamectl set-hostname ''``. Attached is a screenshot of the problem.

![screenshot](https://user-images.githubusercontent.com/42717877/44629991-cbbdc900-a95f-11e8-9df6-279d252398ad.png)

**Comment by martinpitt** [comment] 2019-11-13 06:58
I can reproduce this with

    hostnamectl set-hostname ''
    hostnamectl set-hostname --transient testy

Then the System page shows "testy" (the transient hostname), and the host switcher in the nav shows "127.0.0.2".

**Comment by marusak** [comment] 2020-12-07 13:49
I never see  transient hostname nowhere in the UI and checking with old code, there has never really been any change. Does it require something else on the system to make it work?

**Comment by jelly** [comment] 2021-08-05 16:04
Digging into the issue, I think one of the entry points which deals with the hostname is [hostname_text()](https://github.com/cockpit-project/cockpit/blob/main/pkg/systemd/overview.jsx#L179) when a set a transient hostname and no static hostname the object shows:

```
{
  "KernelVersion": "#1 SMP Tue Jul 20 20:27:29 UTC 2021",
  "HostnameSource": "transient",
  "Location": "",
  "Hostname": "testy",
  "HardwareModel": "Standard PC _i440FX + PIIX, 1996_",
  "Chassis": "vm",
  "StaticHostname": "",
  "KernelRelease": "5.13.4-200.fc34.x86_64",
  "HardwareVendor": "QEMU",
  "OperatingSystemCPEName": "cpe:/o:fedoraproject:fedora:34",
  "Deployment": "",
  "KernelName": "Linux",
  "OperatingSystemPrettyName": "Fedora 34 (Cloud Edition)",
  "IconName": "computer-vm",
  "DefaultHostname": "fedora",
  "HomeURL": "https://fedoraproject.org/",
  "PrettyHostname": ""
}```

So it seems that str should be assigned to `this.state.hostnameData.Hostname` and not `HostName`:

When setting a static hostname again the dictionary key is still `Hostname`:

```json
{
  "KernelVersion": "#1 SMP Tue Jul 20 20:27:29 UTC 2021",
  "HostnameSource": "static",
  "Location": "",
  "Hostname": "LOL",
  "HardwareModel": "Standard PC _i440FX + PIIX, 1996_",
  "Chassis": "vm",
  "StaticHostname": "LOL",
  "KernelRelease": "5.13.4-200.fc34.x86_64",
  "HardwareVendor": "QEMU",
  "OperatingSystemCPEName": "cpe:/o:fedoraproject:fedora:34",
  "Deployment": "",
  "KernelName": "Linux",
  "OperatingSystemPrettyName": "Fedora 34 (Cloud Edition)",
  "IconName": "computer-vm",
  "DefaultHostname": "fedora",
  "HomeURL": "https://fedoraproject.org/",
  "PrettyHostname": ""
}
```

**Comment by martinpitt** [comment] 2021-08-06 05:07
@jelly : No, this indeed just looks like a typo, and point out a testing gap. The [official docs](https://www.freedesktop.org/wiki/Software/systemd/hostnamed/) clearly say `Hostname` (and they also document the difference between static, transient, and pretty).

So this is a nice exercise in writing/extending our tests. Since https://github.com/cockpit-project/bots/pull/2168 our test VMs actually get a valid transient hostname, so some combination of removing /etc/hostname, restarting hostnamed, or (if really necessary) a reboot ought to provide a realistic scenario for a transient-only hostname.

While you are at it, please also drop the redundant `|| ""` [here](https://github.com/cockpit-project/cockpit/blob/main/pkg/systemd/overview.jsx#L253)?

I also see that the corresponding [shell code](https://github.com/cockpit-project/cockpit/blob/main/pkg/shell/machines/machines.js) (for the host switcher) does not even try to look at the transient host name (which is what this issue is about originally). So both are independent fixes, but both should be done.

Thanks!

**Closed** 2021-08-12 08:11 UTC
Labels: good-first-issue
