### ISSUE TITLE
"Overview" link on detailed graphs page does not work

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13580] opened 2020-02-20 10:43 UTC
1. Visit http://localhost:9090/system/graphs#/cpu
2. Click "Overview"
3. Notice nothing happening

The Overview link works on the simple graphs page. The link back to the simple graphs also works on the detailed graphs page.

**Comment by garrett** [comment] 2020-02-20 10:47
I noticed that there are two breadcrumb bars and the overview link is in both. There's the same ID used for both elements, although one is always hidden.

The event is probably bound specifically to the ID and the first one with that ID is for the simple graph.

All IDs on a page _must_ be unique, even when they're hidden.

**Comment by KKoukiou** [comment] 2020-02-20 11:55
Duplicate of https://github.com/cockpit-project/cockpit/issues/13578

**Closed by KKoukiou** 2020-02-20 11:55 UTC
Labels: bug, good-first-issue
