### ISSUE TITLE
Tests failed on 7ad70e4bfa5cd8ec84ab2bac264548bcff6c7f8d

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20360] opened 2024-04-24 02:25 UTC
The job `fedora-39/daily` failed on commit 7ad70e4bfa5cd8ec84ab2bac264548bcff6c7f8d.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-7ad70e4b-20240424-012718-fedora-39-daily/log.html

**Comment by martinpitt** [comment] 2024-04-24 05:31
Duplicate of #20338

**Closed by martinpitt** 2024-04-24 05:31 UTC
Labels: nightly
