### ISSUE TITLE
Cannot refresh cache whilst offline

### ISSUE THREAD

**Issue by Ludo-code** [cockpit-project/cockpit#17350] opened 2022-05-17 21:02 UTC
### Explain what happens

Cannot refresh cache whilst offline

Veuillez recharger la page après avoir résolu le problème.

This is the error message when trying to update, I have already tried to change the network manager but doesn't fix the problem.... 

### Version of Cockpit

V269

### Where is the problem in Cockpit?

Software updates

### Server operating system

Ubuntu

### Server operating system version

22.04

### What browsers are you using?

Firefox, Firefox Mobile on Android, Chrome, Chrome on Android, Edge, GNOME Web

**Comment by marusak** [comment] 2022-05-18 06:14
Duplicate of https://github.com/cockpit-project/cockpit/issues/8477
Please see this issue for explanation and workarounds

**Closed by marusak** 2022-05-18 06:14 UTC
Labels: bug
