### ISSUE TITLE
Tests failed on f63bd0b0e4f3d531d740630de870f999615e3715

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21244] opened 2024-11-11 02:27 UTC
The job `fedora-40/updates-testing` failed on commit f63bd0b0e4f3d531d740630de870f999615e3715.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f63bd0b0-20241111-013127-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-11 04:50
Duplicate of #21237

**Closed by martinpitt** 2024-11-11 04:50 UTC
Labels: nightly
