### ISSUE TITLE
Registry user cannot patch error

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#6713] opened 2017-05-26 15:36 UTC
Cockpit version 140
Origin version v1.5.0

Changing project access settings, the following error returned:

    User "aweiteka" cannot "patch" "projectsaweiteka" with name "" in project ""

It appears the project string is not getting passed into the call properly. Related to #4924 but appears to be more actionable based on the error.

![screen shot 2017-05-26 at 11 11 43 am](https://cloud.githubusercontent.com/assets/1764461/26501394/86ea0804-4207-11e7-88eb-7abf8a07ba80.png)

**Comment by aweiteka** [comment] 2017-05-26 15:36
cc @dmsimard

**Comment by petervo** [comment] 2017-05-26 15:39
@aweiteka this seems to be another selfLink problem. What version of openshift are you trying this with?

**Comment by dmsimard** [comment] 2017-05-26 15:40
@petervo this is out of origin 1.5

**Comment by petervo** [comment] 2017-05-26 15:41
This should be getting backported to 1.5.1 see https://bugzilla.redhat.com/show_bug.cgi?id=1447441

**Comment by dmsimard** [comment] 2017-05-26 15:45
@petervo ack, origin 1.5.1 hasn't yet been [tagged for release](https://cbs.centos.org/koji/buildinfo?buildID=17241). I'll try and chime in if I can reproduce this after updating.

**Comment by petervo** [comment] 2017-05-26 17:33
Closing as dup of #6381, please reopen if reproducible with the still unreleased openshift 1.5.1

**Closed by petervo** 2017-05-26 17:33 UTC
