### ISSUE TITLE
Broken journal button group

### ISSUE THREAD

**Issue by pdonlon** [cockpit-project/cockpit#746] opened 2014-06-20 14:32 UTC
- All buttons to the left of a button being selected become selected. Behavior acts like a scroll-bar.

- Deselecting a button behaves as if you are selecting it for the first time, itself and everything to the left of it becomes selected and everything to the right of it becomes deselected. If there is nothing selected to the right of it selected then nothing will happen.

**Comment by stefwalter** [comment] 2015-01-20 11:17
Duplicate of #615 1378

**Closed by stefwalter** 2015-01-20 11:17 UTC
Labels: ui-fixes
