### ISSUE TITLE
WIP: cockpit-tasks-hwmq4: Update machine learning from test logs

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#9696] opened 2018-07-20 04:24 UTC
Perform machine learning tasks such as retrieving new test logs and updating
 * [ ] learn-tests

**Comment by cockpituous** [comment] 2018-07-20 04:24
learn-tests in progress on cockpit-tasks-hwmq4.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9696-20180720-042727/

**Comment by martinpitt** [comment] 2018-07-25 05:20
older duplicate of #9697

**Closed by martinpitt** 2018-07-25 05:20 UTC
Labels: bot
