### ISSUE TITLE
applications: On page load, Applications are not loaded, but clicking refresh shows the apps

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16128] opened 2021-07-22 07:54 UTC
### Discussed in https://github.com/cockpit-project/cockpit/discussions/16127

<div type='discussions-op-text'>

<sup>Originally posted by **Verhoeckx** July 21, 2021</sup>
Hello Cockpit developers,

It took me a while before I realized that I had to click on the refresh button on the page Applications to load the applications (and see them). I think it's good idea to load them immediately after you open the page Applications. Then, I think, the button refresh isn't necessary anymore.

Or just load them the first time.</div>

**Comment by martinpitt** [comment] 2021-07-22 08:04
Agreed. The updates page already does that, the Applications page should as well.

**Comment by marusak** [comment] 2021-07-22 08:36
They get loaded for me automatically. I think there is more to it. @martinpitt and @garrett you both see the same behavior?

**Comment by Verhoeckx** [comment] 2021-07-22 09:24
Great to know that this isn't intended behavior but probably just a bug!

Linux distribution: Red Hat Enterprise Linux 8.4
Version of Cockpit: 238.2 (release 1.el8)
Browser: Firefox 90.0

Let me know if you need more information!

**Comment by martinpitt** [comment] 2021-07-29 15:12
@marusak : Not for me -- I only see the already installed apps, with their "Remove" buttons. I need to click the refresh button to install `appstream-data` and thus get the list of available apps. However, I'm not sure we should do that completely automatically. Right now it sort of happens behind the scenes anyway when the user clicks "refresh", and we don't tell them that we just installed a new package. This is at least the case on Fedora/RHEL, on Debian the appstream metadata is part of `apt-get update` (which certainly *should* happen automatically if it's out of date, like the SW updates page -- but doesn't right now).

**Comment by ne20002** [comment] 2021-08-28 07:41
On my Debian installations I see the installed Apps (storage, machines) right on opening the page. I don't see any other applications and clicking refresh does not bring up any other application.
I'm unsure if there should be any other apps, I believe, if there is a list of apps it probably checks for dependencies? I try setting up SELinux on my system, but it lacks troubelshootd (not available in Debian), so it makes sense to not show this app.

**Comment by KKoukiou** [comment] 2023-01-07 14:07
@ne20002 regarding you comment please follow https://github.com/cockpit-project/cockpit/issues/17737.

Closing this issue as not reproduceable.

**Closed by KKoukiou** 2023-01-07 14:07 UTC
Labels: page:applications
