### ISSUE TITLE
Tests failed on f540cfaef30ae50f4f9fc2e2e1aa7b35623804a0

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21050] opened 2024-09-29 03:11 UTC
The job `fedora-40/updates-testing` failed on commit f540cfaef30ae50f4f9fc2e2e1aa7b35623804a0.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f540cfae-20240929-013136-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-09-30 04:59
Duplicate of #21048

**Closed by martinpitt** 2024-09-30 04:59 UTC
Labels: nightly
