### ISSUE TITLE
Trouble with ssh password authentication between primary and secondary machine when the secondary machine requires two factor code.

### ISSUE THREAD

**Issue by H20-17** [cockpit-project/cockpit#14733] opened 2020-10-12 21:45 UTC
Cockpit version: 228-1
OS: Fedora 32
Page: Connect to secondary machine

Hi,
I set up cockpit a long time ago with ssh keypairs (for all the relevant users) to allow cockpit to automatically connect from the primary machine to all of the secondary ones. That works fine.

All of the secondary machines require two factor for password based ssh logins, so I wanted to see what would happen if I relied on entering a password, so on the secondary machine I renamed ~/.ssh/authorized_keys to ~/ssh/authorized_keys.saved.

This is what happened when I tried to connect from the primary machine. It started off by saying "Not connect to host (Login failed), so I clicked on the "Login" button and a password dialog appeared.

I then typed in my password and the following happened:

1. An error box appeared with a message saying "Internal error"

2. in the logs of the primary machine it said
```
Oct 12 17:20:33 OURSERGORSERV.AD.QUEENSU.CA cockpit-ssh[213075]: cockpit-ssh 192.168.254.3: couldn't authenticate: Access denied for 'publickey'. Authentication that can continue: publickey,password,keyboard-interactive
```

In the logs of the secondary machine it said:
```
 Oct 12 16:19:58 OURSERGORSALT.AD.QUEENSU.CA sshd[185714]: pam_sss(sshd:auth): authentication success; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.254.1 user=waltonm
Oct 12 16:19:58 OURSERGORSALT.AD.QUEENSU.CA sshd[185712]: Received disconnect from 192.168.254.1 port 38692:11: Bye Bye [preauth]
```

It may be that two factor is not supported in this situtation, but the available messages fall in the spectrum of saying nothing to being misleading, and if two factor is supported for the primary login, surely for the sake of consistency it should be supported accross the board, no?

**Comment by martinpitt** [comment] 2021-04-21 17:12
Duplicate of #12982

**Closed by martinpitt** 2021-04-21 17:12 UTC
Labels: review-2021-02
