### ISSUE TITLE
machines: storage pools and networks not visible

### ISSUE THREAD

**Issue by BigBob931** [cockpit-project/cockpit#10829] opened 2018-12-14 06:01 UTC
Hello!
I've installed Cockpit and cockpit-machines preview 184 on centos 7.6 and can't see the new section of storage pools and networks. There's only the list of virtual machines visible. `visrh pool-list` show correctly all pools. Don't know where the problem is.
Tested the same constalation on a fedora 29. No such problems there.

**Comment by KKoukiou** [comment] 2018-12-17 10:50
@BigBob931 thanks for having interest in these.

On your centos host do you have libvirt-dbus package installed? In order to have these features you need it, and afair it is just suggested package for cockpit-machines and not required dependency for centos-7.

**Comment by davewthompson** [comment] 2019-01-02 17:25
@KKoukiou How would we install this? I see the same issue with my Centos installation; I have libvirt installed but I can't see any sections inside Cockpit.

I did install libvirt **after** Cockpit but that shouldn't be in issue, should it?

**Comment by davewthompson** [comment] 2019-01-02 20:00
Actually, @BigBob931 and @KKoukiou , it looks like libvirt-dbus isn't available as a package for CentOS - not sure why - but the documentation for Cockpit notes you can use virsh instead - but it appears this isn't working.

**Comment by KKoukiou** [comment] 2019-01-03 07:03
@davewthompson @BigBob931 the Virtual Machines plugin has much more functionality if libvirt-dbus is installed and what you hit here is part of the functionality that is not available without libvirt-dbus package. This was done deliberately, once we rewrote the plugin some time ago, to stop using virsh and communicate with libvirt with this dbus bindings, we started developing new features only with dbus bindings. Of course the distros that don't include libvirt-dbus package yet will not include the new features. So, from our side this is not a bug. You can of course install the rpm manually or from sources and try the new functionality.

**Comment by KKoukiou** [comment] 2019-01-10 13:44
So, as I mentioned above this functionality is available only if libvirt-dbus package is installed. For distributions that this package is not available unfortunately having this functionality will require some workaround as mentioned above. I am closing the issue here since this is not a bug.

**Closed by KKoukiou** 2019-01-10 13:44 UTC
