### ISSUE TITLE
offline errors when not using Network Manager

### ISSUE THREAD

**Issue by tmjpugh** [cockpit-project/cockpit#8759] opened 2018-03-04 03:45 UTC
Check for new Applications and Loading available updates fail when not using Network Manager.
"Cannot refresh cache whilst offline" or "Cannot download packages whilst offline"  messages received

Expected Behavior
I would expect these function to work regardless of application managing network connection.
If network OK, it should proceed without error

I previously switched to Network Manager and these succeed without issue.

**Comment by martinpitt** [comment] 2018-03-04 08:40
Which operating system are you on? This is a known issue/limitation in Ubuntu 16.04, but this was fixed in later NetworkManager versions. I. e. on Ubuntu 17.10 it should work fine.

**Comment by tmjpugh** [comment] 2018-03-04 11:48
My apology, it is 16.04.

**Comment by martinpitt** [comment] 2018-03-04 19:57
Ack, thanks. This is a duplicate of #8477 then.

**Closed by martinpitt** 2018-03-04 19:57 UTC
Labels: question

**Comment by Bjornskjald** [comment] 2019-07-12 12:14
I'm using Netplan with default renderer (networkd, I guess) on Ubuntu Server 19.04 and unfortunately it still happens.

**Comment by david50407** [comment] 2019-11-11 02:34
same on 18.10

**Comment by edisno** [comment] 2020-04-21 13:54
It might be the same on 20.04 as well.

**Comment by lsaadeh** [comment] 2020-05-21 07:12
having this issue on ubuntu 20.04

**Comment by parbash** [comment] 2020-05-30 01:14
Also having this issue on Ubuntu 20.04

**Comment by redfive2012** [comment] 2021-01-06 02:55
Still a problem on Ubuntu 20.04 LTS. I updated the NetworkManager.conf file to have `managed=true` in the [ifupdown] section and restarted NetworkManager. I'm using NetPlan with networkd as the renderer. I've got a whole bunch of bonds and VLANs, so I really don't want to mess that up.

**Comment by ethanpil** [comment] 2026-06-16 19:07
Fix that worked for me today in Debian 13:

```
sed -i '/\[ifupdown\]/,/managed=/ s/managed=false/managed=true/' /etc/NetworkManager/NetworkManager.conf
systemctl restart NetworkManager
systemctl restart packagekit
nmcli networking off
nmcli networking on
```
