### ISSUE TITLE
White-Screen after login in some Chromium browsers

### ISSUE THREAD

**Issue by kasuganosoras** [cockpit-project/cockpit#12745] opened 2019-09-09 17:15 UTC
Cockpit version: 197.3
OS: Windows 10 (My PC) and CentOS 7 (My Server)
Page: homepage (after login)

I use the Chrome 74.0 visit the web page, after I login there are not thing display, just a white screen. I try to clear cookie and browser caches but it doesn't work.

Steps to reproduce

1. Use Chrome browser 74.0 to open http://server-ip:9090/
2. Input the username and password, then login.
3. Login is successful, but there are not thing display.

When I open the browser developer tool, I saw some errors in console:
```
Uncaught ReferenceError: cockpit is not defined
    at Object.<anonymous> (index.js:1)
    at n (index.js:1)
    at Module.<anonymous> (index.js:35)
    at n (index.js:1)
    at Object.<anonymous> (index.js:35)
    at n (index.js:1)
    at index.js:1
    at index.js:1
```
I also try the Firefox 68.0, It working fine.
Sorry for my bad English 😂

**Comment by SteffenM-DE** [comment] 2019-09-16 13:41
Hi,
same here. Blank page after login with chrome and edge (new edge beta with chrome engine working).
Regards, Steffen

**Comment by philippjess** [comment] 2019-09-28 15:55
I have the same Issue, but its working fine in Chrome 77. I get that problem when i use Firefox 69.

**Comment by CromAr** [comment] 2019-11-04 13:53
Same here, Chrome version 78. Edge gets the Same. I have actually no chance to have a look at cockpit

**Comment by riccardolardi** [comment] 2019-12-09 09:31
Getting lots of `ERR_EMPTY_RESPONSE` as well as `Uncaught ReferenceError: Cockpit is not defined` on Chrome Version 78.0.3904.108 (Official Build) (64-bit) Mac OS 10.15.1

**Comment by Revertron** [comment] 2019-12-28 16:25
Works fine on Chrome 79.0.3945.88, but shows white screen on Firefox 72.0b11.

**Comment by asumos** [comment] 2020-01-20 03:57
same issue

cockpit version: 188
OS: debian 10.2
Browser: Chrome Version 79.0.3945.130 (Official Build) (64-bit)

works with firefox 72.0.1 (64-bit)

**Comment by alexwiese** [comment] 2020-02-16 10:56
I had the same problem and resolved it by disabling this extension:

- Disable HTML5 Autoplay (Reloaded)
ID: cafckninonjkogajnihihlnnimmkndgf

**Comment by philippjess** [comment] 2020-02-16 12:50
Incredible, you found it. Turning it off is not enough, you have to completely disable the extension, which is unacceptable. Does anyone know a working alternative to the extension?

**Comment by SteffenM-DE** [comment] 2020-02-16 14:40
> I had the same problem and resolved it by disabling this extension:
> 
> * Disable HTML5 Autoplay (Reloaded)
>   ID: cafckninonjkogajnihihlnnimmkndgf

I have no extension installed and I can not login anymore:

Connection failed
There was an unexpected error while connecting to the machine.
Messages related to the failure might be found in the journal:
journalctl -u cockpit

**Comment by alexwiese** [comment] 2020-02-18 22:34
> > I had the same problem and resolved it by disabling this extension:
> > 
> > * Disable HTML5 Autoplay (Reloaded)
> >   ID: cafckninonjkogajnihihlnnimmkndgf
> 
> I have no extension installed and I can not login anymore:
> 
> Connection failed
> There was an unexpected error while connecting to the machine.
> Messages related to the failure might be found in the journal:
> journalctl -u cockpit

Looks like that's a totally different issue. 
Make sure cockpit is running, no errors in log, etc.

**Comment by SteffenM-DE** [comment] 2020-02-19 06:50
Cockpit is running and log is showing this:

Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: TLS handshake failed: The TLS connection was non-properly terminated.
Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: TLS handshake failed: The TLS connection was non-properly terminated.
Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: reading from client fd 6 TLS connection failed: The TLS connection was non-properly term
Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: reading from client fd 7 TLS connection failed: Error in the pull function.
Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: reading from client fd 8 TLS connection failed: The TLS connection was non-properly term
Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: reading from client fd 9 TLS connection failed: The TLS connection was non-properly term
Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: reading from client fd 10 TLS connection failed: The TLS connection was non-properly ter
Feb 19 07:46:43 host001.dom.local cockpit-tls[13787]: cockpit-tls: reading from client fd 13 TLS connection failed: The TLS connection was non-properly ter
Feb 19 07:46:48 host001.dom.local cockpit-session[13793]: pam_ssh_add: Failed adding some keys
Feb 19 07:46:48 host001.dom.local cockpit-session[13793]: pam_unix(cockpit:session): session opened for user user1 by (uid=0)
Feb 19 07:46:48 host001.dom.local cockpit-ws[13789]: logged in user session
Feb 19 07:46:49 host001.dom.local cockpit-tls[13787]: cockpit-tls: reading from client fd 16 TLS connection failed: The TLS connection was non-properly ter
Feb 19 07:46:49 host001.dom.local cockpit-tls[13787]: cockpit-tls: TLS handshake failed: A TLS fatal alert has been received.

With Edge (non Chrome) everything is working but with chrome etc. I can not login.

**Comment by balthisar** [comment] 2020-03-31 20:39
Well, I'll be darned... HTML5 Autoplay (Reloaded) is the culprit. I don't want to completely disable it, but if not enabled in Incognito, then Inognito works fine. Or in a regular window, hitting Reload one or twice will usually bring up the correct display.

**Comment by kasuganosoras** [comment] 2020-04-02 04:52
That's cool. It really working now. Thanks!

**Comment by fakhamatia** [comment] 2020-05-05 18:30
```
Uncaught ReferenceError: cockpit is not defined
    at Object.4 (logs.js:5)
    at n (logs.js:1)
    at Module.389 (logs.js:5)
    at n (logs.js:1)
    at Object.388 (logs.js:5)
    at n (logs.js:1)
    at logs.js:1
    at logs.js:1
```
Same problem with Chrome 81 Ubuntu 19.10

**Comment by 0987363** [comment] 2020-06-10 06:43
Same problem with Chrome 83 Mac osx 10.14.6

```
content.js:4 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:4
content.js:5 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:5
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://xxxxx.com:8008/cockpit/$51e7c760309cdec8b03cd295bc0ae5d7425e7cd0b0e27fb3745caec48b8e7235/base1/jquery.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
system:12 GET https://xxxxx.com:8008/cockpit/$51e7c760309cdec8b03cd295bc0ae5d7425e7cd0b0e27fb3745caec48b8e7235/base1/cockpit.js net::ERR_TOO_MANY_REDIRECTS
system:14 GET https://xxxx.com:8008/cockpit/$51e7c760309cdec8b03cd295bc0ae5d7425e7cd0b0e27fb3745caec48b8e7235/*/po.js net::ERR_TOO_MANY_REDIRECTS
```

But waterfox classic 2020.05 is fine.

**Comment by martinpitt** [comment] 2021-03-03 16:55
Closing as it was an issue with a browser extension (HTML5 autoplay)

**Comment by timdonovanuk** [comment] 2021-04-27 02:55
I don't have this Chrome extension but get the same issue. Works fine in Chrome running in guest mode, i.e. no plugins.

**Comment by coopbri** [comment] 2021-04-27 08:02
I also have this issue in Chromium (Brave). It works in Private Mode (Incognito), but not in a regular session (even with all extensions and Brave shields disabled). Works great on Firefox!

**Comment by Ferryistaken** [comment] 2021-05-05 23:45
I have this issue in brave as well(`Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)`)

**Comment by EHRETic** [comment] 2021-06-04 06:47
> SECOND EDIT: Nevermind it didn't fix the issue, now I "only" have to refresh 3-4 times and then cockpit will work as usual

Thanks a lot for that "solution"! 😁
I'm wondering where is the problem exactly because in Chrome, it works fine (and I want to get rid of it...)

**Comment by Ferryistaken** [comment] 2021-06-04 20:20
The very strange thing is that it works after a few refreshes so brave isn't completely "breaking" cockpit. 
Curious behavior but with the refresh method it's at least usable (even if extremely annoying).

**Comment by ragnaroks** [comment] 2021-06-10 01:36
same problem,disable all plugin/extension are not effect,but use privacy mode is work fine

**Comment by egee-irl** [comment] 2021-06-26 13:09
This bug still appears to be an issue and is an almost-blocker for me.

I'm seeing it on Fedora 33, Fedora 34, and openSUSE Tumbleweed. Curiously, I am **not** seeing it on Ubuntu distributions.

As someone else said, refreshing the page a half dozen times "fixes" it until I have to log in again.

**Comment by Ferryistaken** [comment] 2021-06-27 14:17
For me now (Brave Browser 91.1.26.67, Cockpit v 246 release 1.fc34 on Fedora Workstation 34) I only need to refresh once, but the problem persists (same on arch and nvidia's build of ubuntu, can't speak for stock ubuntu)

**Comment by infinytum** [comment] 2021-07-03 20:56
I am facing this issue with Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) and an Up-to-Date RHEL 8 Server. Firefox works no problem, its just chrome-ish browsers that cannot open cockpit.

**Comment by MCUmbrella** [comment] 2021-07-04 08:46
same here, even with incognito mode enabled. btw is there a way to disable the 'html5 autoplay'? using Firefox developer edition 90.0b12 x64

**Comment by MCUmbrella** [comment] 2021-07-09 09:02
> 
> 
> same here, even with incognito mode enabled. btw is there a way to disable the 'html5 autoplay'? using Firefox developer edition 90.0b12 x64

I found that this problem was caused by [ruffle](https://github.com/ruffle-rs/ruffle) on my computer. After disabling this plugin the page is displayed normally

**Comment by garrett** [comment] 2021-07-28 14:43
I have Brave, Edge, Google Chrome, and Ungoogled Chromium installed here (as well as Firefox), all installed via Flathub, running on Fedora 34:

- Brave: Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) unknown (64-bit): blank screen; can't load Cockpit
- Edge (beta): Version 92.0.902.55 (Official build) beta (64-bit): Works
- Chromium: Version 91.0.4472.164 (Official Build, ungoogled-chromium) (64-bit): Works
- Google Chrome: Version 92.0.4515.107 (Official Build) (64-bit) 
- Firefox: 90.0.2 (64-bit): Works

Everything but Brave works fine here. This is on Cockpit built from the main branch as of today.

**Comment by Ferryistaken** [comment] 2021-07-28 15:41
TBH for the past week brave worked for me. I'm pretty sure it's a bug within brave that we should report since the behaviour isn't always the same.

I use Brave  92.1.27.109 with Fedora 34 (installed from RPM)

**Comment by garrett** [comment] 2021-07-29 08:15
I just installed the latest version of Brave using RPM from within a toolbox on Fedora 34 and I still see the issue.

`Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)`

And I've tried the beta channel. Same issue. That's:

`Version 1.28.92 Chromium: 92.0.4515.107 (Official Build) beta (64-bit)`

And nightly; it still has the blank page problem. It's:

`Version 1.29.27 Chromium: 92.0.4515.107 (Official Build) nightly (64-bit)`

I'm installing a fresh copy of Fedora 34 in a VM now to install the RPM version to see what happens. I'm on Fedora 34 Silverblue and running the flatpak of Brave with issues and also the RPM version with the same issues in toolbox, so I'll see if I can get Brave to work exactly as you see it, @Ferryistaken, in case there's some lower level thing that's different in Silverblue that might be affecting the issue.

**Comment by garrett** [comment] 2021-07-29 08:20
Retitled to make it applicable to Chromium browsers, re-opening for Brave. Other Chromium browsers seem unaffected, at least right now; it seems to be something Brave-specific.

**Comment by martinpitt** [comment] 2021-08-06 07:23
I installed brave into a F34 toolbox according to their [excellent install instructions](https://brave.com/linux/#fedora-28-centosrhel-8-1) (honestly, this is exemplary -- proper RPMs and repo signatures!) and got brave-browser-beta-1.29.51-1.x86_64, so slightly newer than @garrett. I start the browser with `HOME=/tmp/h brave-browser-beta` to make sure that it does not leave anything permanent on my home dir, and results stay reproducible.

I confirm the "white screen" problem both with using unencrypted HTTP (http://localhost:9090) as well as https with ack'ing the self-signed certificate. So I think this is not a problem with the websocket and certificates after all.

**Comment by martinpitt** [comment] 2021-08-06 08:27
This is not specific to the shell. Going directly to a frame on e.g. http://localhost:9090/cockpit/@localhost/system/terminal.html has the same result. The page does a `<script src="../base1/cockpit.js"></script>` properly, which should import the `cockpit` object. Our webpack does deliberately decleare this as an external, as we don't want to bundle it everywhere. I've tried for half an hour to webpack-bundle cockpit.js, but that is going poorly, as it is *very* far away from being a proper ESM.

Stuff that I tried. This did not  help, but I validated all of these in firefox, that they don't break a known-good browser:

  * Network inspector confirms that cockpit.js gets loaded successfully and has the right contents.
  * Strip out the included CSS in pkg/base1/cockpit.js
  * `cp pkg/base1/cockpit.js dist/base1/` to strip off the webpack wrapping

But I saw an interesting change when moving the `cockpit` var out of the "init" function:
```
--- dist/base1/cockpit.js.orig	2021-08-06 10:21:13.560022515 +0200
+++ dist/base1/cockpit.js	2021-08-06 10:21:14.927028304 +0200
@@ -40,8 +40,8 @@
 /* injected by tests */
 var mock = mock || { }; // eslint-disable-line no-use-before-define
 
-(function() {
 var cockpit = { };
+(function() {
 event_mixin(cockpit, { });
 
 /*
```

Then the error message changes:
```
Uncaught TypeError: cockpit__WEBPACK_IMPORTED_MODULE_0___default(...).dbus is not a function
    at Superuser (superuser.js:73)
    at Module../pkg/lib/superuser.js (superuser.js:126)
    at __webpack_require__ (bootstrap:19)
    at make namespace object:7
    at sosreport.js:11331
    at sosreport.scss?2ab1:1
```
I confirmed with a console.log that the init function *does* get called under Brave, so that's not it. I also entirely droped the init function and made the whole code global, but that does not change anything either. In the JS console I now see the `cockpit` object, but it only has the `event_mixin` and standard object properties, nothing else. And sure enough, with

```diff
--- dist/base1/cockpit.js.orig	2021-08-06 10:21:13.560022515 +0200
+++ dist/base1/cockpit.js	2021-08-06 10:26:40.530415679 +0200
@@ -40,10 +40,12 @@
 /* injected by tests */
 var mock = mock || { }; // eslint-disable-line no-use-before-define
 
-(function() {
 var cockpit = { };
+
 event_mixin(cockpit, { });
 
+console.log("XXX initializing cockpit object");
+
 /*
  * The debugging property is a global that is used
  * by various parts of the code to show/hide debug
@@ -3584,6 +3586,7 @@
     };
 
     /* public */
+    console.log("XXX initializing cockpit.dbus");
     cockpit.dbus = function dbus(name, options) {
         if (!options)
             options = { bus: "system" };
@@ -4645,4 +4648,3 @@
     else
         define([], factory); // eslint-disable-line no-undef
 }
-})();
```
.. the "XXX initializing cockpit.dbus" never appears in Brave.

**Comment by martinpitt** [comment] 2021-08-06 08:45
The bug is how [cockpit.js loads itself](https://github.com/cockpit-project/cockpit/blob/32370e287505683cb2b0970d31f240884b370f8c/pkg/base1/cockpit.js#L4626). It does some weird check on `document.scripts`, and assumes that it's always the last item. In Firefox, the array is indeed one element long, with `http://localhost:9090/cockpit/@localhost/base1/cockpit.js`. But in Brave, there is a second array entry with an empty entry, and thus `last` is empty, and thus `factory()` is not ever called.

**Comment by martinpitt** [comment] 2021-08-06 09:27
Fixed in PR #16211

**Closed** 2021-08-06 14:15 UTC

**Comment by iongion** [comment] 2021-09-10 09:47
On latest brave, disable ublock origin if you have it for that host and all is good. Refresh and it all works.

**Comment by garrett** [comment] 2021-09-13 11:57
> On latest brave, disable ublock origin

@iongion: Cockpit _should_ work for you with uBlock Origin enabled too, unless you have some specific advanced options enabled (like blocking _all_ scripts and/or iframes... including first party and inline) or custom rules that might block resources. Can you confirm if Brave + uBlock Origin works for you? Thanks!

I've tested it here, and not only does Cockpit work fine with uBlock Origin on Firefox, it also works fine with uBlock Origin (with default settings, at least) on Brave too.

**Comment by iongion** [comment] 2021-09-13 12:58
@garrett - indeed, actually it solved it only once.

The cockpit version is the one provided by coreos from `podman machine init`, from default repos.
I will wait for the maintainer to upgrade one day, meanwhile, firefox is ok as alternative to brave.

**Comment by Dragonlord1005** [comment] 2021-10-13 22:21
just confirmed with firefox, issue with brave

**Comment by garrett** [comment] 2021-10-18 07:35
@Dragonlord1005: Thanks for sharing your OS and browser versions. Using the latest backports version on Ubuntu 21.04 should have also fixed it, but upgrading to 21.10 is a great solution too, as you get newer _everything_.

I'm happy it's solved for you now with the newer version!

**Comment by J-dotjs** [comment] 2023-12-11 19:58
still happens for raspberry pi 4 all is updated, no extensions on firefox, chrome works

**Comment by garrett** [comment] 2023-12-12 09:22
@J-dotjs: I have a Raspberry Pi 4 running Fedora IoT with Cockpit and use Firefox (even with extensions). There's not a problem here.

What are you running on your Raspberry Pi 4? What Linux distribution and what version? And what version of Cockpit? These are all things that would make a huge difference. (The hardware itself doesn't matter as much as the software.)

**Comment by J-dotjs** [comment] 2023-12-12 14:43
> @J-dotjs: I have a Raspberry Pi 4 running Fedora IoT with Cockpit and use Firefox (even with extensions). There's not a problem here.
> 
> What are you running on your Raspberry Pi 4? What Linux distribution and what version? And what version of Cockpit? These are all things that would make a huge difference. (The hardware itself doesn't matter as much as the software.)
> 
> This particular issue would only sometimes show up in some browsers (as they changed how CSP was handled two and a half years ago) and was quickly fixed two and a half years ago in Cockpit and the fix was included in Cockpit 251. Please make sure you update your OS and Cockpit — the latest version of Cockpit is 306; we're about to release 307 later this week.
> 
> We have information on how to install and update Cockpit @ https://cockpit-project.org/running.html — in the case of Debian and Ubuntu, you might need to use backports to get the latest, in some cases. But even non-backport packages should still work.

It's only with the bitwarden extension.

**Comment by garrett** [comment] 2023-12-12 16:36
@J-dotjs: Again, you need to provide basic details:

- What version of Cockpit? 
- What distribution (and distribution version)?
- What browser version? (You said Firefox, but didn't say which version.)
- Any other details that could help provide insight as to what's going on with your system.

**Comment by J-dotjs** [comment] 2023-12-12 16:48
> @J-dotjs: Again, you need to provide basic details:
> 
> - What version of Cockpit? 
> - What distribution (and distribution version)?
> - What browser version? (You said Firefox, but didn't say which version.)
> - Any other details that could help provide insight as to what's going on with your system.

Latest version of everything it's what I said on my first comment 🤔

**Comment by garrett** [comment] 2023-12-13 11:17
@J-dotjs: Again, you're not going to get any help whatsoever if you don't tell us the specific versions. "Latest version" of "everything" is completely meaningless. Be specific. 

We still don't know what distribution you're running, nor what specific version of it, nor what specific version of Cockpit, nor what version of Firefox.

There might be a bug somewhere that might still exist (which could be unrelated to this issue which was fixed 2 and a half years ago), or you could be running "the latest [available] version" of Cockpit on an old, unsupported Debian that went EOL years ago.

Be specific.

**Comment by J-dotjs** [comment] 2023-12-15 03:03
latest version is very specific @garrett

**Comment by J-dotjs** [comment] 2023-12-15 03:06
> latest version is very specific @garrett

and honestly i have no idea on how to get the version number of cockpit 

Firefox ver 120.0.1

removing the bitwarden extension makes it work but its very inconvenient

**Comment by martinpitt** [comment] 2023-12-15 06:42
Trouble with bitwarden extension is tracked in #19624

**Comment by J-dotjs** [comment] 2023-12-15 20:27
> Trouble with bitwarden extension is tracked in #19624

Thanks for being useful unlike @garrett
