### ISSUE TITLE
Ubuntu: Dependency conflict when building from source!

### ISSUE THREAD

**Issue by Micrified** [cockpit-project/cockpit#11461] opened 2019-03-25 16:35 UTC
## Ubuntu
OS: Ubuntu 18.04.2 LTS, 

When following the build from source guide located [here](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md), the build step with `autogen` will fail because of a dependency removal cycle on Ubuntu. The clash is between `npm` and `libssh`. 

---
### Step by Step 

The step: 

``` sudo apt-get install nodejs npm ```

Installs `npm`. Then the step:

```$ ./autogen.sh --prefix=/usr --enable-debug```

Will eventually tell you (see the output of the build script [here](https://pastebin.com/raw/dS8HLDiK)): 

```No package 'libssh' found```

If you try to install `libssh-dev`, it will uninstall `npm` though: 

```
The following packages will be REMOVED:
  libssl1.0-dev node-gyp nodejs-dev npm
```

In fact, this [answer](https://unix.stackexchange.com/a/408426/287731) on unix.stackexchange explains that they cannot coexist.

**Comment by martinpitt** [comment] 2019-03-27 11:04
This is a duplicate of issue #11104. There is unfortunately nothing we can do about this, in 18.04 and 18.10 npm  and libssh are simply not co-installable. This will be fixed in 19.04, or build it in 16.04 LTS (you can use a chroot/schroot/pbuilder/container/etc.)

**Closed by martinpitt** 2019-03-27 11:04 UTC
