### ISSUE TITLE
"Ooops" message pops up on Web Console.

### ISSUE THREAD

**Issue by mmuto118** [cockpit-project/cockpit#18347] opened 2023-02-15 07:18 UTC
### Explain what happens

1.I access to Web Console.
2. "Ooops" message pops up on Web Cosole.
3. I click "Ooops" message and the below message is shown.
```
Unexpected error
Cockpit had an unexpected internal error.

You can try restarting Cockpit by pressing refresh in your browser. The javascript console contains details about this error (Ctrl-Shift-J in most browsers).
```

### Version of Cockpit

264-1ubuntu0.22.04.1 all

### Where is the problem in Cockpit?

Overview

### Server operating system

Ubuntu

### Server operating system version

"22.04.1 LTS (Jammy Jellyfish)"

### What browsers are you using?

Chrome, Edge

### System log

```shell
#####error log

terminal.js:2 FormSelect requires either an id or aria-label to be specified
ie @ terminal.js:2
updates.js:2 Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
（匿名） @ updates.js:2
updates.js:2 Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"

Uncaught TypeError: Cannot set properties of undefined (setting 'vendor_urls')
    at Object.UpdateDetail (updates.js:2:1102472)
    at ae.<anonymous> (updates.js:2:402375)
    at cockpit.js:1:31321
    at L (cockpit.js:1:12242)
```
```

**Comment by mmuto118** [comment] 2023-02-15 07:20
![image](https://user-images.githubusercontent.com/97217099/218959226-b4dc4474-f86c-4ff1-ba0e-9975a7ad9fff.png)

**Comment by martinpitt** [comment] 2023-02-15 07:29
Duplicate of #17405 . This got fixed in version 272, please install a newer version from backports. Thanks!

**Closed by martinpitt** 2023-02-15 07:29 UTC
Labels: bug

**Comment by mmuto118** [comment] 2023-02-15 07:32
> Duplicate of #17405 . This got fixed in version 272, please install a newer version from backports. Thanks!
@martinpitt 
Thank you for leading me to #17405.
I will install version 272.

**Comment by mmuto118** [comment] 2023-02-16 05:37
> Duplicate of #17405 . This got fixed in version 272, please install a newer version from backports. Thanks!

sorry to add comments due to Closed stats.
is this correct to install the below command for a new version from backports?
```. /etc/os-release
sudo apt install -t ${VERSION_CODENAME}-backports cockpit
```

**Comment by martinpitt** [comment] 2023-02-16 05:56
Yes, that should work.

**Comment by jangotek** [comment] 2024-10-19 23:59
the error still there on latest version of cockpit 326 on firefox but on other browser like edge no error
