### ISSUE TITLE
Tests failed on 86e2b69e8b6ec1e5373fa6f9d0323361113a03ac

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20603] opened 2024-06-17 02:22 UTC
The job `fedora-40/daily` failed on commit 86e2b69e8b6ec1e5373fa6f9d0323361113a03ac.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-86e2b69e-20240617-013016-fedora-40-daily/log.html

**Comment by martinpitt** [comment] 2024-06-17 05:08
Duplicate of #20542

**Closed by martinpitt** 2024-06-17 05:08 UTC
Labels: nightly
