### ISSUE TITLE
Tests failed on ab2d7bea1cc9b379988412a841de2e41548e8259

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21428] opened 2024-12-13 02:45 UTC
The job `fedora-41/updates-testing` failed on commit ab2d7bea1cc9b379988412a841de2e41548e8259.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-ab2d7bea-20241213-013215-fedora-41-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-12-13 04:10
Duplicate of #21424

**Closed by martinpitt** 2024-12-13 04:10 UTC
Labels: nightly
