### ISSUE TITLE
Tests failed on 8fa8a269e42ce5bcc2142145d1df5375b56c9551

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21139] opened 2024-10-20 02:27 UTC
The job `fedora-40/updates-testing` failed on commit 8fa8a269e42ce5bcc2142145d1df5375b56c9551.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-8fa8a269-20241020-013127-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-21 05:25
Duplicate of #21137

**Closed by martinpitt** 2024-10-21 05:25 UTC
Labels: nightly
