### ISSUE TITLE
Allow searching the journal

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1281] opened 2014-10-01 11:12 UTC
Test day suggestion: We no longer have a way to search the journal. We should add this feature back.

**Comment by andreasn** [comment] 2019-10-21 07:33
#1535 is a duplicate of this

**Comment by marusak** [comment] 2020-05-12 15:09
Implemented in https://github.com/cockpit-project/cockpit/pull/13905

**Closed by marusak** 2020-05-12 15:09 UTC
Labels: enhancement
