### ISSUE TITLE
Tests failed on 5ff98a2117e2815f7560e31d67bb1be69ed2e33e

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20209] opened 2024-03-21 02:38 UTC
The job `fedora-39/updates-testing` failed on commit 5ff98a2117e2815f7560e31d67bb1be69ed2e33e.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-5ff98a21-20240321-012453-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-03-21 05:34
Fix is waiting in #20202, so yet another duplicate of #20184

**Closed by martinpitt** 2024-03-21 05:34 UTC
Labels: nightly
