### ISSUE TITLE
Please mention the distro and minimal version it has been tested to be 'fully' functional

### ISSUE THREAD

**Issue by zaxebo1** [cockpit-project/cockpit#2912] opened 2015-10-06 16:50 UTC
from README.md ( https://github.com/cockpit-project/cockpit/blob/master/README.md ) or documentation ( http://files.cockpit-project.org/guide/0.77/ ),  it is Not clear that this has been tested on RHEL 6 or CentOS 7 or Ubuntu 14.04 or ubuntu 12.04 LTS or Debian 7 or Debian 8 or Arch Linux. Note that Ubuntu 12.04LTS is still under official support of canonical. 

**That is, in atonce it is not clear that which Distro and 'on Which minimal version of that distro' - cockpit has been officially/unofficially tested or recommended on.** 
**Kindly put it in documentation.**

**Comment by zaxebo1** [comment] 2015-10-06 16:54
on unofficial article, ihttp://www.ubuntugeek.com/cockpit-a-remote-manager-for-gnulinux-servers.html -- it mentions a PPA to install cockpit, 

BUT on official page, https://github.com/cockpit-project/cockpit/blob/master/HACKING.md , there is only mention of Fedora and Rawhide; not about any other linux distribution.

**Comment by dperpeet** [comment] 2015-10-06 20:30
@andreasn @stefwalter
I think this might be a good candidate for a wiki page... on the other hand, it is also something we'd like to automatically update when releasing a version of cockpit. Maybe a mix? We can keep OS/version and cockpit version combinations on the homepage that we actively push(ed) to and others can add themselves to the wiki. Unnecessary segregation or workable?

**Comment by stefwalter** [comment] 2015-10-06 21:05
The current set of distros that people contributors have worked to make Cockpit run well on are listed here:

http://cockpit-project.org/running.html

**Comment by zaxebo1** [comment] 2015-10-07 00:50
i fear that it is not clear on how much stable is cockpit regarding Debian/Ubuntu family. 
http://cockpit-project.org/running.html
url does not mention Debian/ubuntu. and it says "(c) Redhat 2014"

===
BUT There are lots of links , which tell how can you install it on ubuntu

http://sourcedigit.com/17066-install-cockpit-server-administrator-manager-for-linux-ubuntu-systems/
http://www.ubuntugeek.com/cockpit-a-remote-manager-for-gnulinux-servers.html
https://launchpad.net/~jpsutton/+archive/ubuntu/cockpit

====

This link states that Cockpit is a Red Hat sponsored tool - it is not clear today it will manage Ubuntu.
http://askubuntu.com/a/489591

====

https://liquidat.wordpress.com/2014/02/11/first-look-at-cockpit-a-web-based-server-management-interface/
This links states that "cockpit requires systemd". 

Now that ubuntu 15.04 has switched from upstart to systemd and Debian also has switched to systemd, so is it safe to assume that  now basci requirements have been met?

====

Actually it seems many bloggers are opinionated that cockpit is redhat sponsored tool and will work well only on redhat distributions. 
I just want to be reassured that although the fedora/RHEL may be primary target - but porting contributions to other distro families will not be seen as separate secondary step child, or patches that will have to be maintained separately. 
May be if project somewhere states that - 'its goal is to be distribution agnostic , though the mileage may vary in different distributions. That is , being tied to one distro family, is not in its goal. Or, redhat being a kind good sponsor of the project will not mean that the second biggest family (debian) will not be part of core vision, even if one wants to contribute'

---

i hope that i could convey what i wanted to say. 
**Somewhere the project should formally deal with "its agnostic position regarding linux distribution or distribution family", just to reassure the probable contributors , probable users**

**Comment by stefwalter** [comment] 2015-10-07 07:35
> i fear that it is not clear on how much stable is cockpit regarding Debian/Ubuntu family. http://cockpit-project.org/running.html

Indeed.

> url does not mention Debian/ubuntu. 

Because nobody has done a pull request to change that page? The page's repository is here, and if you have time, it would be great if you could add Ubuntu:

https://github.com/cockpit-project/cockpit-project.github.io

> and it says "(c) Redhat 2014"

Indeed, that's unfortunate. Although various files in the sources do carry a (c) notice from the author that contributed it ... and many source files were contributed by RedHat ... having this on the web page precludes modifications and is incorrect. @andreasn Do you think we can remove this from the web page?

> BUT There are lots of links , which tell how can you install it on ubuntu

Lets add one of these to the running.html page? Which ubuntu PPA repository is the most stable? Could you contribute the change to the running.html page? We should probably have a warning that states that Cockpit is not a part of Ubuntu repository, and the PPA is "best effort" no?

> This link states that - "Cockpit is a Red Hat sponsored tool - it is not clear today it will manage Ubuntu." http://askubuntu.com/a/489591

I think it mostly works ... but beyond that it's all about the contributions. For example, it takes a significant effort to test and deliver Cockpit across an entire distribution, but I think it would be awesome if there was effort towards doing that on Ubuntu. I think our current testing infrastructure could run such tests.

> I acknowledge that Arch port is a different distribution family . But still as ubuntu is the real worthy commercial competitor to Redhat RHEL in corporate clouds, so main concern is about ubuntu/debian patches acceptability in official vision/goal.

I have never ever seen an Ubuntu or Debian patch rejected (there have been a few).

> This links states that "cockpit requires systemd". Now that ubuntu 15.04 has switched from upstart to systemd and Debian also has switched to systemd, so is it safe to assume that now basic requirements have been met?

Yes it has.

> Actually it seems many bloggers are opinionated that cockpit is redhat sponsored tool and will work well only on redhat distributions. I just want to be reassured that although the fedora/RHEL may be primary target - but porting contributions to other distro families will not be seen as separate secondary step child, or patches that will have to be maintained separately.

Nope. They should not have to be maintained separately, or be secondary step children. To be a first class distro, one would need to:

 1. Contribute patches to make Cockpit work in areas that currently fall over on that distro.
 2. Contribute changes to the testing infrastructure (see the tests directory) which make the Cockpit integration tests work.
 3. Actively work to keep the infrastructure on the distro in sync and working.

By doing these things, the distro becomes first class. Each and every pull request would be tested against the other distro, so that regressions or bugs are handled appropriately.

> May be if project somewhere states that - 'its goal is to be distribution agnostic , though the mileage may vary in different distributions. That is , being tied to one distro family, is not in its goal. Or, redhat being a kind good sponsor of the project will not mean that the second biggest family (debian) will not be part of core vision, even if one wants to contribute'

Indeed. That makes a lot of sense. I think it makes sense to document this properly. 

I'll try and work on better messaging in this area, and update the cockpit website with an explanation like that, perhaps a FAQ would be appropriate, and also a blog post.

Could you do the work to contribute an Ubuntu PPA link for the running.html page, along with a logo that looks correct along side the others?

**Comment by zaxebo1** [comment] 2015-10-07 08:25
okk. I would happy to be of any use  :-)

Ubuntu 15.10 is coming just after three weeks. Let it release, and then i will atonce contribute the PPA which is "properly tested" with latest release and LTS simultaneously..

**Comment by andreasn** [comment] 2015-10-20 10:37
> Indeed, that's unfortunate. Although various files in the sources do carry a (c) notice from the author that contributed it ... and many source files were contributed by RedHat ... having this on the web page precludes modifications and is incorrect. @andreasn Do you think we can remove this from the web page?

Sure.
I created a pull request to reflect the bigger contributor base https://github.com/cockpit-project/cockpit-project.github.io/pull/34

**Comment by Conzar** [comment] 2015-11-02 01:43
The cockpit client doesn't work on Ubuntu 14.04 due to not having systemctl.

**Comment by zaxebo1** [comment] 2015-11-02 04:27
@Conzar :  it will work only on ubuntu 15.04 and 15.10 and any later future version.
if you want LTS release then it you will have to wait for ubuntu 16.04 LTS

**Comment by Conzar** [comment] 2015-11-02 04:33
@zaxebo1 anyway to make it work on non-systemd systems?  I mean, writing init scripts is pretty easy so is there anything in cockpit's client that is a major dependency on something in systemd other than just starting the deamons?

**Comment by zaxebo1** [comment] 2015-11-02 04:45
as of now, no readymade solution exists. 
cockpit was initially very intermingled in redhat platform. so it has only systemd support as of now.

even the arch linux port of cockpit works , only the date after arch linux also moved to systemd
https://bbs.archlinux.org/viewtopic.php?pid=1149530#p1149530

====

But it is technically definitely feasible to make cockpit work on "upstart" (competitor of "systemd" ) too. But the incentive is not there for us. Arch , Debian testing , Ubuntu non-LTS all have already switched to systemd, and ubuntu LTS with systemd is only six months away(April 2016). 
So writing a solution - which is stop gap only for "six months"(april 2016) is not of particular interest of anybody.

as on date, initramfs etc in embedded linux based on arch, are also running systemd.

So, the thinking is that : why to undertake a project effort, whose life span is so short.

**Comment by Conzar** [comment] 2015-11-02 04:56
@zaxebo1 Ubuntu 14.04 LTS is [supported](https://wiki.ubuntu.com/LTS) until mid 2019.  So I think support for Ubuntu 14.04 is pretty important especially since ALL of my companies infrastructure runs on 14.04.  We currently have no plan for upgrading to 16.04 at this stage.  Usually we wait a year or so after the LTS has been out to do the massive upgrade (gives us plenty of time to make any changes SUCH as SystemD --- you can imagine that all the software we deploy that has init scripts will need to be modified so we aren't excited about the move).  

Can you point me in the code to where the systemd stuff lives?  Is it just a matter of starting, stopping, and restarting the service?  If so, I maybe interested in developing that bit as we have some motivation here.

**Comment by zaxebo1** [comment] 2015-11-02 06:44
one quick shot way to point is : 

1) download the code 

2)inside the $COCKPIT_SOURCE_TOP_DIR, now run the following command:

    grep -rin systemd *

    grep -rin systemctl *

if you are just interested in pure source code files(not in doc,test etc), then you can run the above command in $COCKPIT_SOURCE_DIR/src

   
This will give you fair indication to where to start

**Comment by Conzar** [comment] 2015-11-02 08:04
Seems the main file that contains systemd headers (#include <systemd/sd-daemon.h>
) is src/common/cockpitwebserver.c.

Why is the systemd code written in C instead of bolted ontop in a shell scripting language like bash?  I don't know anything about systemd and find it strange that its handled in the source code.  Why is that?

**Comment by zaxebo1** [comment] 2015-11-02 09:37
i was talking from ubuntu packaging/porter point of view.

this question of yours may be better be answered by main developers.

**Comment by mvollmer** [comment] 2015-11-02 10:07
Cockpit interacts with systemd in two very different ways:

- It uses systemd to manage the Cockpit socket and main `cockpit-ws` process, in a straight forward manner.  This is done by the `cockpit.service` and `cockpit.socket` unit files and some bits to deal with socket activation.  If you want to get Cockpit running on a system with a different init than systemd, you need to integrate it into the init mechanism of that system.  This shouldn't be difficult.

- The UI can show systemd services and the systemd journal, and it uses systemd in various other places, like configuring the clock for NTP, starting docker if necessary, and probably other things.  If you want to port Cockpit to another platform that doesn't have those systemd APIs, you need to either remove all those features from Cockpit, or replace them with new code that talks to the platform APIs that are available.  This is a lot of work, but doable.

  See here for the systemd specific UI code: https://github.com/cockpit-project/cockpit/tree/master/pkg/systemd

**Comment by Conzar** [comment] 2015-11-02 10:29
It seems systemd the library is [available](https://launchpad.net/ubuntu/+source/systemd)on Ubuntu 14.04.  So if the library is there, than all that needs to be done is replace how thr cockpit web server is started?  So instead of running systemctl start cockpit, an init.d script would start the web server?  Or am i missing something fundamental in how systemd works?

**Comment by stefwalter** [comment] 2015-11-02 14:00
> 

It seems systemd the library is availableon Ubuntu 14.04. So if the library is there, than all that needs to be done is replace how thr cockpit web server is started? So instead of running systemctl start cockpit, an init.d script would start the web server? Or am i missing something fundamental in how systemd works?

Systemd provides the DBus APIs that Cockpit uses to configure the system. If systemd is present in its appropriate role in the system (as init/service manager) then alternative components to the systemd specific cockpits in Cockpit would need to be developed, and that's not a trivial effort.

Really I'm just repeating what @mvollmer said above :)

**Comment by stefwalter** [comment] 2017-01-10 10:16
The distributions where Cockpit is tested and/or delivered are listed here: 

http://cockpit-project.org/running.html

Over the last few months we've worked on full testing on Debian and Ubuntu. Lets close this issue.

**Closed by stefwalter** 2017-01-10 10:16 UTC
