### ISSUE TITLE
OpenSSH 7.8 new default private key format breaks authentication/credentials in shell and lib

### ISSUE THREAD

**Issue by croissanne** [cockpit-project/cockpit#9948] opened 2018-08-31 12:57 UTC
OpenSSH 7.8 moves away from PEM in favour of their own format. Keys in this new format added in cockpit lack some of the functionality, their passwords can't be changed for instance.

See also #9920.

**Comment by Gundersanne** [comment] 2018-08-31 12:59
The problem is that the PEM formatted keys were able to have `key.name` filled in `pkg/lib/credentials.js` with the path to that key. As a result they can be changed via `ssh-keygen`.

However with the new format the path (and thus `key.name`) is missing with our current parsing. I'm not sure if this information should still be in there or if it's just gone.

**Comment by martinpitt** [comment] 2023-01-03 16:04
Duplicate of #9467 5861

**Closed by martinpitt** 2023-01-03 16:04 UTC
Labels: cockpit-ssh, review-2022-12
