### ISSUE TITLE
conflicting disk I/O information between System and Storage

### ISSUE THREAD

**Issue by cmurf** [cockpit-project/cockpit#2662] opened 2015-08-30 19:01 UTC
All at the same time:

Cockpit Dashboard > System > Disk I/O  =  ~76 MB/s
Cockpit Dashboard > Storage > Reading = ~ 36 MB/s
Cockpit Dashboard > Storage > Writing   = negligible 
iotop and iostat show 38 MB/s reads (total and actual)

So something is wrong about the System > Disk I/O value computation. I also don't understand the meaning of the two tone graphing in Storage > Reading.

Screenshot for System > Disk IO
![screen shot 2015-08-30 at 12 26 42 pm](https://cloud.githubusercontent.com/assets/10091077/9568934/2210af76-4f17-11e5-9542-72751030806d.png)
Screenshot for Storage > Reading
![screen shot 2015-08-30 at 12 23 13 pm](https://cloud.githubusercontent.com/assets/10091077/9568936/259be872-4f17-11e5-8d7d-b076dccb50e3.png)

**Comment by mvollmer** [comment] 2016-01-05 17:34
Is this a duplicate of #3403?

**Closed by mvollmer** 2016-01-05 17:34 UTC
