### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19777] opened 2023-12-24 02:31 UTC
Tests failed on e70b470c1ef028b91484f90e762aa108735621f4, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231224-012909-e70b470c-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2023-12-24 09:45
Duplicate of #19772

**Closed by martinpitt** 2023-12-24 09:45 UTC
Labels: nightly
