### ISSUE TITLE
firewalld: configure custom ports

### ISSUE THREAD

**Issue by Songxuewen** [cockpit-project/cockpit#9327] opened 2018-06-07 07:34 UTC

**Comment by andreasn** [comment] 2018-06-18 16:14
I'm a bit confused by the description.
Did you mean **can't** configure custom ports?

**Comment by Songxuewen** [comment] 2018-06-19 05:15
I hope you can manage the open ports of firewalls, not just open services.

**Comment by andreasn** [comment] 2018-06-19 08:36
There are plans for it, but nobody is hacking on that right now.
Here is a mockup that @garrett made for it:
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/firewall/firewall-dialog-add-service.png)

**Comment by garrett** [comment] 2018-06-19 12:56
It previously wasn't clear by just looking at the mockup out of context from [the firewall design page](https://github.com/cockpit-project/cockpit/wiki/Feature:-Firewall) (oops!), but I added a little bit of text in the above mockup too: After this is implemented, adding a custom ports will transparently create custom network service rules on the fly, so they can be managed like every other network service rule in the firewall.

We'll hopefully add custom ports like this soon.

**Comment by garrett** [comment] 2018-06-19 13:01
BTW: Duplicate of #9048.

**Closed by garrett** 2018-06-19 13:01 UTC
