### ISSUE TITLE
Test: waiting for network interface times out

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2910] opened 2015-10-06 12:40 UTC
On RHEL 7:
![check-networking-testbridge-fail](https://cloud.githubusercontent.com/assets/8711649/10308742/202c8552-6c38-11e5-8f55-fab51423154f.png)

```
./check-networking
Wrote check-networking-testBridge-FAIL.png
Journal database copied to check-networking-testBridge-10.111.112.102-FAIL.journal
..EWarning: Permanently added '10.111.112.102' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBridge (__main__.TestNetworking)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-networking", line 228, in testBridge
    self.wait_for_iface(iface1)
  File "./check-networking", line 52, in wait_for_iface
    self.browser.wait_present(sel)
  File "/home/hubbot/hubbot/f3cbe0fe9ce25281f956a5bccefa03fff9279831_r7_x86-64/test/testlib.py", line 223, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/f3cbe0fe9ce25281f956a5bccefa03fff9279831_r7_x86-64/test/testlib.py", line 217, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/f3cbe0fe9ce25281f956a5bccefa03fff9279831_r7_x86-64/test/testlib.py", line 667, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/f3cbe0fe9ce25281f956a5bccefa03fff9279831_r7_x86-64/test/testlib.py", line 630, in run
    raise Error("timeout")
Error: timeout

----------------------------------------------------------------------
Ran 3 tests in 191.846s

FAILED (errors=1)
```

**Comment by stefwalter** [comment] 2015-10-16 10:00
@mvollmer Do you think this is now fixed?

**Comment by mvollmer** [comment] 2015-10-16 10:15
> Do you think this is now fixed?

Yes, hopefully.  This is a duplicate of #2916, as far as I can tell.

**Closed by mvollmer** 2015-10-16 10:15 UTC
