### ISSUE TITLE
Virtual machine not showing of virtualbox

### ISSUE THREAD

**Issue by jainnitesh** [cockpit-project/cockpit#11711] opened 2019-04-30 10:51 UTC
I installed the cockpit-machines package on the host where we are running virtual box but this is not detecting all the virtual machines.

If you will see the attached screenshot virtual machine is listed there but when clicking on the virtual machine this is saying "No VM is running or defined on this host"

**Comment by Antique** [comment] 2019-05-02 08:41
Hi, I don't see any attached screenshot here on github interface.

Anyway cockpit-machines currently supports only QEMU driver from libvirt.  Eventually we can add support for other hypervisors that libvirt knows.

**Comment by jainnitesh** [comment] 2019-05-02 08:44
in screenshot, it was saying no virtual machine running.

i am using VirtualBox

**Comment by KKoukiou** [comment] 2019-05-06 08:00
@jainnitesh as @Antique mentioned for the time being we only support the QEMU driver in cockpit-machines. 
There is not any plan yet to support other drivers except is someone is interested to implement this. The VirtualBox VMs can be manipulated with [vbox](https://libvirt.org/drvvbox.html) libvirt APIs.

So I am closing this issue since this is not a bug. If you 're interested to implement this please step by the #cockpit channel on freenode and we can help you get started.
Or if you really need it but you can't implemented it, please create an issue with request to add support for vbox driver.

**Closed by KKoukiou** 2019-05-06 08:00 UTC

**Comment by maravento** [comment] 2022-12-02 13:36
We have written a post about cockpit. Great program. Congratulations. We're just sorry it doesn't have vbox support. https://www.maravento.com/2022/11/cockpit.html

**Comment by kartikbh6614** [comment] 2023-02-28 18:32
I want to work on this project. Can you assist me how to takeover it

**Comment by KKoukiou** [comment] 2023-03-01 08:07
@kartikbh6614 please make contact on IRC https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#contact (nickname kkoukiou). You should start with something smaller to get your self familiarized.

**Comment by mrbazzan** [comment] 2023-03-23 14:56
Hello @KKoukiou 
I'm a GSoC applicant interested in this project.

@kartikbh6614 
Are you actively interested in this project? I would like to pick it up if you aren't.

**Comment by KKoukiou** [comment] 2023-03-23 15:02
> Hello @KKoukiou I'm a GSoC applicant interested in this project.
> 
> @kartikbh6614 Are you actively interested in this project? I would like to pick it up if you aren't.

@mrbazzan nice to hear, @kartikbh6614 never contacted. Check https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#how-to-start-contributing on how to get started.

**Comment by mrbazzan** [comment] 2023-03-23 15:41
Okay, Thanks.

Do I have to reach out on IRC? Or should I just continue the "setting up process" and reach out if I have any issues?

I have good knowledge of Python but my Javascript is not as good(still working on it). Will that hinder me or I can always learn while attempting problems?

**Comment by OkoloJohnbosco** [comment] 2023-03-24 10:19
Hello @KKoukiou
I'm a GSoC applicant interested in this project 

I have good knowledge of Javascript and React but my Python is not as good. I hope that won't be a problem as I am ready to learn as I go on.

**Comment by gkumarihawk** [comment] 2023-03-27 19:52
Hello @KKoukiou. I am a GSoC applicant and I am interested in this project.

**Comment by JamesAlaric** [comment] 2023-04-04 17:11
Hi I can i work on this project as a gsoc contributor? Plz
