### ISSUE TITLE
Add option to prevent root from login

### ISSUE THREAD

**Issue by liquidat** [cockpit-project/cockpit#4652] opened 2016-06-30 09:28 UTC
It is a common practice to not allow service logins from non-personalized accounts like `root` - see for example also #1790 in regards to sshd.

Please add a configuration option or similar to exclude root or even other default accounts from login.

**Comment by hogarthj** [comment] 2016-08-02 11:14
Note that you can provide for some of this now ...

In my /etc/pam.d/cockpit I have this as the first line:
auth       requisite    pam_succeed_if.so uid >= 1000

In the logs attempts to log in as root result as:
cockpit-session[12187]: pam_succeed_if(cockpit:auth): requirement "uid >= 1000" not met by user "root"

**Comment by stefwalter** [comment] 2016-08-04 12:13
I think this is a duplicate of https://github.com/cockpit-project/cockpit/issues/1790

**Closed** 2016-08-04 12:13 UTC
Labels: enhancement

**Comment by Oaklight** [comment] 2023-12-02 18:57
You can also edit the `/etc/pam.d/cockpit` to include this following line:
```
# List of users to deny access to Cockpit, by default root is included.
auth       required     pam_listfile.so item=user sense=deny file=/etc/cockpit/disallowed-users onerr>
```
and add a file `/etc/cockpit/disallowed-users` with `root` listed in it

**Comment by martinpitt** [comment] 2023-12-02 20:08
For the record, this was fixed a year ago in https://cockpit-project.org/blog/cockpit-280.html -- for new installations, root isn't allowed to login by default.
