### ISSUE TITLE
system: CPU usage chart doesn't show

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#13290] opened 2019-12-13 16:56 UTC
Cockpit version: 209
OS: Fedora Server 31
Page: /system/graphs#/cpu

The CPU usage chart doesn't show at all.

![image](https://user-images.githubusercontent.com/1463740/70817411-48bcbe00-1db0-11ea-88fc-3e57ee84f7d5.png)

Fixing this specific case can be as easy as removing this line:

https://github.com/cockpit-project/cockpit/blob/83bd249245c2c33824899372b95a7e2d50149e28/pkg/systemd/graphs.less#L137

**Comment by garrett** [comment] 2020-01-13 12:56
That line of CSS was added to _avoid_ this bug, not to cause it.

The Flot-based graphs are inherently wonky. I sometimes ran into this issue with the detailed graphs _before_ the graphs were shuffled around.

We should try to move to the PF4 graphs as soon as we can.

**Comment by maximal1st** [comment] 2020-01-14 15:15
![CockpitErrorAnonymized](https://user-images.githubusercontent.com/10962085/72356039-399f9780-36f1-11ea-8d74-e20471551712.png)
Even the layout is broken

**Comment by martinpitt** [comment] 2020-01-19 20:14
At least for me this is fixed with PR #13397.

**Comment by garrett** [comment] 2020-01-20 09:00
@maximal1st's issue is a different one. As the graph pages were moved around to new files, for some reason, most of the JS & CSS weren't being included. The issue for the missing JS & CSS is @ https://github.com/cockpit-project/cockpit/issues/13380.

**Comment by martinpitt** [comment] 2020-01-20 09:00
Sorry, I still get the oops on the CPU page. #13397 fixes the graphs overview page for me (i. e. the four graphs). I take a look at this now.

**Comment by garrett** [comment] 2020-01-20 09:02
BTW, for clarification: This issue is for the separate detailed CPU graph, not the overview graphs. 

(You can see easily spot the difference whether or not the breadcrumbs are displayed properly.)

**Comment by martinpitt** [comment] 2020-01-20 09:05
I get the same crash on my system with Firefox:
```
Error: Invalid dimensions for plot, width = 647, height = 0 36 graphs.js:230:10
    resize http://localhost:9090/cockpit/@localhost/system/graphs.js:230
    Canvas http://localhost:9090/cockpit/@localhost/system/graphs.js:209
    setupCanvases http://localhost:9090/cockpit/@localhost/system/graphs.js:1408
    Plot http://localhost:9090/cockpit/@localhost/system/graphs.js:802
    plot http://localhost:9090/cockpit/@localhost/system/graphs.js:3241
    maybe_start http://localhost:9090/cockpit/@localhost/system/graphs.js:23046
```

I confirm that dropping the `100% !important` hack fixes things perfectly. @garrett, @KKoukiou, how can the original bug be reproduced that triggered introducing this hack? This got introduced in commit 83bd249245c2 without explanation or bug reference.

**Comment by garrett** [comment] 2020-01-20 09:10
The explanation is that the CPU graph would be sized inappropriately, as it would be too small. So this was supposed to stretch it to the available width. It worked locally at the time of that commit. I'm not sure why Flot is being fussy now.

@martinpitt: Perhaps there's a race condition. It would explain why it would show during development but isn't showing for @leomoty and you now?

In the graphs overview, Flot would render the charts too early, before the page was done loading, and then they'd be sized incorrectly. A browser resize fixed that there. And then I worked around it with some CSS to size the graphs differently anyway.

Here, it could be causing the issue where it works sometimes for some people, and not for others.

The suggested fix would be to drop that line and have Flot load at the appropriate time (after the page is rendered) to size the graph to the available space.

**Comment by garrett** [comment] 2020-01-20 09:11
Alternatively, we could drop the height and set a min-height instead. This might also work, perhaps even regardless of when Flot renders.

**Comment by martinpitt** [comment] 2020-01-20 09:17
I sent PR #13420 as a strawman. If that's not the correct fix, let's just close it.

**Comment by garrett** [comment] 2020-01-20 13:13
Oh. For some reason, the container is set to `display: block` with inline CSS, instead of using `grid`, as specified in the CSS. Also, the grid template sizing is not correct. All of this together probably causes the issue — if the grid container, a `div`, is set to block, then a child div with a `display: block`, but `height: 100%` would effectively be height of 0px, as it wouldn't have content yet to force it taller and height: 100% on a contentless block will not do anything in this case.

Some things have changed since I last looked at the HTML+CSS.

(I have some ideas of how to fix this, but it's really difficult working on this on the train at the moment, so I'll probably have a fix "soon" — either later today or tomorrow.)

**Closed** 2020-01-21 20:24 UTC
