### ISSUE TITLE
Cannot log in to cockpit after following a link on a website

### ISSUE THREAD

**Issue by erentar** [cockpit-project/cockpit#19863] opened 2024-01-20 09:42 UTC
### Explain what happens

1. create index.html with contents
```
cockpit: <a href="http://10.0.0.1:9090" rel="noreferrer noopener" class="uri">http://10.0.0.1:9090</a>
```
2. host this on some ngnix server on 10.0.0.2
3. log in with the correct password, page refreshes, and javascript console shows "GET 10.0.0.1:9090/cockpit/login HTTP 401 Authentication failed"

this does not happen if i copy and paste the link to the address bar

notably clicking on the link adds some headers such as Sec-Fetch-Mode: cors and Sec-Fetch-Site: same-origin which are not present when copy-pasting the link.

### Version of Cockpit

307

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Fedora

### Server operating system version

fedora server 37

### What browsers are you using?

Firefox

### System log

```shell
the logs dont show anything out of the ordinary
```

**Comment by jelly** [comment] 2024-01-22 11:34
This sounds like a duplicate of https://github.com/cockpit-project/cockpit/issues/18260

**Closed by jelly** 2024-01-22 11:34 UTC
Labels: bug
