### ISSUE TITLE
Slash and hash links

### ISSUE THREAD

**Issue by Neustradamus** [cockpit-project/cockpit#13171] opened 2019-11-19 15:07 UTC
1/ Slash problems, for examples:
- https://IP:9090/example/#/example
- https://IP:9090/example//#/example
- https://IP:9090/example///#/example
- https://IP:9090/example////#/example
- https://IP:9090/example///////#/example/example
- https://IP:9090/example//////#/example/example
- https://IP:9090/example////////#/example/example
- https://IP:9090/example/////#/example/example
- ...

In the same time, I think it is possible to have only:
- https://IP:9090/example#example
or
- https://IP:9090/example/#example
or
- https://IP:9090/example/example

2/ There are some links:
- https://IP:9090/cockpit/HASH/example/index.html#/
- https://IP:9090/cockpit/HASH/example/index.html#/example
- ...
Can you change it to https://IP:9090/example...

Linked to:
- https://github.com/NethServer/dev/issues/5921

**Comment by marusak** [comment] 2019-11-21 08:26
> 1/ Slash problems, for examples: ...

I think that all of these addresses are valid, aren't they? I agree that they may seem weird and probably we could just strip sequential slashes. Can you provide any specific example how to get to such address? (Like 1. select page foo 2. click on bar...) Also, does this cause any problem for you or is it just "nice to have"?

> 2/ There are some links: ...

Again, can you please provide specific example of such address and how to get to it? (feel free to change some values like ip addresses). First thing that came to my mind was something like `https://localhost:9090/@127.0.0.3/system` which is connecting to different server and which is correct.

> Linked to: https://github.com/example/dev/issues/5921

This URL does not exist.

**Comment by Neustradamus** [comment] 2019-11-21 21:00
@marusak, sorry, I have added the good link.

**Comment by gsanchietti** [comment] 2019-11-22 08:11
Thank you for you're time @marusak, the problem is related on how NethServer uses the `/usr/share/cockpit/nethserver/manifest.json` to add extra links to the left menu.

Manifest example:
```json
{
  "version": 0,
  "name": "nethserver",

  "menu": {
    "index": {
      "label": "System",
      "order": 10
    },
    "#/applications": {
      "label": "Applications",
      "order": 20
    },
    "/#/software-center": {
      "label": "Software Center",
      "order": 30
    },
    "//#/subscription": {
      "label": "Subscription",
      "order": 40
    },
    "///#/terminal": {
      "label": "Terminal",
      "order": 50
    }
  },

  "tools": {
    "////#/applications/nethserver-firewall-base" : {"label": "Firewall"}
  },

  "content-security-policy": "default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; img-src 'self' data:"
}
```

And this is how the menu looks like:
![Screenshot from 2019-11-22 09-09-57](https://user-images.githubusercontent.com/804596/69408802-f126b780-0d07-11ea-9892-d8d0b2d3617d.png)

I think that we are stretching a bit a Cockpit internal.
The issue is already tracked here https://github.com/cockpit-project/cockpit/issues/10304

I think you can close this one.

**Closed** 2019-11-22 08:57 UTC
Labels: question

**Comment by Neustradamus** [comment] 2019-11-22 17:49
@gsanchietti: Thanks for your reply!
@marusak: It is possible to look for this problem?

**Comment by Neustradamus** [comment] 2019-11-22 18:06
@gsanchietti, @marusak: Warning, this ticket has 2 parts!
The second has been missing...
Can you look this ticket for HASH and random address change?
- https://IP:9090/cockpit/HASH/example/index.html#/
- https://IP:9090/cockpit/HASH/example/index.html#/example

-> other links are only on this base: https://IP:9090/example/#/example

**Comment by Neustradamus** [comment] 2019-11-24 04:22
@gsanchietti, @marusak: I have added the third possibility!
- https://IP:9090/cockpit/@localhost/example/index.html#/

Can you look?

**Comment by marusak** [comment] 2019-11-24 09:03
>  I have added the third possibility!

Please read my first reply, where I mentioned this use case. This is definitely valid use case.

> Can you look this ticket for HASH and random address change?

Again, this seems like a valid use case. I cannot think if Cockpit uses it (please provide how to get to these cases), if not than this needs to be discussed with NethServer.

Also for both of these cases - why does it bother you that there is hash or remote server address in URL? Those are valid addresses and it is needed to distinguish between different places in Cockpit.

**Comment by Neustradamus** [comment] 2019-11-26 04:15
@gsanchietti, @marusak: I think it is possible to have only links without an HASH or cockpit...

On the same page, we have:
- https://IP:9090/nethserver////////////#/applications/nethserver-xxx
- https://IP:9090/nethserver#/applications/nethserver-xxx
- https://IP:9090/cockpit/@localhost/nethserver-xxx/index.html#/
- https://IP:9090/cockpit/$9ld30z0oze9fhbd4705f4af8a441df4901ea6b4b472c61f8eeaf1570zld4867i/nethserver/index.html#/xxx-xxx

Why there is cockpit here?
Why there is HASH here?

I do not speak about @localhost of course.

**Comment by Neustradamus** [comment] 2019-12-06 05:45
@gsanchietti, @marusak: Have you look my last message?
If you do not understand, tell me.

Example for the same result:
- https://IP:9090/cockpit/$9ld30z0oze9fhbd4705f4af8a441df4901ea6b4b472c61f8eeaf1570zld4867i/nethserver/index.html#/xxx
vs
- https://IP:9090/nethserver#/xxx

How to have the first link like the second (without hash and without a change of the link)?

**Comment by marusak** [comment] 2019-12-06 09:24
These are nethserver use cases. I really don't know why it is happening.

**Comment by Neustradamus** [comment] 2019-12-08 14:36
@marusak: In this case, I have done a ticket here: https://community.nethserver.org/t/slash-cockpit-hash-and-cockpit-localhost-links/14156.

Thanks a lot for your replies!
