### ISSUE TITLE
machines: storage pool isn't reflected on 

### ISSUE THREAD

**Issue by oleksandrborniak** [cockpit-project/cockpit#11983] opened 2019-06-03 07:52 UTC
Cockpit version: 195
OS: Fedora server 30
Page: Virtual machines

I have one configured storage pool, named "qemu".
Target Path: /var/lib/machines/qemu
Persistent: yes
Autostart: yes
Type: dir

This pool is not reflected on the Create New Virtual Machine step. 
Do you have some limitations for used file-system  ? I am using btrfs .

```
[root@fc tools]# virsh pool-list
 Name   State    Autostart
----------------------------
 qemu   active   yes

[root@fc tools]#
```

```
[root@fc tools]# rpm -qa | grep libvirt-dbus
libvirt-dbus-1.3.0-2.fc30.x86_64
[root@fc tools]#
```

```
[root@fc tools]# cat /proc/mounts  | grep mach
/dev/mapper/fedora_fc-containers /var/lib/machines btrfs rw,relatime,space_cache,subvolid=5,subvol=/ 0 0
[root@fc tools]#
```

<img width="603" alt="Screen Shot 2019-06-03 at 10 33 31" src="https://user-images.githubusercontent.com/49722408/58785174-ad22e780-85ed-11e9-9d06-ddd4519abb49.png">

**Comment by skobyda** [comment] 2019-06-03 15:09
Hello, @oleksandrborniak 

Do you have any storage volumes defined for storage pool "qemu"? If no, I'm afraid there is misinterpretation of this functionality.

If storage pool doesn't have any volumes, it is ignored by Create New Virtual Machine dialog. 
If storage pool has volumes, you can choose that storage pool and then choose from it's storage volumes. Chosen storage volume will be used as destination storage for the new virtual machine.

As you can see here, my storage pool "default" has already existing volumes, which I can then choose as destination storage for my new virtual machine:
![Screenshot from 2019-06-03 17-05-46](https://user-images.githubusercontent.com/42733240/58812322-e1b09680-8621-11e9-8b72-764c889aa6a8.png)

**Comment by oleksandrborniak** [comment] 2019-06-05 07:37
Yep, thank you for clarification.  It is a little bit weird, that I can't create new volume automatically and just define storage pool, if I have more then one. 
Also it looks like not possible to create a new volume on specified storage pool using UI. 
Am I right ?

**Comment by oleksandrborniak** [comment] 2019-06-05 12:27
Could you please also clarify, what pool types are supported at the moment  ? 
I've tried to use LVM storage pool type, but volumes are not reflected in the UI in such case. 

```
[root@fc ~]# virsh pool-define-as guest_images_lvm logical - - /dev/sdb libvirt_lvm /dev/libvirt_lvm
Pool guest_images_lvm defined

[root@fc ~]# parted /dev/sdb p
Model: VMware Virtual disk (scsi)
Disk /dev/sdb: 215GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start  End  Size  File system  Name  Flags

[root@fc ~]# virsh pool-build guest_images_lvm --overwrite
Pool guest_images_lvm built

[root@fc ~]# pvs
  PV         VG          Fmt  Attr PSize    PFree
  /dev/sda2  fedora_fc   lvm2 a--  <199.00g  176.10g
  /dev/sdb   libvirt_lvm lvm2 a--  <200.00g <200.00g
[root@fc ~]# virsh pool-start guest_images_lvm
Pool guest_images_lvm started

[root@fc ~]#
```

```
[root@fc ~]# virsh pool-dumpxml guest_images_lvm
<pool type='logical'>
  <name>guest_images_lvm</name>
  <uuid>c5f3ead2-dc2a-46ab-a2f1-1371914789f8</uuid>
  <capacity unit='bytes'>214744170496</capacity>
  <allocation unit='bytes'>26843545600</allocation>
  <available unit='bytes'>187900624896</available>
  <source>
    <device path='/dev/sdb'/>
    <name>libvirt_lvm</name>
    <format type='lvm2'/>
  </source>
  <target>
    <path>/dev/libvirt_lvm</path>
  </target>
</pool>

[root@fc ~]# virsh vol-list guest_images_lvm --details
 Name       Path                        Type    Capacity    Allocation
------------------------------------------------------------------------
 fedora29   /dev/libvirt_lvm/fedora29   block   15.00 GiB   15.00 GiB
 testqcow   /dev/libvirt_lvm/testqcow   block   10.00 GiB   10.00 GiB

[root@fc ~]#
```

**Comment by skobyda** [comment] 2019-06-11 15:54
I believe it's caused by bug which will be fixed by this PR: https://github.com/cockpit-project/cockpit/pull/12044

Let me know if that fixed it.

**Closed** 2019-06-12 05:28 UTC

**Comment by oleksandrborniak** [comment] 2019-07-31 11:56
@KKoukiou  @martinpitt  I've re-checked this behaviour on  the "cockpit-199-1.fc30.x86_64" and I can see all storage volumes , BUT they appears only after "machines" page is reloaded or cockpit service is restarted. 
Example: 
```
[root@fc cockpit]# virsh vol-create-as guest_images_lvm newvirtdisk 50G
Vol newvirtdisk created

[root@fc cockpit]# virsh vol-create-as guest_images_lvm manualvol 50G
Vol manualvol created

[root@fc cockpit]# virsh vol-list guest_images_lvm --details
 Name          Path                           Type    Capacity    Allocation
------------------------------------------------------------------------------
 fedora29      /dev/libvirt_lvm/fedora29      block   15.00 GiB   15.00 GiB
 manualvol     /dev/libvirt_lvm/manualvol     block   50.00 GiB   50.00 GiB
 newvirtdisk   /dev/libvirt_lvm/newvirtdisk   block   50.00 GiB   50.00 GiB
```
I've added two additional storage volumes - "manualvol" && "newvirtdisk" , but UI shows me only old record. 
<img width="731" alt="Screen Shot 2019-07-31 at 14 47 14" src="https://user-images.githubusercontent.com/49722408/62209682-edf76c80-b3a2-11e9-9c53-cd4aa4f04175.png">

**Result after "machines" page is reloaded or cockpit service is restarted:** 

<img width="708" alt="Screen Shot 2019-07-31 at 14 49 01" src="https://user-images.githubusercontent.com/49722408/62209745-1f703800-b3a3-11e9-8a21-34ed84c63c39.png">
