### ISSUE TITLE
[view hardware details] do not show anything

### ISSUE THREAD

**Issue by PANDATEEN** [cockpit-project/cockpit#16257] opened 2021-08-25 06:32 UTC
**Cockpit version: cockpit-238.2-1.el8.x86_64
OS:CentOS Linux release 8.4.2105
Page: view hardware details**

the system info block works normal,but when I click the [view hardware details],the content block becomes empty and shows nothing.
I can not get any useful infomation from the system log, bug I can get the error throwed by my chrome console.
I tried the dnf reinstall cockpit*.but did not work.
the broad is MSI B450M and the cpu is ryzen5 3600,memory is 24g.

ok,it happens on one of my centos server,but I can not reproduce it on the other of my centos server.the two server are totally the same version and system.it is hard for me to figure it out.

**journalctl -u cockpit:**
```
-- Logs begin at Wed 2021-08-25 12:50:40 CST, end at Wed 2021-08-25 14:28:03 CST. --
8月 25 12:51:06 gamer systemd[1]: Starting Cockpit Web Service...
8月 25 12:51:06 gamer systemd[1]: Started Cockpit Web Service.
8月 25 12:51:06 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:51:06 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:51:06 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:51:06 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:51:06 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:51:06 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:51:06 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:51:11 gamer cockpit-tls[2620]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:54:05 gamer systemd[1]: Stopping Cockpit Web Service...
8月 25 12:54:05 gamer systemd[1]: cockpit.service: Succeeded.
8月 25 12:54:05 gamer systemd[1]: Stopped Cockpit Web Service.
8月 25 12:54:05 gamer systemd[1]: Starting Cockpit Web Service...
8月 25 12:54:05 gamer systemd[1]: Started Cockpit Web Service.
8月 25 12:54:08 gamer cockpit-tls[6079]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:54:08 gamer cockpit-tls[6079]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:54:14 gamer cockpit-tls[6079]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:54:14 gamer cockpit-tls[6079]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:54:14 gamer cockpit-tls[6079]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:54:14 gamer cockpit-tls[6079]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:38 gamer systemd[1]: Stopping Cockpit Web Service...
8月 25 12:59:38 gamer systemd[1]: cockpit.service: Succeeded.
8月 25 12:59:38 gamer systemd[1]: Stopped Cockpit Web Service.
8月 25 12:59:39 gamer systemd[1]: Starting Cockpit Web Service...
8月 25 12:59:39 gamer systemd[1]: Started Cockpit Web Service.
8月 25 12:59:42 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:42 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:43 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:43 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:47 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:47 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:47 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 12:59:47 gamer cockpit-tls[10942]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:46 gamer systemd[1]: Stopping Cockpit Web Service...
8月 25 13:13:46 gamer systemd[1]: cockpit.service: Succeeded.
8月 25 13:13:46 gamer systemd[1]: Stopped Cockpit Web Service.
8月 25 13:13:46 gamer systemd[1]: Starting Cockpit Web Service...
8月 25 13:13:46 gamer systemd[1]: Started Cockpit Web Service.
8月 25 13:13:49 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:49 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:49 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:49 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:55 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:55 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:55 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:13:55 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:07 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:07 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:45 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:45 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:45 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:45 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:45 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:14:45 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 13:54:36 gamer cockpit-tls[13839]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
8月 25 14:04:03 gamer systemd[1]: cockpit.service: Succeeded.
```
by the way,the tls alert is because I open the website from the localhost url,even if I open it in the correct website url with https,the problem is still here.
**chrome console:**
```
TypeError: Cannot read property 'props' of undefined
    at hwinfo.js:307
    at Array.map (<anonymous>)
    at hwinfo.js:307
    at Array.map (<anonymous>)
    at qt (hwinfo.js:307)
    at $i (hwinfo.js:294)
    at ho (hwinfo.js:294)
    at dl (hwinfo.js:294)
    at ol (hwinfo.js:294)
    at Zo (hwinfo.js:294)
Zs @ hwinfo.js:294
Uncaught (in promise) TypeError: Cannot read property 'props' of undefined
    at hwinfo.js:307
    at Array.map (<anonymous>)
    at hwinfo.js:307
    at Array.map (<anonymous>)
    at qt (hwinfo.js:307)
    at $i (hwinfo.js:294)
    at ho (hwinfo.js:294)
    at dl (hwinfo.js:294)
    at ol (hwinfo.js:294)
    at Zo (hwinfo.js:294)
```

**Comment by marusak** [comment] 2021-08-25 06:40
I believe this is duplicate of https://github.com/cockpit-project/cockpit/issues/15631 which was fixed in cockpit-system-246

Can you please try to update and check if it is fixed?  You can use this copr if you don't have newer version available: https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/

**Comment by martinpitt** [comment] 2021-09-02 12:15
Indeed, very plausible. Closing as duplicate of #15631, it's very unlikely to be something else. If it still happens with a current version, I'm happy to reopen. Thanks!

**Closed by martinpitt** 2021-09-02 12:15 UTC
Labels: question
