### ISSUE TITLE
Spaces of /etc/motd from the start of file aren't printed on web interface

### ISSUE THREAD

**Issue by viniciusferrao** [cockpit-project/cockpit#11680] opened 2019-04-26 17:17 UTC
Cockpit version: 176
OS: CentOS 7.5.1804
Page: System

The motd box eats spaces on /etc/motd if the file start with spaces.

For instance, if we have an ASCII Art on the /etc/motd file it get's printed wrong on the first line if it starts with spaces.

Steps to reproduce

1. Create a /etc/motd file with spaces at start
2. See it on system pane
3. Does not get the spaces printed on the box.

![motdOnTerminal](https://user-images.githubusercontent.com/2031761/56824850-1022a100-682e-11e9-873e-cd212e5361c6.png)
![motdOnCockpit](https://user-images.githubusercontent.com/2031761/56824852-1022a100-682e-11e9-9e31-b88e6ac33338.png)

**Comment by jeremyvisser** [comment] 2019-05-03 09:49
Probably caused by the use of `trim()` here:

https://github.com/cockpit-project/cockpit/blob/dd32f908a0c361cb8d2ecccb9ec958ced9fe88f8/pkg/systemd/host.js#L237-L239

**Comment by martinpitt** [comment] 2019-10-21 08:50
Fixed in PR #13021

**Closed** 2019-10-21 13:03 UTC
Labels: good-first-issue
