### ISSUE TITLE
The diagnostic reports page fails to download large sos reports

### ISSUE THREAD

**Issue by jeepingben** [cockpit-project/cockpit#8589] opened 2018-02-08 21:53 UTC
If the sos report generated in the Diagnostic Reports page is bigger than 16MB (the default max size in src/bridge/cockpitfsread.c), the download fails. Increasing the max size for sos reports appears to be a matter of including it in the request from sosreports/index.js.

When this error happens, the error returned from the back end has no details, it just says internal server error.  Getting a more specific error from the back end looks like it could be harder.
![screen shot 2018-02-08 at 4 44 28 pm](https://user-images.githubusercontent.com/8668066/36000324-8bff7f4a-0cf0-11e8-8848-3f61cc3e0e7a.png)

The easiest way to reproduce this is probably to generate a sos report, then before hitting download, ssh into the system extend the file containing the report.  Once the file has been extended, click download and you should see the error.

**Comment by stefwalter** [comment] 2018-02-09 13:22
@mvollmer Do we just need to set the max file size option in the channel that downloads the file?

In addition there's definitely another bug here. A file that's too big should have an intelligent error message, rather than the general "Internal Server Error".

@jeepingben You can almost certainly see more failure details in the system journal, but nevertheless this is still a bug on both counts.

**Comment by martinpitt** [comment] 2018-02-16 08:12
#8620 is a first band-aid. But this should be fixed more properly, with a legible error message and a test case; so I'm keeping this open.

**Comment by deryni** [comment] 2018-02-23 17:34
As a first pass of a real fix for this I assume we would want to at least surface the "File too big" error in the dialog.

But what about the next step? What do we do with the file? How do we suggest the user get the file at that point? My initial thought was just to show the path to the file (possibly in a "sample" scp command or similar) but I'm not sure that's actually a good idea.

What other options are available to cockpit at that point?

**Comment by martinpitt** [comment] 2019-01-17 16:44
We do giant downloads in cockpit-composer now, after @stefwalter 's throttling protocol fixes. So we should b able to teach the sosreport page about unlimited downloads now, too.

**Comment by marusak** [comment] 2020-02-14 06:34
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.

**Closed by marusak** 2020-02-14 06:34 UTC
Labels: review-2019-10
