### ISSUE TITLE
metrics: History: Tooltip isn't recompiled when hovering a different part of the graph

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16491] opened 2021-10-19 11:59 UTC
Tooltip of the graphs are tied to segments (the minute block), not based on the position inside of the SVG (so if the SVG goes from empty to max, hovering empty and max in the same minute returns the same results).

While it might be computed based on the SVG on entry, it needs to be recomputed on mouse movement. This can (optionally?) have a debounce for movement so it's not recomputed per pixel, but it should be accurate when the mouse stops moving. 

(UX participants were confused when moving the mouse within the same minute and the stats in the hover didn't change.)

**Comment by martinpitt** [comment] 2021-10-19 12:11
As I mentioned, I cannot reproduce this. Moving tooltip works fine for me, I get 5s resolution. This mostly works for "expanded"  minutes of course, but it still works in principle for the collapsed ones as well, you just need to point really precisely.

**Comment by marusak** [comment] 2022-01-04 10:59
@garrett if none can reproduce this I am afraid we have nothing we can do about this. Do you agree with closing this or do you have some ideas what could be the issue here?

**Comment by garrett** [comment] 2022-01-04 11:04
Multiple people had this problem in the usability study. It's a bug that impacts usability and it should be fixed. 

I guess we can look at the videos again to see if there's some hint as to what has happened. The person in the test could have been doing something than what you are doing.

**Comment by marusak** [comment] 2022-01-10 07:11
> I guess we can look at the videos again to see if there's some hint as to what has happened. The person in the test could have been doing something than what you are doing.

Do we have those videos then?

**Comment by garrett** [comment] 2022-01-24 15:45
> Do we have those videos then?

Yes. There was a shared folder on Drive. I can't find it now though... I see it was renamed / moved... but I cannot find it. Perhaps @andreasn knows where the videos of the Cockpit Metrics Page usability are located and can give you a link?

(We can't share the videos with a wider audience, as they have personally identifying information, including faces, voices, names, and possibly some personal information can be seen on their computers as well. And we also assured them we wouldn't be sharing it with the public. But we can share them internally with each other for usability-related purposes.)

**Comment by garrett** [comment] 2022-01-24 16:21
@marusak: I believe I might've shared the videos with you on your RH account on Google Drive. Hopefully it works. (It looks like it should.)

**Comment by garrett** [comment] 2022-01-24 16:32
I can't download the videos to scrub through them to find the correct video and location in the video, so all I can say is that it's somewhere in the videos. Google's UI is not very good. Apologies.

I think it's at the last third of one or more of the videos... probably the one that's from 2021-10-11? But it might be somewhere else or in another. Again; it's impossible to effectively find things in these videos with Google's crappy, laggy UI.

**Comment by andreasn** [comment] 2022-01-25 12:34
To tighten how we respect private identifiable information of our participants, the research team have been moving all videos to a private space, but the anonymized transcripts and all other data is available. I can extract the segments with the tooltips problems for you. I'll contact you in private, @garrett so we can figure out who it was together, without accidentally leaking their private identifiable information.

**Comment by garrett** [comment] 2022-01-25 13:16
> I can extract the segments with the tooltips problems for you. I'll contact you in private, @garrett so we can figure out who it was together, without accidentally leaking their private identifiable information.

OK, awesome! Thanks!

**Comment by marusak** [comment] 2022-12-15 07:43
@andreasn and @garrett any update on this? None was able to reproduce this and without any videos we cannot proceed.

**Comment by garrett** [comment] 2022-12-15 16:07
It's still a bug (as we haven't fixed it or touched that part of the code since, AFAICT) and it still was a problem that multiple people ran into it.

I remember I had some kind of access to the videos at some point, but they were in a web thing that only I had access to and they weren't scrubable or shareable (even in part), so they were almost completely useless as reference. We'd need access to the raw videos from @andreasn in order for them to be useful (and then they could be scrubbed to find the right point where the bug happens, then trimmed, and shared _internally_ to our team members only, for privacy reasons).

**Comment by marusak** [comment] 2023-03-17 07:26
I talked with @garrett and we agreed we can close this. None was able to reproduce, nor we could not find anything in code. As soon as we have reproducer let's investigate this bur right now this is no-op for us.

**Closed by marusak** 2023-03-17 07:26 UTC
Labels: question, UXresearch-finding, page:metrics
