### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19831] opened 2024-01-10 02:20 UTC
Tests failed on 992c989e3b2e9cc8123aac58d1c0298e883e95b9, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240110-012825-992c989e-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2024-01-10 06:38
Duplicate of #19765

**Closed by martinpitt** 2024-01-10 06:38 UTC
Labels: nightly
