### ISSUE TITLE
Tests failed on c7d327f89f01ae54bd127020e7665dccea00aff3

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21310] opened 2024-11-23 02:30 UTC
The job `fedora-40/updates-testing` failed on commit c7d327f89f01ae54bd127020e7665dccea00aff3.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c7d327f8-20241123-013202-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-24 09:54
Duplicate of #21312

**Closed by martinpitt** 2024-11-24 09:54 UTC
Labels: nightly
