### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20023] opened 2024-02-14 02:42 UTC
Tests failed on 55cab378fdcae701647c00cd6dde965d0276ccb2, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240214-012424-55cab378-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment] 2024-02-14 09:26
Duplicate of #20022

**Closed by martinpitt** 2024-02-14 09:26 UTC
Labels: nightly
