### ISSUE TITLE
Way to delete Systemd timers

### ISSUE THREAD

**Issue by kaushalyap** [cockpit-project/cockpit#16873] opened 2022-01-25 01:39 UTC
Currently there is no way delete to created Systemd timers only to create, stop  and etc. Users have to manually stop and delete them. So please provide a way to delete systemd timers through the UI.

**Comment by marusak** [comment] 2022-01-26 07:04
Duplicate of https://github.com/cockpit-project/cockpit/issues/9467

**Closed by marusak** 2022-01-26 07:04 UTC
Labels: enhancement
