### ISSUE TITLE
Image refresh for openshift

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#6504] opened 2017-05-11 18:56 UTC
Image creation for openshift in process on cockpit-tests-rpqhf.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-openshift-2017-05-11/

**Comment by cockpituous** [comment] 2017-05-11 19:03
Image creation aborted

**Comment by stefwalter** [comment] 2017-05-18 07:41
Duplicate of #6334

**Closed by stefwalter** 2017-05-18 07:41 UTC
Labels: bot
