### ISSUE TITLE
Username/Password are behind forms

### ISSUE THREAD

**Issue by Neustradamus** [cockpit-project/cockpit#13172] opened 2019-11-20 03:17 UTC
On the connection window, the Username/Password are behind forms.

**Comment by marusak** [comment] 2019-11-21 08:35
By "connection window" you mean login screen? And what you mean by "are behind forms"? Is this related to https://github.com/cockpit-project/cockpit/issues/6399#issuecomment-555818719 ?

**Comment by Neustradamus** [comment] 2019-11-21 21:10
@marusak: No.

Another people speak about it here: https://community.nethserver.org/t/nethserver-7-7-cockpit-edition-released/13823/22

There is a translation problem too, the page is not completely refreshed.

**Comment by marusak** [comment] 2019-11-21 21:42
Ah, this is fixed in master and also in release 206 (I think, maybe 207)
Duplicate of https://github.com/cockpit-project/cockpit/issues/13047
Fixed in https://github.com/cockpit-project/cockpit/pull/13058

> There is a translation problem too, the page is not completely refreshed.

We show as many translations as we have access to. So this is only problem of incomplete translations in Zanata.

**Closed by marusak** 2019-11-21 21:42 UTC

**Comment by Neustradamus** [comment] 2019-11-21 21:56
No translations are here, after several window refresh (F5) or cache cleaning, it is good!

**Comment by Neustradamus** [comment] 2019-11-22 17:51
@marusak: Can you test it and confirm this bug?

**Comment by marusak** [comment] 2019-11-24 08:55
> Can you test it and confirm this bug?

What bug?

**Comment by Neustradamus** [comment] 2019-11-24 19:01
About translation: Translations are here but when we change of language, some parts are not changed.

-> "No, translations are here, after several window refreshes (F5) or cache cleaning, it is good!
There is always a little problem."

**Comment by marusak** [comment] 2019-11-25 08:14
> Translations are here but when we change of language, some parts are not changed.

This still seems to me like incomplete translations. I commented on it in my reply above. Can you please provide screenshot, as it seems we are not on the same page.

**Comment by Neustradamus** [comment] 2019-11-26 04:54
@marusak: I have done all screenshots for you, step by step:
- https://i.ibb.co/yPfpchT/1-nethserver-login-english.png
- https://i.ibb.co/g4Z2zzN/2-nethserver-dashboard-english-normal.png
- https://i.ibb.co/CnPPpq0/3-nethserver-root-info-english-normal.png
- Spanish selection and validation
- https://i.ibb.co/1MGmd8V/4-nethserver-dashboard-spanish-not-complete.png (Red part)
- https://i.ibb.co/fpbzBYX/5-nethserver-root-info-spanish-after-language-change-not-complete.png (Red part)
- https://i.ibb.co/8BBgMTS/6-nethserver-login-spanish-after-logout.png (Username/Password behind forms in the same time)
- https://i.ibb.co/3CndnQR/7-nethserver-dashboard-spanish-after-logout-and-new-login.png
- https://i.ibb.co/SstNxmC/8-nethserver-root-info-spanish-after-logout-and-new-login.png

You can see complete languages are here :)

cc @gsanchietti.

**Comment by marusak** [comment] 2019-11-26 08:09
So is the problem that you need to log out to see the translations?
What browser are you using? We know about some problems with chromium (see https://github.com/cockpit-project/cockpit/issues/8160).

**Comment by Neustradamus** [comment] 2019-11-26 16:52
Yes, about languages problem: Opera, Opera is based on Chromium, no problem with Firefox.

@gsanchietti: Username/Password behind forms is solved by an update of cockpit, can you do this?
- https://github.com/cockpit-project/cockpit/issues/13172#issuecomment-557285191

**Comment by Neustradamus** [comment] 2019-11-26 17:06
@marusak: Login button it is solved too?
- https://i.ibb.co/2kRh4SK/X-nethserver-login-button-problem-other-language.png

**Comment by marusak** [comment] 2019-11-26 17:35
>  Login button it is solved too?

It is massive now, so I believe so.
![jj](https://user-images.githubusercontent.com/12330670/69657869-69300d00-107b-11ea-8611-6ffef5585db8.png)

**Comment by Neustradamus** [comment] 2019-11-26 20:22
@marusak: Thanks for your reply!

@gsanchietti: Can you see for a NethServer Cockpit update?
