### ISSUE TITLE
network page not working.

### ISSUE THREAD

**Issue by paomian** [cockpit-project/cockpit#19417] opened 2023-10-01 05:37 UTC
### Explain what happens

1. login in web console
2. open network
3. I will get this error in network

```
networkmanager.js:11  Uncaught TypeError: Cannot read properties of undefined (reading 'v')
    at networkmanager.js:11:290017
    at Array.map (<anonymous>)
    at V (networkmanager.js:11:289925)
    at Function.<anonymous> (networkmanager.js:11:294424)
    at G (cockpit.js:5:5607)
    at cockpit.js:5:5802
    at k (cockpit.js:5:4658)
```

```
                peers: G("wireguard", "peers", []).map(fe=>({
                    publicKey: fe["public-key"].v,
                    endpoint: fe.endpoint?.v,
                    allowedIps: fe["allowed-ips"].v
                }))
```
the `allowed-ips` not exists
I stringify fe get `'{"public-key":{"t":"s","v":"xxxxx"}}'` 

and when i restart networkmanager service, I can enter the network page ,but when i refresh the page i will get the same error.
My network manager version is 
```
NetworkManager --version
1.42.8-1.fc38
```

### Version of Cockpit

301

### Where is the problem in Cockpit?

Networking

### Server operating system

Fedora

### Server operating system version

38

### What browsers are you using?

Edge

**Comment by subhoghoshX** [comment] 2023-10-01 15:30
Apologies for the inconvenience. It's fixed in #19395.

Duplicate of #19384.

**Closed by subhoghoshX** 2023-10-01 15:30 UTC
Labels: bug
