### ISSUE TITLE
Running cockpit under wsl 2

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14700] opened 2020-10-05 10:25 UTC
hi.. is it possible to run cockpit under ubuntu running under wsl2? 
one restriction that i know of is that curretnly wsl2 doesn't support systemd which makes it a problem for cockpit

**Comment by marusak** [comment] 2020-10-08 09:02
Dupe of #14699

**Closed by marusak** 2020-10-08 09:02 UTC
