### ISSUE TITLE
Tests failed on 6ac0b4b1cd86f75227a23d82a405990d8c11edec

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21063] opened 2024-10-02 03:08 UTC
The job `fedora-40/updates-testing` failed on commit 6ac0b4b1cd86f75227a23d82a405990d8c11edec.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6ac0b4b1-20241002-013119-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-02 04:23
Duplicate of #21048

**Closed by martinpitt** 2024-10-02 04:23 UTC
Labels: nightly
