### ISSUE TITLE
Tests failed on fe196082855cd53d3fe9c4da91048b0a2ade6fe1

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21129] opened 2024-10-17 02:28 UTC
The job `fedora-40/updates-testing` failed on commit fe196082855cd53d3fe9c4da91048b0a2ade6fe1.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-fe196082-20241017-013110-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-17 04:40
Still the broken stratisd 3.7.1 and thus a duplicate of #21108. https://bodhi.fedoraproject.org/updates/FEDORA-2024-09cee483a4 is still not visible on the mirrors.

**Closed by martinpitt** 2024-10-17 04:40 UTC
Labels: nightly
