### ISSUE TITLE
Does not appear to support ARM (BBG)

### ISSUE THREAD

**Issue by dalers** [cockpit-project/cockpit#7366] opened 2017-07-25 07:28 UTC
I'm a Cockpit newb, but listed to the FLOSS Weekly interview and think Cockpit would be ideal for interacting with remote IoT-type gateways. I'm trying to install Cockpit on Debian Jessie running on a [Beaglebone Green (BBG)](http://beagleboard.org/green), which has a TI ARM Cortex A-8 processor and the supported distribution is based on Debian. I followed the [Debian instructions on the Cockpit website](http://cockpit-project.org/running.html) but it appears there is no ARM package (I also regret to say I'm a newb using Debian). Is my understanding correct? Is there another way to install Cockpit?

Fwiw, I followed the ["Join the Mailing List"](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/) link on the Cockpit website intending to post there instead, but it appears I must sign in to post and new registrations are closed (I may have that wrong, I'm also a Fedora mailing list newb). Sorry to have to put this in an Issue. If there is a better place to ask, please say where.

Thanks in advance,
Dale

```
debian@beaglebone:~$ sudo apt-get update
Hit http://security.debian.org jessie/updates InRelease
Hit http://repos.rcn-ee.com jessie InRelease
Hit http://repo-cockpitproject.rhcloud.com jessie InRelease
Ign http://httpredir.debian.org jessie InRelease
Hit https://deb.nodesource.com jessie InRelease
Hit http://httpredir.debian.org jessie-updates InRelease
Hit http://httpredir.debian.org jessie Release.gpg
Hit http://httpredir.debian.org jessie Release
Get:1 http://security.debian.org jessie/updates/main armhf Packages [522 kB]
Get:2 http://repos.rcn-ee.com jessie/main armhf Packages [741 kB]
Get:3 https://deb.nodesource.com jessie/main armhf Packages [969 B]
Get:4 http://security.debian.org jessie/updates/contrib armhf Packages [994 B]
Get:5 http://security.debian.org jessie/updates/non-free armhf Packages [20 B]
Get:6 http://httpredir.debian.org jessie-updates/main armhf Packages [17.8 kB]
Get:7 http://httpredir.debian.org jessie-updates/contrib armhf Packages [20 B]
Get:8 http://httpredir.debian.org jessie-updates/non-free armhf Packages [450 B]
Get:9 http://httpredir.debian.org jessie/main armhf Packages [8,864 kB]
Get:10 http://httpredir.debian.org jessie/contrib armhf Packages [44.3 kB]
Get:11 http://httpredir.debian.org jessie/non-free armhf Packages [74.9 kB]
Fetched 10.3 MB in 15s (659 kB/s)
W: Failed to fetch http://repo-cockpitproject.rhcloud.com/debian/dists/jessie/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
debian@beaglebone:~$ sudo apt-get install cockpit
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cockpit
debian@beaglebone:~$
```

**Comment by stefwalter** [comment] 2017-07-25 07:30
I know there's an ARM package for Fedora. @martinpitt do we have arm packages in testing or elsewhere?

**Comment by martinpitt** [comment] 2017-07-25 08:21
@dalers: There will soon be an ARM package for Debian 9, in the official [Debian backports repository](https://backports.debian.org/). This is still stuck in [the NEW queue](https://ftp-master.debian.org/backports-new.html), but I hope it will be processed in the next days/few weeks.

There is not currently an ARM package for Debian 8. If there is much demand, I can also upload it to jessie-backports-sloppy, so that there is again an official backport. But this should wait for the Debian 9 backport.

Until then you are of course welcome to just backport/build it yourself, with something like 
```
# install build dependencies
sudo apt-get install -y debhelper dh-systemd dh-autoreconf autoconf automake git intltool libssh-dev zlib1g-dev libkrb5-dev libxslt1-dev libglib2.0-dev libsystemd-dev libpolkit-agent-1-dev libjson-glib-dev libpam0g-dev xsltproc xmlto docbook-xsl glib-networking openssh-client python

dget http://httpredir.debian.org/debian/pool/main/c/cockpit/cockpit_146-1.dsc
dpkg-source -x cockpit_*.dsc
cd cockpit-*
dpkg-buildpackage -us -uc -b
```

**Comment by martinpitt** [comment] 2017-07-25 08:23
Closing as duplicate of issue #6560.

**Closed by martinpitt** 2017-07-25 08:23 UTC

**Comment by leonardosalvatore** [comment] 2017-11-08 13:21
Any news on that issue? 
Is a Debian (8/9) ARM build available?

Thank you.

**Comment by martinpitt** [comment] 2017-11-08 14:00
Yes, cockpit is now in the official backports for both Debian 8 and 9, and there are ARM builds available too.
