### ISSUE TITLE
Using --no-tls with an ssl vhost and http proxy results in an invalid handshake

### ISSUE THREAD

**Issue by hashworks** [cockpit-project/cockpit#2053] opened 2015-03-29 09:59 UTC
I'm using cockpit with the `--no-tls` option since I'm only accessing it locally anyway:
```
[Unit]
Description=Cockpit Web Server
Documentation=man:cockpit-ws(8)

[Service]
#ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=
ExecStart=/usr/libexec/cockpit-ws --no-tls
PermissionsStartOnly=true
User=root
Group=
```

I also have an apache ssl vhost with an http proxy pointing to cockpit:
```
<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerName cockpit.example.org
                [...]
                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass / http://127.0.0.1:9090/ retry=0
                ProxyPassReverse / http://127.0.0.1:9090/
        </VirtualHost>
</IfModule>
```

The login page openes fine, however as soon as I log in I get `Server has closed the connection.` with the following in the cockpit journal:
```
Mär 29 11:57:21 example cockpit-ws[23712]: received invalid or missing Upgrade header: (null)
Mär 29 11:57:21 example cockpit-ws[23712]: Received invalid handshake request from the client
```

I'm not sure why this occures, cockpit shouldn't handle any tls stuff with `--no-tls`.

**Comment by stefwalter** [comment] 2015-03-30 07:51
Apache mod_proxy.so does not support WebSockets. You probably need to experiment with this:

http://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

Either way, this is not a bug in Cockpit. Closing.

**Closed by stefwalter** 2015-03-30 07:51 UTC
Labels: invalid

**Comment by darioce** [comment] 2017-12-18 08:52
To make proxies work with Apache, I added the following to my virtual host definition

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
  [...]

  ProxyPreserveHost On
  ProxyRequests Off

  # allow for upgrading to websockets
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://127.0.0.1:9090/ [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://127.0.0.1:9090/ [P,L]

  # Proxy to your local cockpit instance
  ProxyPass / http://127.0.0.1:9090/
  ProxyPassReverse / http://127.0.0.1:9090/

</VirtualHost>
</IfModule>
```

I have written up the details [here](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt).
