### ISSUE TITLE
when I open https://myip:9090, the whole web site is blank

### ISSUE THREAD

**Issue by Sherlock-Holo** [cockpit-project/cockpit#10661] opened 2018-11-25 03:07 UTC
when I open https://myip:9090, the whole web site is blank.

![image](https://user-images.githubusercontent.com/10096425/48974982-b6148880-f0a1-11e8-8d22-e863e549aba2.png)

the firefox console give me some error:

> Error: Unclosed section "can_sync" at 554 index.js:6428:43
> s
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:6428:43
> p.prototype.parse
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:6519:45
> e.parse
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:6561:20
> t
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:5865:17
> <anonymous>
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:6337:28
> <anonymous>
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:5859:6
> t
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:9:16
> <anonymous>
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:18:37
> <anonymous>
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:17:6
> t
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:9:16
> <anonymous>
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:14:5
> t
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:9:16
> <anonymous>
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:12:40
> <anonymous>
> https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js:1:2
> Source map error: request failed with status 404
> Resource URL: https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.css
> Source Map URL: index.css.map[Learn More]
> Source map error: request failed with status 404
> Resource URL: https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/base1/patternfly.css
> Source Map URL: patternfly.min.css.map[Learn More]
> Source map error: request failed with status 404
> Resource URL: https://45.32.66.185:9090/cockpit/$9428dd4e9f7575bdd0fc7b3dda862d4fd1d84f5661dc582e280a6a212a6b04aa/shell/index.js
> Source Map URL: index.min.js.map[Learn More]

the systemd log is:

> -- Logs begin at Mon 2018-10-08 10:34:25 CST, end at Sun 2018-11-25 11:04:58 CST. --                                    
> Nov 25 03:07:14 Fedora29 systemd[1]: Starting Cockpit Web Service...                                                    
> Nov 25 03:07:14 Fedora29 systemd[1]: Started Cockpit Web Service.                                                       
> Nov 25 03:07:14 Fedora29 cockpit-ws[2041]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert                
> Nov 25 08:56:30 Fedora29 systemd[1]: Starting Cockpit Web Service...                                                    
> Nov 25 08:56:30 Fedora29 systemd[1]: Started Cockpit Web Service.                                                       
> Nov 25 08:56:30 Fedora29 cockpit-ws[3209]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert                
> Nov 25 10:17:38 Fedora29 systemd[1]: Starting Cockpit Web Service...                                                    
> Nov 25 10:17:38 Fedora29 systemd[1]: Started Cockpit Web Service.                                                       
> Nov 25 10:17:38 Fedora29 cockpit-ws[3585]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert                
> Nov 25 10:18:06 Fedora29 cockpit-session[3593]: pam_ssh_add: Failed adding some keys                                    
> Nov 25 10:18:06 Fedora29 cockpit-session[3593]: pam_unix(cockpit:session): session opened for user root by (uid=0)      
> Nov 25 10:18:06 Fedora29 cockpit-ws[3585]: logged in user session                                                       
> Nov 25 10:18:09 Fedora29 cockpit-ws[3585]: New connection to session from 183.238.79.14                                 
> Nov 25 10:26:47 Fedora29 cockpit-ws[3585]: couldn't read from connection: Peer failed to perform TLS handshake          
> Nov 25 10:26:50 Fedora29 cockpit-ws[3585]: New connection to session from 183.238.79.14                                 
> Nov 25 10:26:55 Fedora29 cockpit-ws[3585]: WebSocket from 183.238.79.14 for session closed                              
> Nov 25 10:26:57 Fedora29 cockpit-ws[3585]: New connection to session from 183.238.79.14                                 
> Nov 25 10:27:23 Fedora29 cockpit-ws[3585]: WebSocket from 183.238.79.14 for session closed                              
> Nov 25 10:27:25 Fedora29 cockpit-ws[3585]: New connection to session from 183.238.79.14                                 
> Nov 25 10:27:37 Fedora29 cockpit-ws[3585]: WebSocket from 183.238.79.14 for session closed                              
> Nov 25 10:27:38 Fedora29 cockpit-ws[3585]: New connection to session from 183.238.79.14
> Nov 25 10:28:13 Fedora29 systemd[1]: Stopping Cockpit Web Service...                                                    
> Nov 25 10:28:13 Fedora29 systemd[1]: Stopped Cockpit Web Service.                                                       
> Nov 25 10:28:13 Fedora29 systemd[1]: Starting Cockpit Web Service...                                                    
> Nov 25 10:28:13 Fedora29 remotectl[3805]: remotectl: Error loading certificates from /etc/cockpit/ws-certs.d: Error open
> ing directory ?/etc/cockpit/ws-certs.d?: No such file or directory
> Nov 25 10:28:13 Fedora29 systemd[1]: cockpit.service: Control process exited, code=exited status=1
> Nov 25 10:28:13 Fedora29 systemd[1]: cockpit.service: Failed with result 'exit-code'.
> Nov 25 10:28:13 Fedora29 systemd[1]: Failed to start Cockpit Web Service.
> Nov 25 10:28:39 Fedora29 systemd[1]: Starting Cockpit Web Service...
> Nov 25 10:28:39 Fedora29 systemd[1]: Started Cockpit Web Service.
> Nov 25 10:28:39 Fedora29 cockpit-ws[3848]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
> Nov 25 10:40:14 Fedora29 systemd[1]: Starting Cockpit Web Service...
> Nov 25 10:40:14 Fedora29 systemd[1]: Started Cockpit Web Service.
> Nov 25 10:40:14 Fedora29 cockpit-ws[4518]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
> Nov 25 10:40:14 Fedora29 cockpit-ws[4518]: received invalid HTTP request line
> Nov 25 10:44:29 Fedora29 systemd[1]: Starting Cockpit Web Service...
> Nov 25 10:44:29 Fedora29 remotectl[4609]: remotectl: /etc/cockpit/ws-certs.d/0-self-signed.cert: No PEM-encoded private
> key found
> Nov 25 10:44:29 Fedora29 systemd[1]: cockpit.service: Control process exited, code=exited status=1
> Nov 25 10:44:29 Fedora29 systemd[1]: cockpit.service: Failed with result 'exit-code'.
> Nov 25 10:44:29 Fedora29 systemd[1]: Failed to start Cockpit Web Service.
> Nov 25 10:47:39 Fedora29 systemd[1]: Starting Cockpit Web Service...
> Nov 25 10:47:39 Fedora29 remotectl[4684]: remotectl: /etc/cockpit/ws-certs.d/0-self-signed.cert: No PEM-encoded certific
> ate found
> Nov 25 10:47:39 Fedora29 systemd[1]: cockpit.service: Control process exited, code=exited status=1
> Nov 25 10:47:39 Fedora29 systemd[1]: cockpit.service: Failed with result 'exit-code'.
> Nov 25 10:47:39 Fedora29 systemd[1]: Failed to start Cockpit Web Service.
> Nov 25 10:49:43 Fedora29 systemd[1]: Starting Cockpit Web Service...
> Nov 25 10:49:43 Fedora29 systemd[1]: Started Cockpit Web Service.
> Nov 25 10:49:43 Fedora29 cockpit-ws[4830]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
> Nov 25 10:50:01 Fedora29 cockpit-session[4842]: pam_ssh_add: Failed adding some keys
> Nov 25 10:50:01 Fedora29 cockpit-session[4842]: pam_unix(cockpit:session): session opened for user root by (uid=0)
> Nov 25 10:50:01 Fedora29 cockpit-ws[4830]: cockpit-session: pam: Last failed login: Sun Nov 25 10:46:13 CST 2018 from 21
> 8.92.1.153 on ssh:notty
> Nov 25 10:50:01 Fedora29 cockpit-ws[4830]: cockpit-session: pam: There were 16 failed login attempts since the last successful login.
> Nov 25 10:50:01 Fedora29 cockpit-ws[4830]: logged in user session                                                      
> Nov 25 10:50:04 Fedora29 cockpit-ws[4830]: New connection to session from 183.238.79.14                                
> Nov 25 10:50:06 Fedora29 cockpit-ws[4830]: WebSocket from 183.238.79.14 for session closed                             
> Nov 25 10:50:21 Fedora29 cockpit-ws[4830]: session timed out                                                           
> Nov 25 10:57:39 Fedora29 systemd[1]: Starting Cockpit Web Service...                                                   
> Nov 25 10:57:39 Fedora29 systemd[1]: Started Cockpit Web Service.                                                      
> Nov 25 10:57:39 Fedora29 cockpit-ws[4953]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert               
> Nov 25 10:57:40 Fedora29 cockpit-ws[4953]: couldn't read from connection: Peer sent fatal TLS alert: CA is unknown     
> Nov 25 10:57:40 Fedora29 cockpit-ws[4953]: couldn't read from connection: Peer sent fatal TLS alert: CA is unknown     
> Nov 25 10:57:59 Fedora29 unix_chkpwd[4964]: password check failed for user (root)                                      
> Nov 25 10:57:59 Fedora29 cockpit-session[4962]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=183.238.79.14  user=root
> Nov 25 10:58:09 Fedora29 cockpit-session[4965]: pam_ssh_add: Failed adding some keys                                   
> Nov 25 10:58:09 Fedora29 cockpit-session[4965]: pam_unix(cockpit:session): session opened for user root by (uid=0)     
> Nov 25 10:58:09 Fedora29 cockpit-ws[4953]: cockpit-session: pam: Last failed login: Sun Nov 25 10:57:36 CST 2018 from 218.92.1.153 on ssh:notty
> Nov 25 10:58:09 Fedora29 cockpit-ws[4953]: cockpit-session: pam: There were 22 failed login attempts since the last successful login.
> Nov 25 10:58:09 Fedora29 cockpit-ws[4953]: logged in user session                                                      
> Nov 25 10:58:12 Fedora29 cockpit-ws[4953]: New connection to session from 183.238.79.14                                
> Nov 25 10:59:24 Fedora29 cockpit-ws[4953]: WebSocket from 183.238.79.14 for session closed                             
> Nov 25 10:59:34 Fedora29 cockpit-ws[4953]: couldn't read from connection: Peer sent fatal TLS alert: CA is unknown     
> Nov 25 10:59:34 Fedora29 cockpit-ws[4953]: couldn't read from connection: Peer sent fatal TLS alert: CA is unknown     
> Nov 25 10:59:34 Fedora29 cockpit-ws[4953]: couldn't read from connection: Peer sent fatal TLS alert: CA is unknown     
> Nov 25 10:59:40 Fedora29 cockpit-ws[4953]: session timed out                                                           
> Nov 25 10:59:48 Fedora29 cockpit-session[4996]: pam_ssh_add: Failed adding some keys                                   
> Nov 25 10:59:48 Fedora29 cockpit-session[4996]: pam_unix(cockpit:session): session opened for user root by (uid=0)     
> Nov 25 10:59:49 Fedora29 cockpit-ws[4953]: cockpit-session: pam: Last failed login: Sun Nov 25 10:57:36 CST 2018 from 218.92.1.153 on ssh:notty
> Nov 25 10:59:49 Fedora29 cockpit-ws[4953]: cockpit-session: pam: There were 22 failed login attempts since the last successful login.
> Nov 25 10:59:49 Fedora29 cockpit-ws[4953]: logged in user session                                                      
> Nov 25 10:59:52 Fedora29 cockpit-ws[4953]: New connection to session from 183.238.79.14

I want to use this to manager my server but when I see this I feel sad

**Comment by Lordfourteen** [comment] 2018-12-02 02:35
I get the same mistakes after I install cockpit

**Comment by martinpitt** [comment] 2018-12-06 15:14
Duplicate of issue #10604

**Closed by martinpitt** 2018-12-06 15:14 UTC
