### ISSUE TITLE
Unable to install Machines Application due to a package already being installed

### ISSUE THREAD

**Issue by Justinzobel** [cockpit-project/cockpit#18130] opened 2023-01-06 01:33 UTC
### Explain what happens

1. Attempt to install Machines Application from Applications Menu
2. Error appears `Error running transaction: package cockpit-bridge-282-1.fc37.x86_64 is already installed`

### Version of Cockpit

282

### Where is the problem in Cockpit?

Applications

### Server operating system

Fedora

### Server operating system version

37

### What browsers are you using?

Firefox

### System log

```shell
A package already being installed shouldn't be an issue.
```

**Comment by KKoukiou** [comment] 2023-01-06 14:05
I can't reproduce, can you reproduce from CLI? `sudo pkcon install cockpit-machines`

**Comment by KKoukiou** [comment] 2023-01-23 11:25
Closing as issuer did not respond.

**Closed by KKoukiou** 2023-01-23 11:25 UTC
Labels: question, bug
