### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20054] opened 2024-02-17 02:21 UTC
Tests failed on 1a151ef292939e23701db1be189035a76f71b7b1, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240217-012333-1a151ef2-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment] 2024-02-17 05:42
Duplicate of #19765

**Closed by martinpitt** 2024-02-17 05:42 UTC
Labels: nightly
