### ISSUE TITLE
Avocado tests fail with Avocado version mismatch

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1927] opened 2015-03-16 19:53 UTC
After running the avocado tests successfully a few times today, for some reason they now fail with:

```
20150316-19:50:43 HOST: avocado versions are not same on LOCAL and REMOTE Avocado 0.20.2 != Avocado 0.21.0 (SHOULD BE)
```

**Comment by stefwalter** [comment] 2015-03-16 19:53
More details:

```
[stef@falcon cockpit]$ TEST_JOBS=4 ./VERIFY 
20150316-19:49:21 HOST: >>> fedora-21 testing <<<
20150316-19:49:21 HOST: All packages alread installed
20150316-19:49:21 HOST: Virtualization enabled for user
20150316-19:49:21 HOST: Network domain configured for qemu
20150316-19:49:21 HOST: Host already configured
20150316-19:49:21 HOST: Starting checkmachine7-fedora-21-x86_64
Domain checkmachine7-fedora-21-x86_64 started

20150316-19:49:22 HOST: Reverting checkmachine7-fedora-21-x86_64 to last 'initialized' state
20150316-19:49:23 HOST: Setting up checkmachine7-fedora-21-x86_64
20150316-19:49:25 COCKPIT GUEST: Updating base packages
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package avocado.noarch 0:0.20.2-3.fc21 will be updated
---> Package avocado.noarch 0:0.21.0-0.fc21 will be an update
--> Processing Dependency: libvirt-python for package: avocado-0.21.0-0.fc21.noarch
--> Running transaction check
---> Package libvirt-python.x86_64 0:1.2.9-1.fc21 will be installed
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.2.9)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.2.8)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.2.7)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.2.6)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.2.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.2.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.2.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.1.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.1.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.1.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.0.6)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.0.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.0.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.0.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.0.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_1.0.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.9)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.8)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.7)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.4)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.13)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.11)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.10)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.9.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.8.8)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.8.6)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.8.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.8.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.8.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.8.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.7.7)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.7.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.7.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.7.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.7.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.7.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.6.4)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.6.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.6.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.6.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.5.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.4.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.4.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.4.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.4.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.3.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.3.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.3.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.2.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.2.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.2.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.10.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.10.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.1.9)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.1.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.1.4)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.1.1)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.1.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.0.5)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0(LIBVIRT_0.0.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt-qemu.so.0(LIBVIRT_QEMU_1.2.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt-qemu.so.0(LIBVIRT_QEMU_0.9.4)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt-qemu.so.0(LIBVIRT_QEMU_0.8.3)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt-qemu.so.0(LIBVIRT_QEMU_0.10.0)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt-lxc.so.0(LIBVIRT_LXC_1.0.2)(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt.so.0()(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt-qemu.so.0()(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Processing Dependency: libvirt-lxc.so.0()(64bit) for package: libvirt-python-1.2.9-1.fc21.x86_64
--> Running transaction check
---> Package libvirt-client.x86_64 0:1.2.9.2-1.fc21 will be installed
--> Processing Dependency: nc for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: libnuma.so.1(libnuma_1.2)(64bit) for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: libnuma.so.1(libnuma_1.1)(64bit) for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: gnutls-utils for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: cyrus-sasl-md5 for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: cyrus-sasl for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: libyajl.so.2()(64bit) for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: libwsman_curl_client_transport.so.1()(64bit) for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: libwsman_client.so.2()(64bit) for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: libwsman.so.1()(64bit) for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Processing Dependency: libnuma.so.1()(64bit) for package: libvirt-client-1.2.9.2-1.fc21.x86_64
--> Running transaction check
---> Package cyrus-sasl.x86_64 0:2.1.26-19.fc21 will be installed
---> Package cyrus-sasl-md5.x86_64 0:2.1.26-19.fc21 will be installed
---> Package gnutls-utils.x86_64 0:3.3.13-1.fc21 will be installed
--> Processing Dependency: gnutls-dane(x86-64) = 3.3.13-1.fc21 for package: gnutls-utils-3.3.13-1.fc21.x86_64
--> Processing Dependency: gnutls(x86-64) = 3.3.13-1.fc21 for package: gnutls-utils-3.3.13-1.fc21.x86_64
--> Processing Dependency: libgnutls-dane.so.0(DANE_0_0)(64bit) for package: gnutls-utils-3.3.13-1.fc21.x86_64
--> Processing Dependency: libgnutls-dane.so.0()(64bit) for package: gnutls-utils-3.3.13-1.fc21.x86_64
---> Package libwsman1.x86_64 0:2.4.6-3.fc21 will be installed
---> Package nmap-ncat.x86_64 2:6.47-1.fc21 will be installed
---> Package numactl-libs.x86_64 0:2.0.9-4.fc21 will be installed
---> Package yajl.x86_64 0:2.1.0-3.fc21 will be installed
--> Running transaction check
---> Package gnutls.x86_64 0:3.3.10-1.fc21 will be updated
---> Package gnutls.x86_64 0:3.3.13-1.fc21 will be an update
---> Package gnutls-dane.x86_64 0:3.3.13-1.fc21 will be installed
--> Processing Dependency: libunbound.so.2()(64bit) for package: gnutls-dane-3.3.13-1.fc21.x86_64
--> Running transaction check
---> Package unbound-libs.x86_64 0:1.5.1-2.fc21 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package             Arch        Version                Repository         Size
================================================================================
Updating:
 avocado             noarch      0.21.0-0.fc21          lmr-Autotest      300 k
Installing for dependencies:
 cyrus-sasl          x86_64      2.1.26-19.fc21         fedora             92 k
 cyrus-sasl-md5      x86_64      2.1.26-19.fc21         fedora             60 k
 gnutls-dane         x86_64      3.3.13-1.fc21          updates            36 k
 gnutls-utils        x86_64      3.3.13-1.fc21          updates           237 k
 libvirt-client      x86_64      1.2.9.2-1.fc21         updates           4.4 M
 libvirt-python      x86_64      1.2.9-1.fc21           fedora            231 k
 libwsman1           x86_64      2.4.6-3.fc21           fedora            129 k
 nmap-ncat           x86_64      2:6.47-1.fc21          fedora            135 k
 numactl-libs        x86_64      2.0.9-4.fc21           fedora             32 k
 unbound-libs        x86_64      1.5.1-2.fc21           updates           341 k
 yajl                x86_64      2.1.0-3.fc21           fedora             37 k
Updating for dependencies:
 gnutls              x86_64      3.3.13-1.fc21          updates           626 k

Transaction Summary
================================================================================
Install             ( 11 Dependent packages)
Upgrade  1 Package  (+ 1 Dependent package)

Total download size: 6.6 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
--------------------------------------------------------------------------------
Total                                              1.1 MB/s | 6.6 MB  00:05     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction (shutdown inhibited)
  Updating   : gnutls-3.3.13-1.fc21.x86_64                                 1/15 
  Installing : yajl-2.1.0-3.fc21.x86_64                                    2/15 
  Installing : cyrus-sasl-2.1.26-19.fc21.x86_64                            3/15 
  Installing : libwsman1-2.4.6-3.fc21.x86_64                               4/15 
  Installing : numactl-libs-2.0.9-4.fc21.x86_64                            5/15 
  Installing : unbound-libs-1.5.1-2.fc21.x86_64                            6/15 
  Installing : gnutls-dane-3.3.13-1.fc21.x86_64                            7/15 
  Installing : gnutls-utils-3.3.13-1.fc21.x86_64                           8/15 
  Installing : cyrus-sasl-md5-2.1.26-19.fc21.x86_64                        9/15 
  Installing : 2:nmap-ncat-6.47-1.fc21.x86_64                             10/15 
  Installing : libvirt-client-1.2.9.2-1.fc21.x86_64                       11/15 
  Installing : libvirt-python-1.2.9-1.fc21.x86_64                         12/15 
  Updating   : avocado-0.21.0-0.fc21.noarch                               13/15 
  Cleanup    : avocado-0.20.2-3.fc21.noarch                               14/15 
  Cleanup    : gnutls-3.3.10-1.fc21.x86_64                                15/15 
  Verifying  : 2:nmap-ncat-6.47-1.fc21.x86_64                              1/15 
  Verifying  : cyrus-sasl-md5-2.1.26-19.fc21.x86_64                        2/15 
  Verifying  : unbound-libs-1.5.1-2.fc21.x86_64                            3/15 
  Verifying  : numactl-libs-2.0.9-4.fc21.x86_64                            4/15 
  Verifying  : libwsman1-2.4.6-3.fc21.x86_64                               5/15 
  Verifying  : cyrus-sasl-2.1.26-19.fc21.x86_64                            6/15 
  Verifying  : gnutls-utils-3.3.13-1.fc21.x86_64                           7/15 
  Verifying  : libvirt-python-1.2.9-1.fc21.x86_64                          8/15 
  Verifying  : gnutls-3.3.13-1.fc21.x86_64                                 9/15 
  Verifying  : libvirt-client-1.2.9.2-1.fc21.x86_64                       10/15 
  Verifying  : avocado-0.21.0-0.fc21.noarch                               11/15 
  Verifying  : gnutls-dane-3.3.13-1.fc21.x86_64                           12/15 
  Verifying  : yajl-2.1.0-3.fc21.x86_64                                   13/15 
  Verifying  : gnutls-3.3.10-1.fc21.x86_64                                14/15 
  Verifying  : avocado-0.20.2-3.fc21.noarch                               15/15 

Dependency Installed:
  cyrus-sasl.x86_64 0:2.1.26-19.fc21     cyrus-sasl-md5.x86_64 0:2.1.26-19.fc21
  gnutls-dane.x86_64 0:3.3.13-1.fc21     gnutls-utils.x86_64 0:3.3.13-1.fc21   
  libvirt-client.x86_64 0:1.2.9.2-1.fc21 libvirt-python.x86_64 0:1.2.9-1.fc21  
  libwsman1.x86_64 0:2.4.6-3.fc21        nmap-ncat.x86_64 2:6.47-1.fc21        
  numactl-libs.x86_64 0:2.0.9-4.fc21     unbound-libs.x86_64 0:1.5.1-2.fc21    
  yajl.x86_64 0:2.1.0-3.fc21            

Updated:
  avocado.noarch 0:0.21.0-0.fc21                                                

Dependency Updated:
  gnutls.x86_64 0:3.3.13-1.fc21                                                 

Complete!
20150316-19:49:49 COCKPIT GUEST: Updating build dependencies
warning: bogus date in %changelog: Mon Mar 06 2015 Fridolin Pokorny <fpokorny@redhat.com> - 0.41-2
Loaded plugins: product-id
20150316-19:49:49 COCKPIT GUEST: Updating run-time dependencies
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package expect.x86_64 0:5.45-17.fc21 will be installed
--> Processing Dependency: libtcl8.6.so()(64bit) for package: expect-5.45-17.fc21.x86_64
--> Running transaction check
---> Package tcl.x86_64 1:8.6.3-1.fc21 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package         Arch            Version                  Repository       Size
================================================================================
Installing:
 expect          x86_64          5.45-17.fc21             fedora          264 k
Installing for dependencies:
 tcl             x86_64          1:8.6.3-1.fc21           fedora          2.2 M

Transaction Summary
================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 2.5 M
Installed size: 5.7 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                              1.2 MB/s | 2.5 MB  00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction (shutdown inhibited)
  Installing : 1:tcl-8.6.3-1.fc21.x86_64                                    1/2 
  Installing : expect-5.45-17.fc21.x86_64                                   2/2 
  Verifying  : 1:tcl-8.6.3-1.fc21.x86_64                                    1/2 
  Verifying  : expect-5.45-17.fc21.x86_64                                   2/2 

Installed:
  expect.x86_64 0:5.45-17.fc21                                                  

Dependency Installed:
  tcl.x86_64 1:8.6.3-1.fc21                                                     

Complete!
20150316-19:49:57 COCKPIT GUEST: Phantomjs is already installed
20150316-19:50:01 HOST: Saving checkmachine7-fedora-21-x86_64 'initialized' state
20150316-19:50:09 HOST: Starting ipa-fedora-21-x86_64
Domain ipa-fedora-21-x86_64 started

20150316-19:50:09 HOST: Setting up ipa-fedora-21-x86_64
20150316-19:50:10 IPA GUEST: FreeIPA already configured
20150316-19:50:27 HOST: Tests will be run on these machines:
20150316-19:50:27 HOST:   checkmachine7-fedora-21-x86_64 / 52:54:00:f9:7f:bf / 192.168.123.4
20150316-19:50:27 HOST:   ipa-fedora-21-x86_64 / 52:54:00:06:33:1c / 192.168.123.5

20150316-19:50:43 HOST: avocado versions are not same on LOCAL and REMOTE Avocado 0.20.2 != Avocado 0.21.0 (SHOULD BE)
```

**Comment by stefwalter** [comment] 2015-03-16 19:53
I'm testing a branch that changed cockpit.setup. Maybe that has something to do with it?

**Comment by jscotka** [comment] 2015-03-17 08:00
I'm not sure if that problem is caused by these version difference, but could be. Could you please update your local machine, if it helps?
I had there also "exit 11" command. Because as I discussed with avocado developers, it is too young to have very stable API, so that is is better to have same (similar) version. Guests has newest version, because of new installation, but locally you can have older version. (Also guests can have old version in case, guest is not updated for long long time)
I've discussed it with @mvollmer

**Comment by stefwalter** [comment] 2015-03-17 08:46
You do realize that we use the CI during development heavily, right?

I understand right now for a week or two we discover a lot of issues.

But each of these issues needs to be solved in such a way that it **never** comes up again, otherwise the overhead of developing the CI (and developing against it) will be too high, and the CI will rot.

**Comment by stefwalter** [comment] 2015-03-17 08:47
@mvollmer With that in mind, can we lock down the version of avocado that we use (since it's unstable) and update it manually when necessary?

**Comment by jscotka** [comment] 2015-03-17 08:55
There are several ways how to solve it:
1. fix the version of avocado, downlaod some version locally and that version install on host and all guests
2. no nothing and have all systems updated to lastest version
3. do not use remote/vm plugin and schedule it via avocado locally in steps:
 cp test to remote machine
 avocado run localtest on guest
 copy results back to host

**Comment by stefwalter** [comment] 2015-03-17 09:03
After updating avocado on my system to 0.21.0-3 ./VERIFY seems to hang forever ... not sure of the cause :S

**Comment by martinpitt** [comment] 2019-01-10 16:55
We haven't seen this in years, closing.

**Closed by martinpitt** 2019-01-10 16:55 UTC
Labels: review-2019-01
