### ISSUE TITLE
Image refresh for debian-stable

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#6475] opened 2017-05-09 10:51 UTC
Image creation for debian-stable in process on cockpit-tests-3dkm0.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-stable-2017-05-09/

**Comment by cockpituous** [comment] 2017-05-09 10:56
Image creation aborted

**Comment by martinpitt** [comment] 2017-05-09 11:07
Dupe of #6476

**Closed by martinpitt** 2017-05-09 11:07 UTC
Labels: bot
