### ISSUE TITLE
Add DRBD support to cockpit-storaged

### ISSUE THREAD

**Issue by JohnnyElvis** [cockpit-project/cockpit#17042] opened 2022-02-23 21:43 UTC
It wouold be awesome to have DRBD covered in cockpit-storaged. 

Priority in descending order:

!. (would be awesome) Show replication status of "cat /proc/drbd" via UI. Detailed status message information can be found here - https://support.sciencelogic.com/s/article/1176

sample output

############

root@server:/etc/drbd.d# cat /proc/drbd
version: 8.4.11 (api:1/proto:86-101)
srcversion: C83CE761848B9DE61379370

 1: cs:SyncSource ro:Primary/Secondary ds:UpToDate/Inconsistent C r-----
    ns:696684000 nr:0 dw:2729072 dr:696641533 al:500 bm:0 lo:15 pe:1 ua:15 ap:0 ep:1 wo:f oos:3209234560
        [==>.................] sync'ed: 17.9% (3134016/3815352)M
        finish: 10:43:36 speed: 83,088 (100,400) K/sec
 2: cs:SyncTarget ro:Secondary/Primary ds:Inconsistent/UpToDate C r-----
    ns:0 nr:563686400 dw:563682304 dr:0 al:8 bm:0 lo:5 pe:21 ua:4 ap:0 ep:1 wo:f oos:1389772624
        [====>...............] sync'ed: 28.9% (1357196/1907668)M
        finish: 3:50:39 speed: 100,404 (103,180) want: 113,600 K/sec

############

2. (would be nice) Switch between primary/secondary node - via Pacemaker/Heartbeat - we can discuss this 

3. Set up  block device replication - we can discuss this as well

   Steps 3-6 from this documentation - https://www.tecmint.com/setup-drbd-storage-replication-on-centos-7/

**Comment by marusak** [comment] 2022-03-14 09:43
Duplicate of https://github.com/cockpit-project/cockpit/issues/13362
From ^:
> This is definitively something that we won't do in the cockpit project itself -- it should be developed [as a separate project](https://cockpit-project.org/blog/cockpit-starter-kit.html), by someone with the necessary domain knowledge. Thus closing this for the cockpit project. Thanks!

**Closed by marusak** 2022-03-14 09:43 UTC
Labels: enhancement, page:storage
