### ISSUE TITLE
Docker container terminal output from other machines added to cockpit shows "No such container"

### ISSUE THREAD

**Issue by dchem** [cockpit-project/cockpit#1635] opened 2015-01-12 03:24 UTC
When launching containers from other machines added to cockpit via "Add Host" menu in the cockpit dashboard, enabling "terminal" does not show the correct terminal output of the docker container. Instead, it shows:

```
No such container: <container_name_in_hash>
   disconnected
```

I verified that the container has indeed run properly by logging into the machine itself and then checking the docker log for that container image.

I'm using Cockpit distributed with Fedora 21 Server

**Comment by petervo** [comment] 2015-01-13 15:08
I wasn't able to reproduce this on master, of course things have changed quite a bit since then. Does not enabling terminal make any difference?

**Comment by mvollmer** [comment] 2015-01-14 07:23
See #1377.  I think this didn't make it to F21 yet.

**Comment by stefwalter** [comment] 2015-01-14 08:00
@dchem Could you check if this is fixed for you with Cockpit from the following COPR?

https://copr.fedoraproject.org/coprs/sgallagh/cockpit-preview/

**Comment by dchem** [comment] 2015-01-16 21:01
@stefwalter Will do. Thanks.

**Comment by dchem** [comment] 2015-01-27 06:08
@stefwalter Sorry about late reply, I tried using the linked COPR and it works as intended. I see terminal output for other machines.

**Comment by stefwalter** [comment] 2015-01-27 06:10
Great. Good to hear. Closing.

**Closed by stefwalter** 2015-01-27 06:10 UTC
Labels: needinfo
