### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by jfha73** [cockpit-project/cockpit#2434] opened 2015-06-17 13:16 UTC
Can you please add the ability to configure services, like configure Apache, FTP, SSH, etc. to your product?

Also, I have been testing it with Fedora Server 21 and every time a change is made I have to re-login to be able to see anything, in other words, after changes are made, it won't show anything, not a plain white screen,but it's like if the server had nothing on it.

**Comment by stefwalter** [comment] 2015-06-17 13:39
> Can you please add the ability to configure services, like configure Apache, FTP, SSH, etc. to your product?

Cockpit isn't a product. But I think that rolekit in Fedora (for example) is the kind of "configure a service" infrastructure that you're talking about. @sgallagher and @petervo would know more about the status of that work.

That's tracked in issue #1625

> Also, I have been testing it with Fedora Server 21 and every time a change is made I have to re-login to be able to see anything, in other words, after changes are made, it won't show anything, not a plain white screen,but it's like if the server had nothing on it.

That's expected, you shouldn't change files in /usr/share/cockpit for a running server. See:

https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#making-changes-in-the-ui-code

And for more detailed documentation:

http://files.cockpit-project.org/guide/packages.html

**Comment by stefwalter** [comment] 2015-06-17 13:39
Closed as a duplicate of #1625

**Closed by stefwalter** 2015-06-17 13:39 UTC
