### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20056] opened 2024-02-19 02:19 UTC
Tests failed on 1d801796e1e616cf648953756971a26cbee65bea, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240219-012502-1d801796-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2024-02-19 03:25
Duplicate of #20053

**Closed by martinpitt** 2024-02-19 03:25 UTC
Labels: nightly
