### ISSUE TITLE
accounts: Add user to group

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14746] opened 2020-10-14 12:09 UTC
Currently, account pages have the ability to promote someone to an admin. However, they do not have any group addition/removal features.

(While this is about the user to group mapping, it is different from group editing, in #14745, as this refers to the existing account page.)

**Comment by marusak** [comment] 2020-10-14 12:33
Kind of duplicate of #5762

**Comment by garrett** [comment] 2020-10-14 12:35
If there's a container administration group, as suggested in #2975 (which mainly relates to adding someone to a group at creation time), someone would also be able to add the person on the account page.

We probably want a few predefined groups as well as custom groups.

- admin (which is really the wheel group)
- containers (libvirt group?)
- any groups that have other users in the group already — basically those that match `grep -v ":\$" /etc/group` aside from user groups (those that start and end with the username, such as `garrett:x:1000:garrett`)

And then probably a custom field, which would probably be a [multiple typehead select](https://www.patternfly.org/v4/components/select/react/#multiple).

**Comment by garrett** [comment] 2020-10-14 12:36
@marusak: Ah, kind of. That's sort of a meta-bug though? I didn't see it when searching. Thanks for linking it in!

**Comment by marusak** [comment] 2022-12-15 07:50
This has been fixed in https://github.com/cockpit-project/cockpit/pull/17996

**Closed by marusak** 2022-12-15 07:50 UTC
Labels: enhancement, page:users, review-2022-12
