### ISSUE TITLE
Support SSH agent forwarding

### ISSUE THREAD

**Issue by x11x** [cockpit-project/cockpit#11000] opened 2019-01-18 06:28 UTC
I have read #8103 and understand that the browser can't support forwarding.
However, I would like to use a key that has been forwarded to my server's ssh-agent through a separate ssh connection (made by e.g. putty or ssh client).
In other words, say for example a server running the cockpit-ws on example.com. I run from my local machine `ssh -A user@example.com` and the key from my local agent is loaded into example.com's ssh-agent. I would like cockpit to then use that key to then connect to other hosts. I can do this by running `ssh -A otherhost.example.com`  inside an ssh session on `example.com`.
Is this possible? Maybe an obscure use case, but I like the approach of the key never leaving my local machine - and if I need to access another machine through cockpit, I can agent forward to the primary host and from there connect to the other machines.
Also, it is sometimes handy to do an ssh tunnel (`ssh -L 9090:localhost:9090`) to access cockpit to save having to expose it over public HTTPS. Doing this, it is especially handy to also do agent forwarding while setting up the tunnel (i.e. `ssh -AL 9090:localhost:9090`).

**Comment by martinpitt** [comment] 2019-01-18 07:39
In principle it is possible for the bridge to check some well-known paths for existing ssh-agents, and if it finds these, use these instead of starting  its own. E. g. gnome-keyring starts ssh-agent at the well-known path `$XDG_RUNTIME_DIR/keyring/.ssh`. 

The problem is that `ssh -A` does not do this, it sets an `$SSH_AUTH_SOCK` that is an unpredictable path. So other processes outside of the session that created that agent have no access to this.

On a test server I also get a `$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh` by default when logging in (I don't know what process  creates that, though), but it doesn't actually work.

So we could add looking for `$XDG_RUNTIME_DIR/keyring/.ssh`, but this will only work for the very special case that you Cockpit-login to a machine that runs a GNOME session. This is a corner case only. What would really be useful is for `ssh -A` to start using and preferring `$XDG_RUNTIME_DIR` and use a predictable socket location, which can then be easily be shared between multiple ssh logins, graphical, and Cockpit sessions.

**Comment by x11x** [comment] 2019-01-19 00:12
Thanks for your detailed reply, I don't know much about ssh agents.
That makes sense.
If cockpit could check some well known paths, a workaround for my use case could be something like
`ssh -A user@example.com 'ln -sT "$SSH_AUTH_SOCK" "$XDG_RUNTIME_DIR/keyring/.ssh"'. (I also would probably want to implement cleaning up the symlink at the end of the session).
I wonder why ssh uses an unpredictable path... possible a security measure to prevent other sessions from getting access to ssh-agents? But if permissions are set properly and assuming UIDs are not shared between different users of the server, there should be no problem with having an agent socket at a known location, right?
I probably need to research ssh-agents a bit more.

**Comment by martinpitt** [comment] 2019-01-19 09:00
> I wonder why ssh uses an unpredictable path

That's simply a historic thing. Back in the days when ssh-agent got created, the usual approach was to create a temporary dir and point and env variable to that. This was before we had a /run directory and `XDG_RUNTIME_DIR`, and systemd user instances, all of which make sharing such services between parallel sessions of the same user much simpler.

Indeed it's not literally the location that is secret, the temp dir approach was just taken to safely create a dir in the world-writable /tmp. XDG_RUNTIME_DIR does not have that problem. Thus, as you say, permissions are sufficient to protect the socket.

**Comment by martinpitt** [comment] 2021-04-21 17:06
This has been blocked for over two years on ssh-agent not using XDG directories. Closing for now to clean up our bug list. We can reopen this once SSH supports this case.

**Closed by martinpitt** 2021-04-21 17:06 UTC
Labels: blocked, enhancement, review-2021-02
