### ISSUE TITLE
Request: Resizable Terminal.

### ISSUE THREAD

**Issue by Tux-box1** [cockpit-project/cockpit#6205] opened 2017-03-25 01:10 UTC
I was toying around with it, but it would be great to add something like  the css3 property of "resize: both; overflow: auto;" to the terminal view. It's too small currently and I usually go in and edit via browser the code. It would be nice to ether supply a different default size or allow us to resize it in the window.

**Comment by andreasn** [comment] 2017-04-04 12:44
This seems like a duplicate of #4633

**Closed by andreasn** 2017-04-04 12:44 UTC
