### ISSUE TITLE
Memory leak with SSH sessions

### ISSUE THREAD

**Issue by jciesla** [cockpit-project/cockpit#15681] opened 2021-04-12 16:04 UTC
Hello,

I currently have an important memory leak issue with cockpit-bridge.

After a long time trying to find the cause of the leak, I found a way to reproduce the issue simply :

First, open an SSH session with putty on the target machine, this session will be used to monitor the issue.
There after, login to cockpit as a standard user with privileges enabled, and stay at the overview page.
On the putty console, note the PID of cockpits processes with "ps -aux | grep cockpit", and supervise the cockpit-process associated with user root with "ps -p 11772".

![image](https://user-images.githubusercontent.com/11711472/114435248-f5b86e00-9b91-11eb-89d6-5448720d158f.png)

![image](https://user-images.githubusercontent.com/11711472/114435288-00730300-9b92-11eb-8a44-fc4fef5bc765.png)

Now, open another new putty session, and see the result on the first putty session used to monitor cockpit-bridge. You will see that cockpit-bridge RES value uses more memory and never free it. You can close the last putty session, and reopen a new one, and each time, new session produce a new memory usage in the cockpit-bridge.

In my case, I have a remote rsync connection using SSH, on each 15 sec. The leak I have on my side is around 3-4MB/min.

I'm not sure why cockpit-bridge leak each time another ssh session is opened, do you have any idea?

Thank you very much!!

Julien

**Comment by martinpitt** [comment] 2021-08-07 13:56
Duplicate of issue #13689.

Is this still happening to you with current versions? Any chance I could get SSH access to investigate this?

**Closed by martinpitt** 2021-08-07 13:56 UTC

**Comment by jciesla** [comment] 2021-08-09 18:32
Hello Martin, I tested with build 250 and it still present. I can send you the virtual appliance if you want to reproduce on your side. Let me know your preferred transfer method.
