### ISSUE TITLE
Tests failed on e46f7e022e13f2a984d25a3e189a5117bd1fe88a

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20581] opened 2024-06-13 02:30 UTC
The job `fedora-40/updates-testing` failed on commit e46f7e022e13f2a984d25a3e189a5117bd1fe88a.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-e46f7e02-20240613-012953-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-06-13 06:38
More SELinux.. Srsly, this needs to stop. I'll just consider this a duplicate of #20542

**Closed by martinpitt** 2024-06-13 06:38 UTC
Labels: nightly
