### ISSUE TITLE
Cockpit could not contact the given host

### ISSUE THREAD

**Issue by KRDucky** [cockpit-project/cockpit#4138] opened 2016-04-01 22:48 UTC
I have cockpit setup and connected to one remote host just fine. But as soon as I try to add another remote host that is this time sitting on ssh port 2222, it says "Cockpit could not contact the given host."
I can ssh into the given host just fine from cockpit. But I can not add the machine.
I even did the username@ipaddress:2222 and nothing works. I am on version 0.96. I thought this was supposed to be fixed as of 0.85?

**Comment by KRDucky** [comment] 2016-04-01 22:50
I have 3 more machines to add to the server too. The machines are setup to use ssh ports 2222, 2221, 2223, 2224.

I really wish I could add these machines via CLI since I can ssh into them just fine from CLI.

**Comment by petervo** [comment] 2016-04-01 23:25
@KRDucky adding machines with non-standard ports should work and is part of cockpit's tests. The correct format is ip.or.domain:2222.

If that isn't working make sure you connectivity between the two server and can ssh into those machines from the primary server. For example if in your browser you are connected to 10.0.0.1 ssh into that machine and then try to ssh into the next one from there.

If that doesn't work there may be hints in the logs, are there any error either in the journal or the browser console?

**Comment by stefwalter** [comment] 2016-11-30 10:23
Haven't received a response back from reporter. Closing the bug.

**Closed by stefwalter** 2016-11-30 10:23 UTC
Labels: question

**Comment by lexzz** [comment] 2017-02-06 17:44
I'm having the same problem. My ssh is running on a non-standard port. I can connect to it using the ssh command with the alternative port. 

I hope someone can help!

**Comment by stefwalter** [comment] 2017-02-06 18:13
@lexzz What is the non-standard port you're trying to use? Please include information and/or screenshots.

**Comment by petervo** [comment] 2017-02-07 15:21
@lexzz most of the reports we've gotten of this failing has been because of selinux. I'd suggest checking the journal for those messages.

**Comment by strongpapazola** [comment] 2020-05-12 05:40
just add server with <address_server>:<port_ssh>

**Comment by MestreLion** [comment] 2021-04-04 06:30
I have the same issue: `ssh MYUSER@MYSERVER -p PORT` works fine, authenticating via keypair. Actually, `ssh ALIAS` works too, as I've configured it in my `~/.ssh/config`. I don't think the problem is the port, in cockpit if I change `MYSERVER:PORT` to another port it takes a few seconds to fail (timeout?), as opposed to using the correct (custom) port where it fails immediately.

I've also made sure my SSH key in Authentication is ON and Unlocked. Maybe the issue is the custom user? Does cockpit accepts `MYUSER@MYSERVER:PORT` notation? Or does it require/assume SSH is connecting to root account? root SSH access is disabled in my server, but I don't mind monitoring it as an un-priviledged user. At least to get Mem/CPU/etc usage.
