### ISSUE TITLE
GPG signature verification error: Bad GPG signature

### ISSUE THREAD

**Issue by jomapps** [cockpit-project/cockpit#17857] opened 2022-10-28 14:59 UTC
### Explain what happens

1. Open Cockpit Dasboard
2. Go to Software updates

I get error cannot update repo 'rspamd-experimental': repomd.xml GPG signature verification error: Bad GPG signature

I am on Cloudlinux 8
Running Directadmin

 When I do dnf update, I get no error
I even did this:
$ sudo rpm -e gpg-pubkey-f796ecb0
$ sudo dnf clean all
$ sudo rm -rf /var/cache/dnf/*
$ sudo rm /var/cache/dnf/.gpgkeyschecked.yum
$ sudo dnf update

The system does not seem to have an error but still cockpit is reporting it.

### Version of Cockpit

264.2

### Where is the problem in Cockpit?

Software updates

### Server operating system version

CloudLinux 8.6

### What browsers are you using?

Chrome

**Comment by garrett** [comment] 2022-11-02 10:29
_(Note: CloudLinux 8.6 is a RHEL 8.6 rebuild.)_

Cockpit uses PackageKit as a backend, which uses dnf on RHEL-based distributions.

What happens if you use pkcon from the command line? (And don't accept it)

```sh
pkcon refresh && pkcon update
```

And then what happens when you run `dnf update` from the command line?

**Comment by jomapps** [comment] 2022-11-03 05:32
Thanks for the reply.
When I did
`pkcon refresh && pkcon update`
it gave
`Fatal error: cannot update repo 'rspamd-experimental': repomd.xml GPG signature verification error: Bad GPG signature`
and `dnf update` resulted into `Nothing to do. Complete!`

**Comment by garrett** [comment] 2022-12-08 09:31
Apologies for taking a while to get back to you.

Right, the problem is not with Cockpit, but with the GPG signature for the `rspamd-experimental` distro. You need to very the key is the correct one, or perhaps remove the repo and re-add it with the instructions @ https://rspamd.com/downloads.html

They do mention importing the GPG key there... perhaps it changed?

You might want to consider contacting the rspamd project. There are some GPG issues (both a couple open, but also several closed) which are probably related to your issue. 

https://github.com/rspamd/rspamd/issues?q=is%3Aissue+gpg

I see some about RHEL9-based distributions, but don't see any recent ones about 8... but I'd think it's probably similar.

https://github.com/rspamd/rspamd/issues/4215

As this is a problem with the repo and your system's configuration and Cockpit shows and the error and can't really fix it itself, then I think we can close this issue.

Hopefully my explanation explains clearly enough what you need to do, if you haven't done so already.

**Closed by garrett** 2022-12-08 09:31 UTC
Labels: bug

**Comment by markus-96** [comment] 2022-12-30 14:47
If someone else is still encountering the same problem, here is what is working for me:

Edit `/etc/yum.repos.d/rspamd.repo`, the line where the `gpgkey` is defined:
```
[rspamd]
name=Rspamd stable repository
baseurl=http://rspamd.com/rpm-stable/centos-8/x86_64/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://rspamd.com/rpm-stable/gpg.key
```
