### ISSUE TITLE
Differentiating top horizontal menu/tabs from left-side vertical menu

### ISSUE THREAD

**Issue by jeffvance** [cockpit-project/cockpit#2251] opened 2015-05-06 02:07 UTC
When demoing cockpit to a co-worker I was unable to explain why, when I select a remote server and then click "Dashboard" or "Cluster" in the top menu bar, the server under view is changed to the cockpit host. The change in server-being-shown is somewhat subtle since there is no title/heading containing the name of the server being viewed -- what you see is the top-left machine drop-down shows "Machines" rather than the remote server name.

The same issue also applies when viewing a remote server and then clicking "Cluster" on the top menu bar. The swich from the remote to the host server is not overly obvious, especially if both the host and remote have k8 running.

As a side note: one could view the top menu bar as holding short-cuts that present a particular view. So, regardless of which server you are monitoring in cockpit, clicking an item in the top menu switches your context to that defined by the "short-cut". In the current implementation (as seen from this perspective), the existing top-menu "short-cuts" changes context to the host server and presents the views defined by their label. If this analogy is reasonable (and I looked at wiki pages and other docs to try to understand the current design better, but I missed finding it), then perhaps the top menu-bar could hold any "short-cut" dropped on it. For example, if the user was viewing remote server "foo" and she drags a left-side menu tab and drops it onto the top menu-bar, then that could be a short-cut to her current view.... Thoughts? 

Also I don't know if creating a new issue is the correct/desired way to present questions and/or suggestions.

**Comment by stefwalter** [comment] 2015-05-07 07:49
I'm not sure I understand.

Both 'Dashboard' and 'Cluster' show an overview of multiple hosts, not a single server. So you're not changing the server, but viewing information about N servers. 

You cannot view the 'Dashboard' or 'Cluster' of one server in particular. But you do see these dashboards from the point of view of the server you connected to. That's by design.

**Comment by jeffvance** [comment] 2015-05-08 02:53
>'Dashboard' and 'Cluster' show an overview of multiple hosts, not a single server
I have cockpit running on my laptop with 3 f21 VMs added as remote servers. F21-1 is a functioning kube master. When I click "Cluster" I see nothing related to k8 on the f21-1 remote server. Should I?
![screenshot from 2015-05-07 19 53 08](https://cloud.githubusercontent.com/assets/3076896/7529791/c43a6f8c-f4f2-11e4-9171-0738ee5a0088.png)

**Comment by stefwalter** [comment] 2015-05-08 05:17
Until we get into features around Kubernetes configuration and setup, I would say "no".

**Comment by stefwalter** [comment] 2015-12-01 07:27
Closing this bug. We're continuing to refine the UI, and the patternfly team is working on further navigation enhancements to the sidebar.

**Closed by stefwalter** 2015-12-01 07:27 UTC
