### ISSUE TITLE
Storage Page reporting only 0% progress on RAID5 growth.

### ISSUE THREAD

**Issue by KillerLink** [cockpit-project/cockpit#13892] opened 2020-04-12 00:48 UTC
Cockpit version: 216
OS: Fedora 31 Server
Page: Storage

When growing a raid with `mdadm --grow`, the storage page shows that _something_ is in progress for a raid device but the percentage stays at 0% while there actually is progress that can be shown by `cat /proc/mdstat`. Clicking on the raid device (for details) has the same behaviour (percentage stays at 0%). I assume that output of `cat /proc/mdstat` might be parsed/filtered but looks different because it is not a resync but a reshape.

Steps to Reproduce:
1. Have an existing RAID5 (in my case consisting of 4 partitions, 16GB each)
2. Add a new disk to it: `mdadm --add /dev/md1 /dev/sdf3`
3. Grow it: `mdadm --grow --raid-devices=5 /dev/md1`
4. Check that the operation is in progress and note that there is a progress different from 0%: `cat /proc/mdstat`
5. On the Cockpits' storage page, notice that the operation is recognized but the progress is always 0% until operation is finished.

Happy to provide any necessary or helpful additional information on request.

**Comment by martinpitt** [comment] 2021-02-28 08:14
Duplicate of #12918

**Closed by martinpitt** 2021-02-28 08:14 UTC
Labels: review-2021-02
