### ISSUE TITLE
Tests failed on 6a4d5e5a076b347a15430b209f386951dcc24841

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21054] opened 2024-09-30 03:09 UTC
The job `fedora-40/updates-testing` failed on commit 6a4d5e5a076b347a15430b209f386951dcc24841.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6a4d5e5a-20240930-013136-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-09-30 05:00
Duplicate of #21048

**Closed by martinpitt** 2024-09-30 05:00 UTC
Labels: nightly
