### ISSUE TITLE
Tests failed on 1f14cc1f0656f4cc49782b3617c8a14099e5cfd1

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21329] opened 2024-11-26 02:28 UTC
The job `fedora-40/updates-testing` failed on commit 1f14cc1f0656f4cc49782b3617c8a14099e5cfd1.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-1f14cc1f-20241126-013145-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-26 06:09
Duplicate of #21301

**Closed by martinpitt** 2024-11-26 06:09 UTC
Labels: nightly
