### ISSUE TITLE
Lag on terminal with new theme

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#11369] opened 2019-03-12 02:24 UTC
Cockpit version: 189
OS: Centos 7
Page: System/Teminal

Lag on input/output on terminal with new themes enabled

Steps to reproduce

1. Try to run vi from the System/Terminal tool and it takes along time to load, compared to version 187.
2. Try running htop command on the  System/Terminal tool refresh is slow compared to version 187.
3. When running htop command on the  System/Terminal tool , output becomes corrupted and there are blank lines in the middle of the output.

Is there a way to disable the themes?

<img width="1330" alt="bad_htop" src="https://user-images.githubusercontent.com/2557898/54170236-85cbdc80-443b-11e9-98e8-c8896c77669e.png">

**Comment by PeterFalken** [comment] 2019-03-12 02:29
The terminal get more out of sync if you let it run over time, this makes monitoring with htop over time a bit unusable.
<img width="1330" alt="bad_htop2" src="https://user-images.githubusercontent.com/2557898/54170450-608b9e00-443c-11e9-9307-903740eed304.png">

**Comment by martinpitt** [comment] 2019-03-12 06:44
Duplicate of issue #11343 . It's not really the themes themselves, it's the underlying XTerm.js.

**Closed by martinpitt** 2019-03-12 06:44 UTC

**Comment by marusak** [comment] 2019-03-12 08:49
Slowness is same cause as described in #11343
I cannot reproduce blank lines. Is it possible you resized window during htop running?
