### ISSUE TITLE
Login history wrong login ip

### ISSUE THREAD

**Issue by onlineapps-cloud** [cockpit-project/cockpit#20895] opened 2024-08-16 18:53 UTC
### Explain what happens

Hi, login ip is different, i don't see who and from which ip was login.
![image](https://github.com/user-attachments/assets/dc441ccb-e752-400d-8929-9c816c6c6f6e)
![image](https://github.com/user-attachments/assets/5ecb3c6f-ae31-4ffd-9fd2-32c3a54daf58)

### Version of Cockpit

287.1-0+deb12u2

### Where is the problem in Cockpit?

Logs

### Server operating system

Debian

### Server operating system version

12

### What browsers are you using?

Firefox

**Comment by jelly** [comment] 2024-08-19 07:59
Is cockpit behind a reverse proxy such as nginx?

**Comment by onlineapps-cloud** [comment] 2024-08-19 08:22
no, cockpit is installed using apt install cockpit

**Comment by leomoty** [comment] 2024-08-22 13:49
This is the same as #16774

**Comment by onlineapps-cloud** [comment] 2024-08-22 18:30
yes, this is same issue

**Comment by martinpitt** [comment] 2024-08-23 03:59
Thanks, closing as duplicate of #16774 then.

**Closed by martinpitt** 2024-08-23 03:59 UTC
Labels: bug

**Comment by martinpitt** [comment] 2024-12-10 10:31
Fixed in PR #21418.
