### ISSUE TITLE
when I go to cockpit/logs my cpu goes to 100% any advice?

### ISSUE THREAD

**Issue by Marcin-Kozyra** [cockpit-project/cockpit#13332] opened 2019-12-22 21:17 UTC
cockpit-208-1.fc31.x86_64
cockpit-bridge-208-1.fc31.x86_64
OS:Fedora server 31

When I go to cockpit/logs cpu goes to 100%

cockpit-bridge[2014]: org.freedesktop.problems: couldn't get all properties of org.freedesktop.Problems2.Entry at /org/freedesktop/Problems2/Entry/0dd184d5ef42b2dfe4edd46cdeaccd786eb0f47f: Timeout was reached

top shows abrt-dbus and cockpit-bridge high cpu usages.

[root@mail ~]# abrt-cli list
Traceback (most recent call last):
  File "/usr/bin/abrt-cli", line 40, in <module>
    namespace.func(namespace)
  File "/usr/lib/python3.7/site-packages/abrtcli/cli/list.py", line 27, in run
    not_reported=arguments.not_reported)
  File "/usr/lib/python3.7/site-packages/abrtcli/match.py", line 72, in match_lookup
    problems = problem.list(auth=authenticate)
  File "/usr/lib64/python3.7/site-packages/problem/__init__.py", line 356, in list
    return [tools.problemify(prob, __proxy) for prob in fun()]
  File "/usr/lib64/python3.7/site-packages/problem/proxies.py", line 91, in list
    return [str(prob) for prob in self._dbus_call('GetProblems')]
  File "/usr/lib64/python3.7/site-packages/problem/proxies.py", line 53, in _dbus_call
    return getattr(self._iface, fun_name)(*args)
  File "/usr/lib64/python3.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by Marcin-Kozyra** [comment] 2019-12-23 00:05
top shows abrt-dbus and cockpit-bridge high cpu usages.

**Comment by marusak** [comment] 2020-01-02 14:11
@ernestask Could you please take a look?

**Comment by ernestask** [comment] 2020-01-02 15:06
An equivalent bug was filed on our side as well. I’ll get to it eventually.

**Comment by ernestask** [comment] 2020-01-20 13:31
The issue is reproducible with a large number (1000+) of problem directories present. There’s no immediate solution for improving performance there, as it’s not limited to the D-Bus interfaces.

**Comment by ernestask** [comment] 2020-01-21 11:12
Filed https://github.com/abrt/abrt/issues/1433 for the underlying issues. This can probably be closed as well now (like https://bugzilla.redhat.com/show_bug.cgi?id=1786381).

**Closed** 2021-02-19 10:39 UTC
Labels: review-2021-02
