### ISSUE TITLE
Tests failed on f2cc9e1a360e69dc55b8f9f26f367eb4c17ecb5b

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20239] opened 2024-03-30 02:24 UTC
The job `fedora-39/updates-testing` failed on commit f2cc9e1a360e69dc55b8f9f26f367eb4c17ecb5b.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f2cc9e1a-20240330-012240-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-04-01 08:49
Duplicate of #20242

**Closed by martinpitt** 2024-04-01 08:49 UTC
Labels: nightly
