### ISSUE TITLE
Docker volumes in Cockpit

### ISSUE THREAD

**Issue by williamjmorenor** [cockpit-project/cockpit#1666] opened 2015-01-15 22:32 UTC
Hi

It could be good to be able to configure volumenes when one container run from Cockpit, I can configure the container name, the memory and CPU limits, and the ports, but I can not configure a volume, for example if I would like to mount the bata base folder of a container to the host for easily backup data.

You can add a data volume to a container using the -v flag with the docker run command. You can use the -v multiple times in a single docker run to mount multiple data volumes. Let's mount a single volume now in our web application container.

$ sudo docker run -d -P --name web -v /webapp training/webapp python app.py

In addition to creating a volume using the -v flag you can also mount a directory from your own host into a container.

$ sudo docker run -d -P --name web -v /src/webapp:/opt/webapp training/webapp python app.py

Another useful function we can perform with volumes is use them for backups, restores or migrations. We do this by using the --volumes-from flag to create a new container that mounts that volume, like so:

$ sudo docker run --volumes-from dbdata -v $(pwd):/backup ubuntu tar cvf /backup/backup.tar /dbdata

**Comment by andreasn** [comment] 2015-01-15 23:28
Closing due to duplicate of #1451

**Closed by andreasn** 2015-01-15 23:28 UTC
