### ISSUE TITLE
machines: Failed to delete the vm disk images as expected on Confirm deletion dialog

### ISSUE THREAD

**Issue by AlertBear** [cockpit-project/cockpit#8499] opened 2018-01-26 08:49 UTC
Description of problem:
Failed to delete the vm disk images as expected on Confirm deletion dialog

Version-Release number of selected component (if applicable):
cockpit-machines-159-1.el7.x86_64
cockpit-bridge-159-1.el7.x86_64
cockpit-ws-159-1.el7.x86_64
cockpit-system-159-1.el7.noarch
cockpit-159-1.el7.x86_64
RHEL-7.5-20180116.0
libvirt-3.9.0-7.el7.x86_64

How reproducible:
100%

Steps to Reproduce:
1. Install cockpit-machines package
2. Create a vm via libvirt with a disk(vm.qcow2), the vm can be shown on cockpit-machines page
3. Click the delete button
4. On confirm dialog, choose to delete associated storage files including disk image(vm.qcow2)

Actual results:
1.After step#4, the disk image(vm.qcow2) is not deleted, still exists on the host

Expected results:
1. After step#4, the disk image(vm.qcow2) is deleted as the operation

**Comment by qiyuann** [comment] 2018-04-26 06:58
The exact steps are:
1. create vm.qcow2 under /var/lib/libvirt/images using `qemu-img create -f qcow2 vm.qcow2 10G` 
2. create vm.xml with:
```
<disk type="file" device="disk">
    <driver name="qemu" type="qcow2" />
    <source file="/var/lib/libvirt/images/vm.qcow2" />
    <target dev="hdb" bus="ide" />
</disk>
```
3. create vm by `virsh define vm.xml`
4. try to delete the vm created in step3 on virtual machines page, and select to delete vm.qcow2 at the same time:

![screenshot from 2018-04-26 14-39-25](https://user-images.githubusercontent.com/23047456/39289993-a7870f88-4960-11e8-8abd-e7b378fbf644.png)

5. check /var/lib/libvirt/images, vm.qcow2 is still there

**Comment by mareklibra** [comment] 2018-04-30 09:33
The issue is in adding a disk which is not managed by libvirt:
```
# virsh undefine vm2 --managed-save --storage "hda,hdb"
error: Storage volume 'hdb'(/var/lib/libvirt/images/vm2_extra.qcow2) is not managed by libvirt. Remove it manually.

Domain vm2 has been undefined
Volume 'hda'(/var/lib/libvirt/images/vm2.qcow2) removed.
```

The `hdb` is added as described in previous comment.

IMO, it makes sense to cover even this flow, so if disk source file is known, we can attempt to `rm` it.

**Comment by mareklibra** [comment] 2018-05-02 09:30
Based on discussion in #9073 PR, we will recently not delete non-libvirt managed disks. If a disk was created using other tooling within different flows, it should be removed consistently. If still needed, I would move this feature to potential  (recently non-existing) file-manager in Cockpit.

Anyway, the additional storage can be added via:
```
virsh vol-create-as [POOL_NAME] [DISK_NAME] --capacity [NUMBER]G --format qcow2
```

To get list of pools:
```
virsh pool-list
```

@AlertBear , can you please confirm the disk can be deleted when created this way?

**Comment by mareklibra** [comment] 2018-05-02 09:30
The `pkg/machines` should be improved for `Add Disk` feature, tracked in #9081.

**Comment by qiyuann** [comment] 2018-05-03 08:32
@mareklibra , I tried your suggestion to create the storage via `virsh vol-create-as`,  the disk can be deleted.

**Comment by mareklibra** [comment] 2018-05-03 09:08
@qiyuann , thanks, so closing the issue.

**Closed by mareklibra** 2018-05-03 09:08 UTC
