### ISSUE TITLE
Tests failed on 7707c193196a49f59aab53e203d8ae4f13dff36b

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21143] opened 2024-10-21 02:30 UTC
The job `fedora-40/updates-testing` failed on commit 7707c193196a49f59aab53e203d8ae4f13dff36b.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-7707c193-20241021-013147-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-21 05:26
Duplicate of #21137

**Closed by martinpitt** 2024-10-21 05:26 UTC
Labels: nightly
