### ISSUE TITLE
Tests failed on 07fd7c2d8bdfd576929d33ae99e0a5522860c953

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20494] opened 2024-05-22 02:26 UTC
The job `fedora-40/updates-testing` failed on commit 07fd7c2d8bdfd576929d33ae99e0a5522860c953.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-07fd7c2d-20240522-012820-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-05-22 04:45
Duplicate of #20488

**Closed by martinpitt** 2024-05-22 04:45 UTC
Labels: nightly
