### ISSUE TITLE
Nightly tests did not succeed on fedora-38/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19480] opened 2023-10-14 02:19 UTC
Tests failed on b86c8df46fa9cb023087ab6c9c42bd3fdf38bcd4, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231014-012329-b86c8df4-fedora-38-daily//log.html)

**Comment by martinpitt** [comment] 2023-10-14 05:45
dupe of #19445

**Closed by martinpitt** 2023-10-14 05:45 UTC
Labels: nightly
