### ISSUE TITLE
Tests failed on 9601aee69e8606957fcd17091d60107cedfdf576

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21252] opened 2024-11-12 02:27 UTC
The job `fedora-40/updates-testing` failed on commit 9601aee69e8606957fcd17091d60107cedfdf576.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-9601aee6-20241112-013141-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-12 06:10
Duplicate of #21237

**Closed by martinpitt** 2024-11-12 06:10 UTC
Labels: nightly
