### ISSUE TITLE
Unhelpful message when trying to restart system as unprivileged user

### ISSUE THREAD

**Issue by miabbott** [cockpit-project/cockpit#3630] opened 2016-01-28 21:52 UTC
I was running the `cockpit\ws` (ID 28020add5c9a) container on Fedora Atomic 23 and was toying with logging with different users.

When I was logged in with an unprivileged user, I attempted to use `Restart` from the `Power Options` menu.  After clicking the red `Restart` button, I received an error message:  `not found`

![not found error message](http://i.imgur.com/q2D2iWK.png)

The system did not restart, but I think that error message could be improved.

**Comment by andreasn** [comment] 2016-01-29 10:45
The unprivileged user is not allowed to restart the system at all right?
If so, we should gray out the Restart button on the dashboard already, so that a person who wants but can't reboot a system doesn't waste time on carefully crafting a restart message.

**Comment by miabbott** [comment] 2016-01-29 14:14
From the command line as an unprivileged user, if I use `systemctl reboot` I get prompted to authenticate for `sudo` access.

So it is possible that an unprivileged user could elevate their privileges to be able to reboot the system.

However, I think in most cases, it would be a safe option to gray out the Restart button.

**Comment by petervo** [comment] 2017-05-01 15:29
Duplicate of #5022

**Closed by petervo** 2017-05-01 15:29 UTC
Labels: starter
