### ISSUE TITLE
Image refresh for openshift

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#6598] opened 2017-05-18 13:59 UTC
Image creation for openshift in process on cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-openshift-2017-05-18/

**Comment by cockpituous** [comment] 2017-05-18 14:12
Image creation aborted

**Comment by stefwalter** [comment] 2017-05-19 04:35
Duplicate of #6334 ... and fixing the os.unlink issue in another pull request.

**Closed by stefwalter** 2017-05-19 04:35 UTC
Labels: bot, image/openshift
