### ISSUE TITLE
flatpak can't be opened multiple times

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#21084] opened 2024-10-06 16:59 UTC
### Explain what happens

1. Start the flatpak and login to a server
2. Start the flatpak again to log into another server but
3. the second instance is opening as a second window to the already open one

Thus, I can't open sessions to multiple servers by opening multiple instances of cockpit client flatpak.

* Linux Mint 22

### Version of Cockpit

325

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Debian

### Server operating system version

Debian Bookworm

### What browsers are you using?

Firefox

**Comment by jelly** [comment] 2024-12-11 12:43
They share the same cockpit-ws so in that sense it makes sense, but this feels unexpected. Especially as we want to get rid of the hosts switcher, having the flatpak launch multiple instances feels like wanted behavior.

**Comment by jelly** [comment] 2024-12-11 13:58
Turns out this is a duplicate of https://github.com/cockpit-project/cockpit/issues/16673

**Closed by jelly** 2024-12-11 13:58 UTC
Labels: bug

**Comment by ne20002** [comment] 2024-12-20 08:16
> They share the same cockpit-ws so in that sense it makes sense, but this feels unexpected. Especially as we want to get rid of the hosts switcher, having the flatpak launch multiple instances feels like wanted behavior.

It's not only a wanted behaviour. It's a needed behaviour. For me the flatpak is simply not usable like this. The only option I see is to install cockpit on all machines and open the firewalls accordingly so I can at least use multiple browser tabs at the same time.
