### ISSUE TITLE
Cockpit UI: Integration of Granular Permissions through Polkit

### ISSUE THREAD

**Issue by kubiakszymonp** [cockpit-project/cockpit#19433] opened 2023-10-04 15:55 UTC
I'm reaching out to discuss an issue regarding the Cockpit UI and its interaction with Polkit for managing granular permissions. The detailed context of this query can be associated with issue [#17346](https://github.com/cockpit-project/cockpit/issues/17346).

At present, managing various settings through the Cockpit UI, requires superuser status. Some parts of UI are invisible if superuser.allowed is set to false. This behavior persists even if Polkit rules permit the user to perform the relevant actions.

Desired state will be to check if user has the ability to make this action through Polkit - if not logged as superuser. And then show or hide the UI parts respectively.

Is there anything being done currently about supporting Polkit on the frontend side?

Are there any plans on implementing it?

I have some ideas how to implement it on the UI side, using custom react hooks. Personally i think that this feature will be really useful and will make the UI more compatible with the backend.

Thanks in advance.

**Comment by martinpitt** [comment] 2023-11-13 07:46
Our team does not currently work on this. It's purely a capacity and priority issue -- we actually want this, but implementing it is a *lot* of work. Fortunately it can be done step by step. If you want to look into this, that'd be appreciated of course! Please contact us (Matrix, GitHub) first though, so that we can discuss and agree on an implementation strategy.

Closing as duplicate of #11033.

**Closed by martinpitt** 2023-11-13 07:46 UTC
Labels: enhancement
