### ISSUE TITLE
link from journal detail to service page?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1379] opened 2014-10-21 11:27 UTC
So I was having issues with mt-daapd today. It spit out a number of errors to the journal.
When looking at one of the journal entrys, I was wondering about the _current_ state of the service, like "is it actually running right now?"

In this case it would be handy with a link to the service in question.

**Comment by andreasn** [comment] 2015-01-19 15:43
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/journal/journal-links.png)

**Comment by andreasn** [comment] 2015-01-19 15:44
The link would go to the accompanying service page. The kernel doesn't have a service page, so nothing for that.

**Comment by martinpitt** [comment] 2019-01-10 16:35
Duplicate of #53

**Closed by martinpitt** 2019-01-10 16:35 UTC
Labels: good-first-issue, review-2019-01
