### ISSUE TITLE
Unable to turn on firewall toggle under networking

### ISSUE THREAD

**Issue by dbhol** [cockpit-project/cockpit#18747] opened 2023-05-02 22:52 UTC
### Explain what happens

1. When going into the Netwokring tab, the firewall toggle is off. When hovering over it, it says "you are not authorized to modify the firewall".

I am wondering if this has something to do with firewalld because when i went into console and typed firewalld, it was not installed. But when i do install it, i can no longer access the cockpit webpage interface.
The issue i am having seems similar to this but it did not make sense how i could fix it:
[https://github.com/cockpit-project/cockpit/issues/17660](url)

I could not see where "About Web Console" was in the interface in order to provide my version number

I have installed ubuntu server onto a VM using virtual box if this effects anything at all. And then accessing the interface via my host machine. 

### Version of Cockpit

I think the latest

### Where is the problem in Cockpit?

Firewall

### Server operating system

Ubuntu

### Server operating system version

22.04.2

### What browsers are you using?

Firefox

**Comment by KKoukiou** [comment] 2023-05-03 13:34
we run the following check to discover if the firewall is in readonly mode;
``` sh
$ pkcheck --action-id org.fedoraproject.FirewallD1.all --process $$ --allow-user-interaction
polkit\56temporary_authorization_id=tmpauthz0
polkit\56retains_authorization_after_challenge=true
```

This is after I run it on my local system.

What does this give on yours?

(The error message you see implies that firewall is in readonly mode)

**Comment by KKoukiou** [comment] 2023-05-05 15:51
Try passing allow-internal-agent option as well.

`$ pkcheck --action-id org.fedoraproject.FirewallD1.all --process $$ --allow-user-interaction --enable-internal-agent`

**Comment by dbhol** [comment] 2023-05-12 19:09
> Try passing --enable-internal-agent option as well.
> 
> `$ pkcheck --action-id org.fedoraproject.FirewallD1.all --process $$ --allow-user-interaction --enable-internal-agent`

This doesn't appear to have helped either unfortunately.
I think perhaps i need to revert back to the beggining on this for a moment.
Let's assume i have just installed ubuntu server 22.04 onto a fresh VM and installed cockpit with `sudo apt install cockpit -y`.
What would be the correct way for me to install and setup firewallD to corrently show up on the Networking tab?

**Comment by martinpitt** [comment] 2023-05-13 05:56
Thanks @dbhol : You  mention it works now, but we don't know the previous root cause. "Not authorized" sounds like a problem with the polkit configuration, but I'm afraid the evidence is gone now. Thus I close this now. If you run into this again, please speak up here, and we can continue to investigate.

**Closed by martinpitt** 2023-05-13 05:56 UTC
Labels: question, bug

**Comment by dbhol** [comment] 2023-05-13 18:52
> Thanks @dbhol : You mention it works now, but we don't know the previous root cause. "Not authorized" sounds like a problem with the polkit configuration, but I'm afraid the evidence is gone now. Thus I close this now. If you run into this again, please speak up here, and we can continue to investigate.

Well this issue seems to happen every time i install cockpit to Ubuntu server. I have been using this at work as well and the same issue seems to be present. So if there is anything else i can do to troubleshoot this issue to get a better understanding of what has happened incase this is an actual bug or if it's an issue that anyone else has in the future then i am happy to do more testing with another fresh instance of cockpit with guidance of what i can do to work out what is going on with the not authorized response. 

Let me know, and i will be happy to help further,

**Comment by martinpitt** [comment] 2023-05-14 06:10
@dbhol : That sounds like you can reproduce this? Can you write down an *exact* list of steps? What Ubuntu image you install, and how, how you create the user, how you install cockpit, what you do then. We test with the Ubuntu cloud image, and do pretty much what you describe: Install the cockpit and `firewalld` packages, then create an "admin" user with
```
# some cloud images have a pre-defined admin user or group, for them cloud-init admin creation fails    
userdel -r admin || true    
groupdel admin || true    
useradd -m -U -c Administrator -G sudo -s /bin/bash admin    
echo admin:foobar | chpasswd    
```

Then reboot the VM and log in as `admin`.

Your `pkcheck` commands above consistently failed with "Not authorized", which sounds like your user is not part of the `sudo` group?

**Comment by martinpitt** [comment] 2023-05-14 06:11
> EDIT AGAIN: I decided to do a reboot after running those commands as i had not done one. 

That might actually be the issue: Whatever you did before, e.g. add your user to the `sudo` group, did not affect the currently running shell.

**Comment by dbhol** [comment] 2023-05-20 15:13
@martinpitt see the following information
The Ubuntu server version i am using is 22.04.2.
It is being installed onto a virtual machine via virtualbox with the network being set up with the bridged adapter so i can access cockpit from my host machine
Installation process:
Language: English (UK)
Update to new installer
Keyboard layout: English (UK)
Base for the installation: Ubuntu Server
Network connections left as default
Proxy config left as none
Archive mirror left as default
Use entire disk: yes
Storage config left as default
The user profile i have just made a user called administrator
Ubuntu pro skipped for now
Install OpenSSH: Yes
Server snaps: none
Reboot now
COCKPIT INSTALL
sudo apt update
sudo apt install cockpit -y
sudo systemctl start cockpit
sudo systemctl status cockpit
sudo reboot now
navigate to the IP to check it's running
Networking tab does now have the firewall option showing
FIREWALLD INSTALL
From the VM terminal
sudo apt update
sudo apt install firewalld
sudo systemctl enable firewalld
sudo systemctl start firewalld
sudo firewall-cmd --state
sudo reboot now
sudo firewall-cmd --add-service=cockpit
sudo firewall-cmd --add-service=cockpit --permanent
sudo reboot now

This time i didn't do anything with the pkcheck commands anf the firewalld is working an enabled.
I think i have determined that my initial issue is that even though i installed firewalld, i never enabled and started it with the commands i listed above when i had the original problem because i never knew i needed to do that seeing as none of the online guides actually say to do this. I only found out about this because of a comment on a reddit post.

With regards to the not authorized issue, this still comes up with not authorized for me when i put those commands in. the administrator account i would have thought does have access to the sudo group seeing as i am able to run sudo commands from the terminal?

So my initial issue with firewalld not allowing me to toggle is fixed now. But i don't know about the pkcheck commands though
