### ISSUE TITLE
Tests failed on 6381e56492bfb89d8b8ca8b691e51b15b4f7603f

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21318] opened 2024-11-25 02:33 UTC
The job `fedora-40/daily` failed on commit 6381e56492bfb89d8b8ca8b691e51b15b4f7603f.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6381e564-20241125-013200-fedora-40-daily/log.html

**Comment by martinpitt** [comment] 2024-11-25 02:43
Duplicate of #21309

**Closed by martinpitt** 2024-11-25 02:43 UTC
Labels: nightly
