### ISSUE TITLE
Tests failed on b970f24ccb6c8a8f313287b2d972dba242465695

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20186] opened 2024-03-17 02:35 UTC
The job `fedora-39/updates-testing` failed on commit b970f24ccb6c8a8f313287b2d972dba242465695.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-b970f24c-20240317-012649-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-03-18 06:16
Duplicate of #20184

**Closed by martinpitt** 2024-03-18 06:16 UTC
Labels: nightly
