### ISSUE TITLE
Tests failed on a5c3cf2a025292494dec7d393418f8f92ba252f1

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21277] opened 2024-11-16 02:27 UTC
The job `fedora-40/updates-testing` failed on commit a5c3cf2a025292494dec7d393418f8f92ba252f1.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-a5c3cf2a-20241116-013128-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-16 13:44
Duplicate of #21237

**Closed by martinpitt** 2024-11-16 13:44 UTC
Labels: nightly
