### ISSUE TITLE
The tile on top left corner is better to be sth like "Import a Virtual Machine" on "Import VM" dialog

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit#13089] opened 2019-11-05 07:15 UTC
Cockpit version: cockpit-machines-205.1-1.fc30.noarch
OS: Fedora30
Browser: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
Page: Import VM

The tile on top left corner is better to be sth like "Import a Virtual Machine" on "Import VM" dialog, instead of "Create New Virtual Machine".

Steps to reproduce
1.Click Import VM
2.
3.
![screenshot-10 66 92 212_9090-2019 11 05-15_13_52](https://user-images.githubusercontent.com/12710195/68186416-0c42b900-ffdf-11e9-883c-60caa21110aa.png)

**Comment by marusak** [comment] 2019-11-05 08:16
Duplicate of https://github.com/cockpit-project/cockpit/issues/12614 (and there is also open PR for this)

**Closed by marusak** 2019-11-05 08:16 UTC
