### ISSUE TITLE
Unable to edit or remove a host if connection to it fails

### ISSUE THREAD

**Issue by terrywang** [cockpit-project/cockpit#14439] opened 2020-08-03 05:36 UTC
Cockpit version: `224-1.fc32`
OS: Fedora 32 x86_64

Page: 

Top Lef navigation (down arrow) - Hosts list - Edit Hosts

Issue Description

A Cockpit managed host's DNS name has changed from a `subdomain.domain.com` to EC2's public Hostname. Previously the host was added to Cockpit using the custom DNS name which does not exist any more (fails to resolve to public IP), causing connection error in cockpit UI.

However, connection error is NOT the problem, the real problem it's revealing is that **the left navigation panel UI seems to depend on a working (successful TCP/SSH connection to the managed host) to edit the IP/Host Name or remove it.**

When trying to edit the host in web UI, the `Host Name` part is greyed out. Unable to remove it by clicking the `-` icon either as it's greyed out.

> NOTE: I ended up recreating the A record in DNS infra to get rid of the host from Cockpit lol. In real world scenarios where cockpit is used at scale, and one does not have full control of their IT infrastructure, this is NOT considered a viable option.

Steps to reproduce

1. add a host to Cockpit using IP / DNS name
2. make the connection fail (anyway you like)
3. try to edit the host (host name / IP) or remove it

**Comment by terrywang** [comment] 2020-08-03 06:40
Update: it is possible to delete the host from Dashboard - Edit Server (the tick icon) - Delete button (trash bin) but not the left navigation panel  ;-)

**Comment by marusak** [comment] 2020-09-02 08:08
I believe that you are currently on the given host when you try to remove it.  In that case it is duplicate of https://github.com/cockpit-project/cockpit/issues/14150

**Closed by marusak** 2020-09-02 08:08 UTC
