### ISSUE TITLE
The System Screen claims to allow you to add NTP hosts, but the addition doesn't work correctly.

### ISSUE THREAD

**Issue by aaron-p-lehmann** [cockpit-project/cockpit#8621] opened 2018-02-14 21:05 UTC
Either the user should be able to set NTP servers via the page (preferred), or it he shouldn't be allowed to try.

To reproduce with Version 155:

* Log in to cockpit as root, go to the system page.
* Click on the time, Select Manual, and set it to some other time. The exclamation point will go away and the time will change
* Click on the time, note that the "Automatically from specific NTP Servers" is greyed out.
* Click on it anyway, you'll get a dialog for adding NTP servers.
* Add one and click Change. The time will not change, though the "not synced" exclamation point will return.
* Go back to the dialog where you add NTP servers. Note that the server you added is not there.

**Comment by martinpitt** [comment] 2019-01-17 16:47
I cannot reproduce this with the current version 185 any more. At your third step, the option is not greyed out, and switching back to NTP works properly. Thus I'm closing this now.

If it's still an issue for you, please reopen and we debug this here. Thanks!

**Comment by martinpitt** [comment] 2019-01-31 08:17
Ah, so this is on RHEL/CentOS presumably, where systemd-timesyncd does not exist? (Pointed out in #11088)

**Closed** 2019-01-31 13:31 UTC
