### ISSUE TITLE
Image refresh for centos-7

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#6344] opened 2017-04-15 06:01 UTC
Image creation for centos-7 in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-centos-7-2017-04-15/

**Comment by cockpituous** [comment] 2017-04-15 06:06
Image creation aborted

**Comment by martinpitt** [comment] 2017-04-15 08:03
dupe of #6346

**Closed by martinpitt** 2017-04-15 08:03 UTC
Labels: bot
