### ISSUE TITLE
Tests failed on 2d8821a5469e8009ae0b5af870d73e8766c89bc7

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20786] opened 2024-07-22 02:22 UTC
The job `fedora-40/daily` failed on commit 2d8821a5469e8009ae0b5af870d73e8766c89bc7.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2d8821a5-20240722-013036-fedora-40-daily/log.html

**Comment by martinpitt** [comment] 2024-07-22 03:16
Duplicate of #20786

**Closed by martinpitt** 2024-07-22 03:16 UTC
Labels: nightly
