### ISSUE TITLE
The user USERNAME is not permitted to start or stop services

### ISSUE THREAD

**Issue by yaspoon** [cockpit-project/cockpit#11929] opened 2019-05-27 02:17 UTC
Cockpit version: 194-1
OS: Arch Linux
Page: "Services"

I've followed https://cockpit-project.org/guide/latest/feature-systemd.html on adding a polkit rules file to allow an unprivileged user in a group to start and stop certain services. The user is able to start and stop the service from the command line `systemctl stop ark.service` but going to the services tab and trying to start/stop the ark.service is greyed out as the user.
![Screenshot from 2019-05-27 12-13-00](https://user-images.githubusercontent.com/807332/58391451-54959c80-8079-11e9-9eee-d2b628f1c69a.png)

Steps to reproduce

1. yaourt -S cockpit
2. add /etc/polkit-1/rules.d/60-servers.rules
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.systemd1.manage-units") {
        if (subject.isInGroup("srcds") && ((action.lookup("unit") == "7daystodie.service") || (action.lookup("unit") == "ark.service")))  {
            var verb = action.lookup("verb");
            if (verb == "start" || verb == "stop" || verb == "restart") {
                return polkit.Result.YES;
            }
        }
    }
});

3. systemctl daemon-reload
4. login to cockpit with user that is in srcds group
5. Attempting to start/stop 7daystodie.service or ark.service will not work as the buttons are greyed out
6. systemctl stop ark.service - works from commandline

Attached screenshot shows the issue

**Comment by yaspoon** [comment] 2019-05-27 02:22
Uploading polkit rules file as the formatting in the issue turned out awful.
[60-srcds.rules.txt](https://github.com/cockpit-project/cockpit/files/3221575/60-srcds.rules.txt)

**Comment by martinpitt** [comment] 2019-05-27 06:23
Confirmed. In pretty much all places we just test `cockpit.permission({ admin: true })` right now, which means "general sudo access, through the root bridge". But with fine-grained polkit permissions it doesn't need a root bridge, so for these situations the check needs to be extended. We do this (in a rather blunt way) in pkg/networkmanager/firewall-client.js, but this needs to be generalized.

**Comment by martinpitt** [comment] 2019-05-27 06:24
Note that the 
[polkit API](https://www.freedesktop.org/software/polkit/docs/latest/eggdbus-interface-org.freedesktop.PolicyKit1.Authority.html#eggdbus-method-org.freedesktop.PolicyKit1.Authority.CheckAuthorization) does not actually allow a caller to check if an action can be done with particular arguments. We can only check if the user is allowed to run `org.freedesktop.systemd1.manage-units` in general.

**Comment by KKoukiou** [comment] 2020-03-25 13:15
Duplicate of #13655

**Closed by KKoukiou** 2020-03-25 13:15 UTC
