### ISSUE TITLE
Use Tabs vs button bar consistently

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#674] opened 2014-06-11 12:48 UTC
Use Tabs vs button bar consistently when it comes to filtering vs. switching pages.

**Comment by dperpeet** [comment] 2015-12-01 08:25
Related to searching/filtering in services and logs - the only places where we still have the button bar filtering.

**Comment by martinpitt** [comment] 2019-01-11 07:55
Duplicate of #698

**Closed by martinpitt** 2019-01-11 07:55 UTC
