### ISSUE TITLE
failed PR tests create bogus "nightly run failed" issues for bots PRs

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20078] opened 2024-02-22 13:18 UTC
Tests failed on 25238599546457aec48f411ed1b0e1326c441f0b, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240222-124139-25238599-fedora-40-other-bots-5946/log.html)

**Comment by martinpitt** [comment] 2024-02-22 13:42
This is half of a duplicate of #20075, but slightly different: This test ran in https://github.com/cockpit-project/bots/pull/5946 as a "cross-project" test, while #20075 is a test inside of cockpit.git.

**Closed** 2024-02-22 13:58 UTC
Labels: nightly
