### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19693] opened 2023-12-05 02:27 UTC
Tests failed on 2aa47ee91a7cb2fb0de66a7e54bb29ecd31972c4, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231205-012827-2aa47ee9-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2023-12-05 05:13
duplicate of #19679

**Closed by martinpitt** 2023-12-05 05:13 UTC
Labels: nightly
