### ISSUE TITLE
how can i update ？

### ISSUE THREAD

**Issue by zifeiyuk8s** [cockpit-project/cockpit#8868] opened 2018-03-22 05:59 UTC
i use yum -y install cockpit,but it is 160，but i want use 164，what i should do ?

**Comment by marusak** [comment] 2018-03-27 07:30
What OS you use? (by using yum I guess that you use RHEL 7?)
For RHEL7 newest version is 160 https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=46519
There is build of 164 on cockpit's copr, but mind that it may not work perfectly https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/

**Comment by andreasn** [comment] 2018-03-29 15:54
This sounds like a distribution packaging issue, but this issue tracker is only for development issues.
Here are some resources:
 * Fedora: https://ask.fedoraproject.org/en/questions/
 * CentOS: https://www.centos.org/forums/
 * Red Hat Enterprise Linux: https://access.redhat.com/support/

Since the issue is outside the scope of this issue tracker, I'll close this.
Hope you're able to figure it out in the end!

**Closed by andreasn** 2018-03-29 15:54 UTC
