### ISSUE TITLE
Terminal: paste action doesn't work if using the menu to paste

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12939] opened 2019-10-08 18:56 UTC
Cockpit version: 203
OS: Fedora
Page: Terminal

I tried to copy and paste in the terminal. For some reason paste doesn't work if you use the right click menu. If I use the shortcut (shift+insert) it works as expected.

I get this message in the console of the web browser:

```
Text could not be pasted, use Shift+Insert: TypeError: navigator.clipboard.readText is not a function 5 cockpit-components-terminal.jsx:200:20
    setText cockpit-components-terminal.jsx:200
    React 9
    unstable_runWithPriority scheduler.production.min.js:20
    React 3
```

**Comment by marusak** [comment] 2019-10-09 07:23
Well, that is kinda "feature/known bug". You are using Firefox I guess, because on chrome/ium this should work just fine. The problem is that Firefox does not provide proper clipboard permission api and pasting does not work (only with shift+insert).
There is not much we can do - or you are thinking of some better way how to let users know what is happening?

**Comment by andreasn** [comment] 2019-10-09 08:45
Ah, I see. It took me a while to figure out I could look in the console, so maybe we could show an error notification in the page? Saying something like `Text could not be pasted, use Shift+Insert`

**Comment by marusak** [comment] 2019-10-10 05:19
Sure, some idea what would be the right place?

**Comment by andreasn** [comment] 2019-10-10 13:01
I'll try to figure that out.

**Comment by KKoukiou** [comment] 2021-04-19 16:20
The Permissions API is still not allowing that on firefox. https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API 

Do we want an issue in cockpit for that as well? Not much we can do on our side. @marusak fine with closing?

**Comment by KKoukiou** [comment] 2021-04-19 16:25
Actually I just realized google docs has the same issue and they show a nice warning.
Let's do something similar.
![Screen Shot 2021-04-20 at 18 22 15](https://user-images.githubusercontent.com/14921356/115270386-89fb7580-a13c-11eb-864c-5fb46ca9ddb8.png)

**Comment by marusak** [comment] 2021-04-19 18:51
Indeed, this issue was kept open for having some visual notifying that copying failed and what can be done about it.

**Closed** 2021-04-20 15:09 UTC
Labels: page:terminal
