### ISSUE TITLE
Display full service log

### ISSUE THREAD

**Issue by fedeb95** [cockpit-project/cockpit#7367] opened 2017-07-25 14:29 UTC
In the "Service" tab, if a log message from a service is too long, this can't be viewed entirely, neither clicking on the entry displays it like in the "Log" tab

**Comment by andreasn** [comment] 2017-09-12 09:56
Yeah, clicking it should take you to it's Logs page I think.

**Comment by andreasn** [comment] 2017-09-12 09:57
@mvollmer what do you think?

**Comment by fedeb95** [comment] 2017-09-12 10:17
This is what happens: double clicking simply highlights text. I'm using cockpit shipped with fedora 26 on the server, debian 8.9 and firefox on the client
![istantanea - 12092017 - 12 15 10](https://user-images.githubusercontent.com/25415908/30320758-e7fce9a2-97b3-11e7-83d0-1008e2e216cd.png)

**Comment by andreasn** [comment] 2017-09-13 12:03
I mean it doesn't take you too the Logs right now, I was suggesting we change it to that behaviour. Sorry for being unclear.

**Comment by fedeb95** [comment] 2017-09-13 12:16
oh, my bad. Thank you for taking my request into account then.

**Comment by martinpitt** [comment] 2019-01-14 13:19
Filtering on Logs page is issue #1535. But we still need to change the Service page to at least link to the Logs page, with some pre-set filtering. So keeping this issue open as well.

**Comment by marusak** [comment] 2019-11-12 09:11
Duplicate of #3852

**Closed by marusak** 2019-11-12 09:11 UTC
Labels: needsdesign, review-2019-10
