### ISSUE TITLE
Docker Console Shows Disconnected

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#3216] opened 2015-11-23 13:16 UTC
I've just updated to F23 which comes with Cockpit 0.83, since upgrading all of my docker containers show "disconnected" in the console window, despite being up and running.

I'm not sure if this is connected to a recent change in the Fedora packaged docker build, but each of my containers seem to have leaked into the system journal for example:
 13:10 *** Runit started as PID 28 docker
 13:10 *** Booting runit daemon... docker
 13:10 *** Running /etc/rc.local... docker

**Comment by stefwalter** [comment] 2015-11-24 04:36
docker is broken on Fedora 23. Try to run 'docker logs mycontainer' from the command line.

This is a duplicate of #3174

CC @lsm5 @rhatdan

**Closed by stefwalter** 2015-11-24 04:36 UTC
