### ISSUE TITLE
Nightly tests did not succeed on fedora-38/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19475] opened 2023-10-13 02:28 UTC
Tests failed on 953a6eeb9be2b6cd1c5c95fce7c0db19749bc72f, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231013-012634-953a6eeb-fedora-38-daily//log.html)

**Comment by martinpitt** [comment] 2023-10-13 04:31
Duplicate of #19445 . I'll look at that this morning.

**Closed by martinpitt** 2023-10-13 04:31 UTC
Labels: nightly
