### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19694] opened 2023-12-05 02:36 UTC
Tests failed on 2aa47ee91a7cb2fb0de66a7e54bb29ecd31972c4, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231205-012829-2aa47ee9-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment] 2023-12-05 05:13
Duplicate of #19679

**Closed by martinpitt** 2023-12-05 05:13 UTC
Labels: nightly
