### ISSUE TITLE
Cockpit switches to dark mode in the "View hardware details" page

### ISSUE THREAD

**Issue by MingcongBai** [cockpit-project/cockpit#18103] opened 2022-12-31 20:02 UTC
### Explain what happens

1. Log in to Cockpit's Web console.
2. Click on the "View hardware details" link in the "System Information" section.
3. Cockpit switches to dark mode, and switches back after leaving said page. This can be distracting and unpleasant. See video attached below.

https://user-images.githubusercontent.com/5006263/210154588-e39a2209-ca27-401f-a80d-035151cfbf3d.mp4

### Version of Cockpit

282.1

### Where is the problem in Cockpit?

Overview

### Server operating system

other

### Server operating system version

AOSC OS (10.0.0)

### What browsers are you using?

Firefox

**Comment by marusak** [comment] 2023-01-02 11:07
I believe this is duplicate of https://github.com/cockpit-project/cockpit/issues/17978

This should be fixed in version 282 (which you declare you are using). Can you check if you have updated all cockpit packages and also stopped cockpit.socket after the upgrade?

**Comment by KKoukiou** [comment] 2023-01-02 12:50
@marusak it's unfortunately reproduceable with current main branch.

@MingcongBai thanks for the bug report, we will fix it with next release.

**Closed** 2023-01-03 10:39 UTC
Labels: bug
