### ISSUE TITLE
Viewing Performance Metrics page crashing browser on Safari and Chrome (iOS)

### ISSUE THREAD

**Issue by shred86** [cockpit-project/cockpit#16398] opened 2021-09-25 14:35 UTC
Cockpit version: 253
OS: Debian 11
Page: Performance Metrics

After installing `cockpit-pcp`, I was able to view the Performance Metrics page just fine but there was only a limited amount of metrics/history. Several hours later, I’m attempting to view the same page again but now it just opens up for maybe a second or two then the browser immediately crashes. I’ve tried this in both Safari and Chrome on both my iPad and iPhone.

Steps to reproduce

1. Install `cockpit-pcp`.
2. Wait several hours for enough performance metrics to be logged.
3. Attempt to open the Performance Metrics page on iOS 15 or iPadOS 15 using Safari or Chrome.

**Comment by shred86** [comment] 2021-09-25 23:14
I seem to be able to access the Performance Metrics page from my laptop with Ubuntu using the Brave (Chromium) and Firefox browser just fine. It also works from my iMac with Chrome. However, when attempting to view the page on my iMac with Safari 15.0, it just shows the metrics loading then eventually Safari and the entire computer become extremely sluggish (almost unresponsive).

**Comment by martinpitt** [comment] 2021-09-26 08:50
This is almost certainly a duplicate of issue #16242. This will be fixed in 254 next week. If you want, you can also try the build from this COPR: https://dashboard.packit.dev/results/copr-builds/155881

**Closed by martinpitt** 2021-09-26 08:50 UTC
