### ISSUE TITLE
Tests failed on 03d7067e47bd6bea6dde7025bfd52ce091f52e60

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20413] opened 2024-05-02 02:22 UTC
The job `fedora-40/updates-testing` failed on commit 03d7067e47bd6bea6dde7025bfd52ce091f52e60.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-03d7067e-20240502-012624-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-05-03 09:08
Duplicate of #20338

**Closed by martinpitt** 2024-05-03 09:08 UTC
Labels: nightly
