### ISSUE TITLE
3 incorrect password attempts when using MFA

### ISSUE THREAD

**Issue by agentoranger** [cockpit-project/cockpit#17359] opened 2022-05-19 17:19 UTC
Suggestion:

**Create a feature to allow sysadmins to disable the automatic escalation.**

### Explain what happens

We can successfully enable RSA authentication on cockpit, and it operates very well with one painful exception. That is related to how sudo authentication is handled after login into cockpit.  We are seeing a bug that is causing cockpit to log three failed authentication requests as the result of an attempt to automatically escalate to sudo with RSA credentials that are undergoing rotation.  As any RSA password can only be used one, cockpit will ultimately fail three times when the conditions are right.

**Conditions:**
1.  Use a RedHat 8.6 Server installation, enable cockpit, normal user sshkey generation.
2.  Configure Cockpit, sudo, and ssh pam modules for use with MFA, in this case the [RSA Authentication Agent.](https://[community.securid.com](https://community.securid.com/t5/rsa-securid-access-knowledge/enable-linux-password-authentication-along-with-rsa/ta-p/2145)/t5/rsa-securid-access-knowledge/enable-linux-password-authentication-along-with-rsa/ta-p/2145)
3.  RSA: Require that rotating passwords are to be used a maximum of 1 time.
4.  RSA: Require that rotating password are to rotate every 1 minute.
5.  PAM: Require RSA + Password Authentication for ssh, sudo, and cockpit,

Steps to reproduce:
1.  Access cockpit from HTTPS
2.  Login to cockpit with a password, then reaching the RSA prompt.
3.  Provide the rotating RSA password, then reaching the Overview page
4.  Witness that escalation did not occur automatically.
5.  Witness that three failed authentication requests occurred with invalid saved credentials. 

Examples:
orangeb : 3 incorrect password attempts ; TTY=unknown ; PWD=/run/user/1001 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged
 
PRIORITY					1
SYSLOG_FACILITY				10
SYSLOG_IDENTIFIER			sudo
_AUDIT_LOGINUID				1001
_AUDIT_SESSION				5
_BOOT_ID					<removed>
_CAP_EFFECTIVE				1ffffffffff
_CMDLINE					sudo -A cockpit-bridge --privileged
_COMM						sudo
_EXE							/usr/bin/sudo
_GID						1001
_HOSTNAME					<removed>
_MACHINE_ID					<removed>
_PID							25022
_SELINUX_CONTEXT			unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
_SOURCE_REALTIME_TIMESTAMP	1652979303313776
_SYSTEMD_CGROUP			/user.slice/user-1001.slice/session-5.scope
_SYSTEMD_INVOCATION_ID		<removed>
_SYSTEMD_OWNER_UID			1001
_SYSTEMD_SESSION			5
_SYSTEMD_SLICE				user-1001.slice
_SYSTEMD_UNIT				session-5.scope
_SYSTEMD_USER_SLICE			-.slice
_TRANSPORT					syslog
_UID						0
__CURSOR					<removed>
__MONOTONIC_TIMESTAMP		48387133989
__REALTIME_TIMESTAMP		1652979303313807

![image](https://user-images.githubusercontent.com/9388401/169359491-f418818f-044c-4c0f-8e5e-fa95cbb7f370.png)

### Version of Cockpit

cockpit-264.1-1.el8.src.rpm

### Where is the problem in Cockpit?

Authentication, Escalation, Sudo, PAM, MFA, RSA

### Server operating system version

Red Hat Enterprise Linux release 8.4 (Ootpa)
Red Hat Enterprise Linux release 8.6 (Ootpa)

### What browsers are you using?

Google Chrome
Microsoft Edge

### System log

`root@test75-rhel8:/opt/netl/scripts]# journalctl --since -140m -u session-5.scope
-- Logs begin at Wed 2022-05-18 23:28:41 EDT, end at Thu 2022-05-19 13:18:06 EDT. --

May 19 12:54:55 test75-rhel8 systemd[1]: Started Session 5 of user orangeb.
May 19 12:54:55 test75-rhel8 cockpit-ws[25006]: cockpit-session: pam: Last login: Thu May 19 12:33:20 EDT 2022 from 172.20.34.82 on pts/0

**#Automatic escalation failure**
May 19 12:55:03 test75-rhel8 sudo[25022]:  orangeb : 3 incorrect password attempts ; TTY=unknown ; PWD=/run/user/1001 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged

**#Manual escalation successful after waiting for a new password**
May 19 12:55:35 test75-rhel8 sudo[25105]:  orangeb : TTY=unknown ; PWD=/run/user/1001 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged
May 19 12:55:35 test75-rhel8 sudo[25105]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 19 12:55:35 test75-rhel8 sudo[25105]: pam_unix(sudo:session): session opened for user root by (uid=0)
`

**Comment by agentoranger** [comment] 2022-05-19 17:43
@mvollmer: Looks like you might have a little experience with this authentication routine, any thoughts on how we can workaround the automatic escalation?

**Comment by martinpitt** [comment] 2022-05-20 15:16
This is a duplicate of #17169. It was fixed in Cockpit 267. If you want to try it on RHEL 8.6, you can use [this COPR build](https://download.copr.fedorainfracloud.org/results/packit/cockpit-project-cockpit-17196/centos-stream-8-x86_64/03918095-cockpit/).

**Closed as completed by martinpitt** 2022-05-20 15:16 UTC
Labels: bug
