### ISSUE TITLE
Nightly tests did not succeed on fedora-38/other

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20079] opened 2024-02-22 13:23 UTC
Tests failed on c44c7ef827a7502761cb56b486adc3431bb88bdc, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20073-20240222-122839-c44c7ef8-fedora-38-other/log.html)

**Comment by martinpitt** [comment] 2024-02-22 13:41
Duplicate of #20075

**Closed by martinpitt** 2024-02-22 13:41 UTC
Labels: nightly
