### ISSUE TITLE
Tests failed on 035dc2d9be846320bbe4b2be75c3227793735ed8

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21294] opened 2024-11-21 02:28 UTC
The job `fedora-40/updates-testing` failed on commit 035dc2d9be846320bbe4b2be75c3227793735ed8.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-035dc2d9-20241121-013135-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-21 05:12
Duplicate of #21237

**Closed by martinpitt** 2024-11-21 05:12 UTC
Labels: nightly
