### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19797] opened 2024-01-02 02:24 UTC
Tests failed on 5060e25b60f71bfa622281fc5f182c12233c2153, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240102-012702-5060e25b-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2024-01-02 07:26
Duplicate of #19787

**Closed by martinpitt** 2024-01-02 07:26 UTC
Labels: nightly
