### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by ashwin31** [cockpit-project/cockpit#2713] opened 2015-09-07 09:13 UTC
It doesn't seems to be having support for ubuntu servers. if yes, please update http://cockpit-project.org/running.html to show it.

**Comment by stefwalter** [comment] 2015-09-07 09:22
Hash anybody packaged Cockpit, or contributed towards this effort? If so, please file pull requests and or issues specific to the problems encountered. 

This issue is a duplicate of #2671

**Closed by stefwalter** 2015-09-07 09:22 UTC
