### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19840] opened 2024-01-15 02:30 UTC
Tests failed on d742ae04b81a46100921392751ff13f64ca00351, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240115-012940-d742ae04-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2024-01-15 05:50
Duplicate of #19822

**Closed by martinpitt** 2024-01-15 05:50 UTC
Labels: nightly
