### ISSUE TITLE
Query:file transfer through cockpit

### ISSUE THREAD

**Issue by shailendra73** [cockpit-project/cockpit#7446] opened 2017-08-03 12:51 UTC
I am running cockpit via remote host on my ubuntu machine and i want to copy files from test machine to host and vice versa. 

Do we have any api's like cockpit.spawn to download or upload files from my remote host to the machine i am running cockpit on or the other way around.

**Comment by stefwalter** [comment] 2017-08-03 15:54
Check out this cockpit component:

https://github.com/cockpit-project/cockpit/blob/master/pkg/sosreport/index.js#L91

It does what you're looking for. Does that look like it'll work. If so, we could move this code into cockpit.js and make it a well known API. What do you think @mvollmer? Any limitations around this API?

**Comment by shailendra73** [comment] 2017-08-10 11:52
@stefwalter Thankyou.
This component is helping me out with download mechanism. Could you please specify something for uploading a file from host machine to the test machine(server) file structure.

**Comment by stefwalter** [comment] 2017-08-10 15:00
Uploading via the browser? It's certainly an interesting problem. I'll think about it ... but not one anyone has done before. So this is going to take a bit longer. I'll be away for the next couple weeks.

**Comment by shailendra73** [comment] 2017-08-11 11:19
@stefwalter Thankyou for the response.
Kindly let me know if there are any advancements wrt the upload problem.

**Comment by marusak** [comment] 2019-11-12 11:47
Duplicate of #12338

**Closed by marusak** 2019-11-12 11:47 UTC
