### ISSUE TITLE
Ubuntu 20.04 LTS Loading available updates failed

### ISSUE THREAD

**Issue by williamgh2019** [cockpit-project/cockpit#14006] opened 2020-05-01 11:11 UTC
Cockpit version: 215
OS: Ubuntu 20.04 LTS
Page: 

Please help us out by explaining how to reproduce it.

Relevant parts of the system log are also useful:
Cannot refresh cache whilst offline

Steps to reproduce

1. Log in by web
2. I see it on  Health Dashboard as Loading available updates failed
3. Try to click on Software Update it shows: Cannot refresh cache whilst offline

![image](https://user-images.githubusercontent.com/17005582/80801593-1e409580-8bd7-11ea-84a2-db461f9ce75d.png)

![image](https://user-images.githubusercontent.com/17005582/80801614-2bf61b00-8bd7-11ea-8774-a8258b756f5f.png)

**Comment by HyderKhalil** [comment] 2020-05-01 22:42
Also have this on Ubuntu Server 20.04. However, when I first log in to Cockpit, dashboard status shows up to date, but when I click the Software Updates tab, after the progress bar, the cannot refresh error is shown.
![Screenshot 2020-05-01 at 23 41 18](https://user-images.githubusercontent.com/8531503/80846805-6aa2ca00-8c05-11ea-8b1d-7f7e9e53b0f6.png)

![Screenshot 2020-05-01 at 23 41 28](https://user-images.githubusercontent.com/8531503/80846816-72fb0500-8c05-11ea-9685-905caec4d480.png)

**Comment by williamgh2019** [comment] 2020-05-02 06:56
Yep! this error I got same you too beside by error above. Hope creator will fix.

**Comment by marusak** [comment] 2020-05-02 07:40
Duplicate of https://github.com/cockpit-project/cockpit/issues/8477

There a few workarounds. It is limitation of Ubuntu, not Cockpit ones.

**Closed by marusak** 2020-05-02 07:40 UTC

**Comment by baughmann** [comment] 2023-02-25 22:59
"Our software doesn't work on this operating system? Must be the operating system's fault. Has nothing to do with the fact that we are a corporation that completes with the other operating system. Nothing to see here."

**Comment by baughmann** [comment] 2023-02-28 13:31
@garrett You're right, it's not. It's actually pretty insensitive in retrospect.

You can tell the community put a lot of work into cockpit, and it's one of the best easy admin tools I've ever used.

So, I apologize. It came from a place of anger when it should have come from a place of help and appreciation.
