### ISSUE TITLE
Edit Firewall zones after adding them

### ISSUE THREAD

**Issue by Cooperdale** [cockpit-project/cockpit#14842] opened 2020-10-31 13:01 UTC
I noticed that, after adding a Firewall zone, containing for instance particular IPs or ranges, you can't edit the zone afterwards, for instance adding or removing IPs.
I think it would be useful.

**Comment by marusak** [comment] 2020-11-01 06:32
Thank you for the report! It is already reported though, thus closing.

Duplicate of https://github.com/cockpit-project/cockpit/issues/12287

**Closed by marusak** 2020-11-01 06:32 UTC
