### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19922] opened 2024-02-01 02:26 UTC
Tests failed on fca64d4b989ceadabbfda311b971a41490aa2187, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240201-012701-fca64d4b-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment] 2024-02-01 05:17
Duplicate of #19765

**Closed by martinpitt** 2024-02-01 05:17 UTC
Labels: nightly
