### ISSUE TITLE
252 - unable to add private key

### ISSUE THREAD

**Issue by OSXGroupFL** [cockpit-project/cockpit#16553] opened 2021-11-02 19:15 UTC
I just updated to 252 to try and solve this issue and it still exists. I try to add a private key for authentication and the box just closes and does not appear to use the key. I have had this issue going on for awhile now and I really want to be able to use this to manage multiple servers but the headache of getting it to use keys is wasting a ton of time.

**Comment by KKoukiou** [comment] 2021-11-03 17:05
We rewrote the credentials dialog in 256 with https://github.com/cockpit-project/cockpit/pull/16470, try to update to > 256 firstly and then please update the issue here with any errors you see in the UI or the browser console.

**Comment by KKoukiou** [comment] 2021-11-03 17:08
Closing this as duplicate of https://github.com/cockpit-project/cockpit/issues/12432 

Please reply there with any updates.

**Closed by KKoukiou** 2021-11-03 17:08 UTC
Labels: question
