### ISSUE TITLE
Tests failed on c037dc3338790167402a3fbdd75fbc3e1727a85e

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20587] opened 2024-06-14 02:24 UTC
The job `fedora-40/daily` failed on commit c037dc3338790167402a3fbdd75fbc3e1727a85e.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c037dc33-20240614-012941-fedora-40-daily/log.html

**Comment by martinpitt** [comment] 2024-06-15 05:58
Duplicate of #20542

**Closed by martinpitt** 2024-06-15 05:58 UTC
Labels: nightly
