### ISSUE TITLE
"The filesystem has no permanent mount point" on snap partitions

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#17173] opened 2022-03-23 17:36 UTC
### Explain what happens

hi.. i'm not sure if this is a bug or a problem with snap , ubuntu  or cockpit , but i'm seeing a lot of warnings in the storage section about inconsistent mounts which all come from snap, and i was wondering if those can be ignored, or avoided somehow

![incosistent_snaps](https://user-images.githubusercontent.com/13434544/159761194-b9a0d4ca-8af0-4ae2-ad90-087225c3a749.png)

this is my layout

aeroscout@aessrv-561-0712:~$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0  61.9M  1 loop /snap/core20/1328
loop1    7:1    0  61.9M  1 loop /snap/core20/1376
loop2    7:2    0  43.6M  1 loop /snap/snapd/14978
loop3    7:3    0  67.2M  1 loop /snap/lxd/21835
loop4    7:4    0  67.9M  1 loop /snap/lxd/22526
loop5    7:5    0  43.6M  1 loop /snap/snapd/15177
sda      8:0    0   200G  0 disk 
├─sda1   8:1    0     1M  0 part 
├─sda2   8:2    0   512M  0 part /boot
├─sda3   8:3    0     8G  0 part [SWAP]
└─sda4   8:4    0 191.5G  0 part /
sr0     11:0    1  1024M  0 rom  

$ snap list
Name    Version   Rev    Tracking       Publisher   Notes
core20  20220304  1376   latest/stable  canonical✓  base
lxd     4.0.9     22526  4.0/stable/…   canonical✓  -
snapd   2.54.4    15177  latest/stable  canonical✓  snapd

### Version of Cockpit

264-1~bpo20.04.1

### Where is the problem in Cockpit?

Storage

### Server operating system version

20.04.04

### What browsers are you using?

Chrome

**Comment by mvollmer** [comment] 2022-03-24 11:35
This is a duplicate of #14424, which is tracked upstream at https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/1714941

Apparently, there is a special mount option now, "x-gdu.hide", which GNOME Disks knows about.  I guess Cockpit should start looking at that as well.

**Comment by martinpitt** [comment] 2022-03-24 12:25
@mvollmer: See discussion in PR #15439. This has a proposed test case/reproducer, and some thoughts about it. (This has been on my todo list for too long..)

**Comment by mvollmer** [comment] 2022-03-24 12:43
> See discussion in PR #15439.

Wow, I forgot all about that!

"x-gdu.hide" is indeed hard to find, and might require us to finally parse systemd mount units in addition to fstab.

**Comment by mvollmer** [comment] 2022-03-24 12:49
I think omitting all read-only loop devices from the Storage page is too much. What about being more specific and omitting anything mounted on something below `/snap`?  That should work.

**Comment by emaayan** [comment] 2022-03-24 13:16
would love some background on read only loops why is this a warning, and what would happen if people would try to unmount it or have it mounted on next reboot? (and how can avoid or remove those warnings)

**Comment by mvollmer** [comment] 2022-03-24 13:23
> would love some background on read only loops why is this a warning,

The warning appears because Cockpit does not understand systemd mount units.  Any filesystem that is mounted exclusively via a systemd mount unit and not via /etc/fstab is going to show this warning, because Cockpit isn't aware that the mount unit will take care of mounting it on the next boot.

So we clearly have to teach Cockpit about mount units.

But for snaps specifically, I think it is better to omit them from Cockpit entirely.  We were hoping that the loop devices will get marked up with UDISKS_IGNORE hints, but that doesn't seem to happen and UI are expected to look at the x-gdu.hide option.  But looking at the mount points is much more straightforward.

> and what would happen if people would try to unmount it or have it mounted on next reboot? (and how can avoid or remove those warnings)

The snaps might stop working, I guess.

**Comment by martinpitt** [comment] 2022-03-24 13:39
> What about being more specific and omitting anything mounted on something below /snap

I don't like such special cases at all, but if parsing out the mount options is too hard, then I'm fine with it of course.

**Comment by emaayan** [comment] 2022-03-24 17:54
i didn't install any of those snaps on my own i would imagine those are just base minimum for snap managment in ubuntu.

**Closed** 2022-03-29 13:15 UTC
Labels: bug
