### ISSUE TITLE
Ubuntu 22.04 Cockpit Unexpected Internal Error

### ISSUE THREAD

**Issue by OtherWorlds** [cockpit-project/cockpit#17427] opened 2022-06-04 07:32 UTC
I've had the server running fine for the past few weeks, It just now start to give me an issue, its not stopping me from using the web interface itself, however, since this issue started I haven't been able to access my samba shared folders. I have no idea what could be causing this issue, as I have changed any thing on the server for the last few days.
The errors I am getting from the developer console in my browser:
```javascript
terminal.js:2 FormSelect requires either an id or aria-label to be specified
ie @ terminal.js:2

updates.js:2 Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
(anonymous) @ updates.js:2

updates.js:2 Uncaught TypeError: Cannot set properties of undefined (setting 'vendor_urls')
    at Object.UpdateDetail (updates.js:2:1102472)
    at ae.<anonymous> (updates.js:2:402375)
    at cockpit.js:1:31321
    at L (cockpit.js:1:12242)
```

**Comment by martinpitt** [comment] 2022-06-04 08:47
Duplicate of #17405

**Closed by martinpitt** 2022-06-04 08:47 UTC
