### ISSUE TITLE
Segmentation fault when changing chart period to 1 week

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14410] opened 2020-07-26 11:10 UTC
Cockpit version: 188-1 (version given by apt-cache)
OS: Debian Buster (kernel 4.19.0-9-amd64)
Page: Networking

I get a segmentation fault when I press the chart period button and set it to 1 week on the Networking page. After this event the historical data is no more plotted in any of the charts, also not on all other pages. This issue does not happen on System page or Storage page.

Output in syslog:
Jul 26 11:27:00 NAS001 cockpit-bridge[25673]: /usr/lib/cockpit/cockpit-pcp: bridge was killed: 11
Jul 26 11:27:00 NAS001 kernel: [582530.016147] cockpit-pcp[25681]: segfault at 56090f012002 ip 00007f1be7331011 sp 00007ffdb7e75fe8 error 4 in libpcp.so.3[7f1be7318000+5d000]
Jul 26 11:27:00 NAS001 kernel: [582530.016163] Code: 00 00 48 63 4e 04 85 c9 7e 5f 48 8b 46 08 48 8d 0c 49 48 8d 0c c8 48 39 c8 72 0f eb 4c 0f 1f 40 00 48 83 c0 18 48 39 c1 76 3f <3b> 38 75 f3 48 8b 48 10 48 63 70 08 48 8d 34 b1 48 39 f1 73 17 3b

Steps to reproduce
1. Login to Cockpit
2. Go to Networking page
3. Press chart period button and set to "1 week"

**Comment by RoyKas** [comment] 2020-07-29 20:37
Moved to version 223-1 (Debian Buster backport)

The above issue also occurs in this version. Output in syslog is:
Jul 29 22:23:52 nas001 kernel: [31577.348072] cockpit-pcp[22628]: segfault at 0 ip 00007fb119e80011 sp 00007ffd7244b298 error 4 in libpcp.so.3[7fb119e67000+5d000]
Jul 29 22:23:52 nas001 cockpit-bridge[22605]: /usr/lib/cockpit/cockpit-pcp: bridge was killed: 11
Jul 29 22:23:52 nas001 kernel: [31577.348087] Code: 00 00 48 63 4e 04 85 c9 7e 5f 48 8b 46 08 48 8d 0c 49 48 8d 0c c8 48 39 c8 72 0f eb 4c 0f 1f 40 00 48 83 c0 18 48 39 c1 76 3f <3b> 38 75 f3 48 8b 48 10 48 63 70 08 48 8d 34 b1 48 39 f1 73 17 3b

**Comment by martinpitt** [comment] 2020-08-06 13:59
I was a bit surprised, but this is actually perfectly reproducible. This seems to be a bug in PCP 4.3.2 in Debian 10, and is fixed in version 5.x in Debian testing. At least I don't get the crash with that. [Debian pcp versions](https://tracker.debian.org/pkg/pcp)

As that is a bug in an old version of pcp, not Cockpit, I'm closing this here. Thanks!

**Closed by martinpitt** 2020-08-06 13:59 UTC
