### ISSUE TITLE
cannot view individual log entries from Storage or Network log

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3852] opened 2016-02-26 20:30 UTC
It looks like this should be possible, since each line in the corresponding log panel turns blue if you hover over it, but clicking on the line achieves nothing.

The log in Logs window works as expected, i.e., you can click on individual lines to see a complete log entry.

**Comment by andreasn** [comment] 2016-02-29 12:40
Yup, agreed, should be able to go to the full error.
Where should it end up though?
There are two cases we need to address with that. One is figuring out the content of the full message, and one is figuring out what else happen to the system around the time of the message.

@dperpeet @mvollmer thoughs?

**Comment by andreasn** [comment] 2016-02-29 16:42
One thing that would fix both issues in one shot would be to show the additional info inline in the journal instead of on a separate page. I was a bit worried about the height, but breaking it up into two columns seems to take care of it.

So if you see an error on the storage page, you click on the error and it jumps to the Logs page with the details about the error expanded.

![screenshot from 2016-02-29 17-09-33](https://cloud.githubusercontent.com/assets/209895/13401258/b2c7ccbe-df0b-11e5-8211-7a427c02997e.png)

**Comment by andreasn** [comment] 2016-02-29 16:44
_SOURCE_REALTIME_TIMESTAMP of course breaks up rather ugly in the above screenshot, but ignore that for now :)

**Comment by mulkieran** [comment] 2016-02-29 19:28
This seems tricky to me because you would have to adjust the filters on the logs so that that particular log entry would be one that would occur in the list of log entries. With the projected greater sophistication of filters that I saw on the wiki feature that might become even more tricky. It's actually quite nice that the selected filters persist, I'm not sure I would be happy to have changed the Log filters by clicking on an entry in the list of log entries in Storage.

**Comment by mulkieran** [comment] 2016-02-29 22:23
Inline display of entries _might_ be made easier by visually grouping the entries as suggested in #3869 and maybe actually hiding all entries except those in the User category.

**Comment by marusak** [comment] 2019-10-31 15:46
So the goal of this is to:
1. Show logs inline and not on separate page
2. When specific log is clicked in services/networking/storage page it jumps to logs page and just opens a specific item and moves page to it?

I am a bit skeptic about logs being opened inline, since some may be waaay to long (like coredumps, also see https://github.com/cockpit-project/cockpit/issues/11665). Jumping to specific detailed log from those embedded journals is few lines of code.

**Comment by andreasn** [comment] 2019-10-31 16:12
Yeah, I agree, jumping directly to the specific detailed log is probably better.

**Comment by marusak** [comment] 2020-04-13 12:52
Duplicate of #1113

**Closed by marusak** 2020-04-13 12:52 UTC
