### ISSUE TITLE
Tests failed on f0d0c718208205a8ff6d8803f561cb31e80441f4

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20490] opened 2024-05-21 02:28 UTC
The job `fedora-40/updates-testing` failed on commit f0d0c718208205a8ff6d8803f561cb31e80441f4.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f0d0c718-20240521-012757-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-05-21 04:40
Duplicate of #20488

**Closed by martinpitt** 2024-05-21 04:40 UTC
Labels: nightly
