### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19773] opened 2023-12-22 09:30 UTC
Tests failed on d90a4645f0c13ea268de270946f9139db46172ea, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231222-083001-d90a4645-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment] 2023-12-22 11:12
Duplicate of #19772

**Closed by martinpitt** 2023-12-22 11:12 UTC
Labels: nightly
