### ISSUE TITLE
subscriptions: when unregistering a system, it never finishes

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10515] opened 2018-11-06 16:37 UTC
I've been staring at this for about 30 minutes now.

![screenshot from 2018-11-06 17-36-04](https://user-images.githubusercontent.com/209895/48078868-854fda80-e1ea-11e8-87a5-280762fa4b85.png)

Only when I reload the page it tells me I'm unregistered.

**Comment by martinpitt** [comment] 2018-11-06 20:42
Is this our own cockpit-subscriptions package in RHEL 7? Or the subscription-manager-cockpit package?

**Comment by andreasn** [comment] 2018-11-07 09:16
Our own. What's the plan for that going forward?

**Comment by martinpitt** [comment] 2019-01-15 11:40
I cannot reproduce this, thus adding question label. Is there anything relevant in the journal? Try to register, start `sudo journalctl -f`, then unregister.

**Comment by martinpitt** [comment] 2019-11-13 06:33
This has been sitting around for a long time without a reproducer nor journal info, and we didn't get any other reports about that (neither in bugzilla). I'm closing this now, sorry.

**Closed by martinpitt** 2019-11-13 06:33 UTC
Labels: question, review-2019-10
