### ISSUE TITLE
Feature: Support reverse proxy

### ISSUE THREAD

**Issue by steve--d** [cockpit-project/cockpit#1803] opened 2015-02-11 07:56 UTC
Supporting apache (and other) reverse proxy's would be helpful.

Typically I would say just adding a suburi option ie: cockpit-ws --base /cockpit but I noticed that even proxying / -> http://localhost:9090/ doesn't work properly.

**Comment by stefwalter** [comment] 2015-02-11 09:41
Are you using a reverse proxies support WebSockets? What are the exact tweaks needed to Cockpit make this work? Can you do the research here?

**Comment by stefwalter** [comment] 2015-02-19 06:22
The proxy that you are using needs to have WebSocket support. Will close this issue, but please comment here, if you're sure your proxy supports WebSockets, and it still doesn't work.

**Closed by stefwalter** 2015-02-19 06:22 UTC
Labels: question

**Comment by jasonhansel** [comment] 2015-05-18 00:08
My reverse proxy (nginx) supports WebSockets -- I'm using it with another app that requires them. However, I can't seem to get Cockpit working (I get a 401 Not Authorized). This is likely to just be a configuration issue, however.

**Comment by stefwalter** [comment] 2015-05-18 07:06
Some folks have contributed documentation on the wiki: https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX

**Comment by hrumph** [comment] 2015-12-11 21:41
Hi, I would like this reoppoened. I followed the instructions on the wiki and they work but there's
no good way (that I know of) to set a location other than "/", because the links served by cockpit don't change. For instance cockpit returns a link somewhere called "/login", and there are no configuration settings to get cockpit to return the link "/mylocation/login" instead.

**Comment by stefwalter** [comment] 2015-12-12 07:21
Please use a recent versions of cockpit. They support the root url ```/cockpit``` or ```/cockpit+mylocation/```. I think this support was added in 0.78 and later.

**Comment by hosiet** [comment] 2017-05-11 15:00
FYI: Now apache2 supports revproxy with websockets.

**Comment by aHcVolle** [comment] 2017-06-23 16:01
@hosiet since apache2 does support this now did you succedd in using it? i only get a blank page (the page's sourcecode seems to be fine).

**Comment by ald3rson** [comment] 2017-07-04 23:55
**@aHcVolle** me too. after installing nginx, when I login to cockpit, i only get blank page

**Comment by CodeSurfing145** [comment] 2017-10-16 12:10
Anyone knows how this is fixed with Apache2?
I have cockpit running over port 9090 but I get a blank page after logging in on cockpit.

**Comment by fedoraptor** [comment] 2018-02-17 14:06
Hi,
I found this older issue/topic while searching for cockpit reverse proxy solution in my project. Did not find anything so I made this on my own. I would like to help others by sharing it here and we can evolve it to official documentation eventually.
I am attaching my working Apache 2.4 configuration of reverse proxy for Cockpit on Fedora Server:
[cockpit-apache-reverse-proxy-port-443.conf.txt](https://github.com/cockpit-project/cockpit/files/1733730/cockpit-apache-reverse-proxy-port-443.conf.txt)

It has "A" grade SSL configuration (ssllabs.com) to run via HTTPS (A+ would get for enabling HSTS) + reverse proxy exposing https version of Cockpit from port 9090 (ignoring any certificate issues there) + proxy of Cockpit websockets. Please eventually notify proper guys, I can cooperate on making documentation.
PS: Thanks @stefwalter for brilliant presentation about Cyborg Teams at Devconf in Brno! 👍

**Comment by fivestones** [comment] 2018-06-13 01:29
@ald3rson @aHcVolle When I browse to cockpit running with nginx as a reverse proxy, I get the login page, but once logged on I only get a blank page. Did either of you figure this out?

**Comment by aHcVolle** [comment] 2018-06-13 07:10
No, I haven't tried it any more 🙄

**Comment by aHcVolle** [comment] 2018-06-13 07:10
No, I haven't tried it any more 🙄

**Comment by FreeSoftwareServers** [comment] 2019-03-15 06:44
> @ald3rson @aHcVolle When I browse to cockpit running with nginx as a reverse proxy, I get the login page, but once logged on I only get a blank page. Did either of you figure this out?

I have exact same issue :( Did you ever figure it out?

**Comment by aHcVolle** [comment] 2019-03-15 06:57
IIRC i never got this to work but i stopped using cockpit a while ago so I'm not sure ... But I can't help you with this sorry ....

**Comment by mvollmer** [comment] 2019-03-15 07:06
Using a reverse proxy should work, I have done this with both nginx and httpd. 

We have these instructions:

https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX
https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt

Do they help?

**Comment by mvollmer** [comment] 2019-03-15 07:08
> For instance cockpit returns a link somewhere called "/login", and there are no configuration settings to get cockpit to return the link "/mylocation/login" instead.

You can set UrlRoot in cockpit.conf, like so:

```
[WebService]
UrlRoot = /webcon/
```

You can't unfortunately use `WebRoot=/cockpit/`, that trips up Cockpit's routing logic somehow.

**Comment by mvollmer** [comment] 2019-03-15 07:14
Here is a runnable example that puts Cockpit behinf nginx with a non-empty UrlRoot: 
https://github.com/mvollmer/seamless-cockpit/tree/nginxed

The main point of the example is to show single-sign-on via OAuth, so that might be a bit confusing, but hopefully you can start from there and take out the OAuth bits again.

**Comment by FreeSoftwareServers** [comment] 2019-03-15 07:38
> @ald3rson @aHcVolle When I browse to cockpit running with nginx as a reverse proxy, I get the login page, but once logged on I only get a blank page. Did either of you figure this out?

I got it to work after a bunch of trial and error fiddling! I can only access via Proxy now tho, so not via IP:9090, but hey I'm fine with that!

https://www.freesoftwareservers.com/display/FREES/Reverse+Proxy+Cockpit+over+NGinX 

Setup:

```
Cockpit 1.8 on Fedora 27
NGinX on Ubuntu
```
Notes:

Viewing by https://ip:9090 STOPPED working after editing `cockpit.conf` and adding:

```
cat << 'EOL' >/etc/cockpit/cockpit.conf
[WebService]
AllowUnencrypted = true

[Log]
Fatal = criticals
EOL
```
But Proxy Started working! I also couldn't view cockpit via http://ip:9090, so now ONLY via Proxy, but that's fine.

I terminated https at Proxy as I prefer to do, but I also added my SSL to cockpit during testing.


NGinX Setup:

Virtual Host

```
##GLOBAL SSL
ssl_certificate /etc/ssl/certs/ssl-bundle.crt;
ssl_certificate_key /etc/ssl/private/server.key;

##Home
server {
listen 80;
server_name cockpit.freesoftwareservers.com;

return 302 https://$server_name/;

}

server {
listen 443 ssl;
server_name cockpit.freesoftwareservers.com;

location / {

proxy_pass http://192.168.1.255:9090/;
include /etc/nginx/cockpit.conf;
}
}
```

Added to nginx.conf http block:

```
http {

map $http_upgrade $connection_upgrade {
default upgrade;
'' close;
}

        ##
        # Basic Settings
        ##

```
cockpit.conf on NGinX Server:

```
cat << 'EOL' >/etc/nginx/cockpit.conf
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header X-Real-IP  $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $remote_addr;
# needed for websocket
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
# change scheme of "Origin" to http
proxy_set_header Origin http://$host;

# Pass ETag header from cockpit to clients.
# See: https://github.com/cockpit-project/cockpit/issues/5239
gzip off;
EOL
```

**Comment by lenhart** [comment] 2019-05-20 15:35
I had the blank page after login issue aswell. For future references:
`sudo systemctl status cockpit.service`
gives some hints. For me it was an invalid handshake caused by certificate issues. 
These partly were intertwined with problems that the network router does not support NAT loopback, so the server is not reachable by dyndns name from local network. In consequence calling it with the ip 192.168.x.x./cockpit-sth did not work because the certificates did not match.

Eliminating other steps tried out in the process leaves following insights: 
`proxy_set_header Upgrade $http_upgrade;`
needs to be in both configuration files (the overall server.conf and the _cockpit.conf file) in the /cockpit-sth/ section (if you have seperate files for the reverse proxy)

The /etc/cockpit/cockpit.conf consists of
`[WebService]
UrlRoot = /cockpit-sth/
Origins = http://my.ddnss.de http://127.0.0.1:13689`

other entries were not necessary. Hope this helps a bit

**Comment by KMFtcy** [comment] 2021-03-24 09:33
> > For instance cockpit returns a link somewhere called "/login", and there are no configuration settings to get cockpit to return the link "/mylocation/login" instead.
> 
> You can set UrlRoot in cockpit.conf, like so:
> 
> ```
> [WebService]
> UrlRoot = /webcon/
> ```
> 
> You can't unfortunately use `WebRoot=/cockpit/`, that trips up Cockpit's routing logic somehow.

Thanks for this comment I change subdirection to cockpits and it works. Trips me days.
