### ISSUE TITLE
Tests failed on 23701a555a5af13f998ee4c7526d27fdb5669d63

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20704] opened 2024-07-04 01:39 UTC
The job `fedora-40/daily` failed on commit 23701a555a5af13f998ee4c7526d27fdb5669d63.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-23701a55-20240704-013011-fedora-40-daily/log.html

**Comment by martinpitt** [comment] 2024-07-04 04:36
Duplicate of #20694

**Closed by martinpitt** 2024-07-04 04:36 UTC
Labels: nightly
