### ISSUE TITLE
Tests failed on b0e82161b4afcb9f0a6fddd8ff94380e983b2238

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21262] opened 2024-11-14 02:32 UTC
The job `fedora-40/updates-testing` failed on commit b0e82161b4afcb9f0a6fddd8ff94380e983b2238.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-b0e82161-20241114-013109-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-14 06:09
Still a duplicate of #21237 plus the recent NFS failure. I'll re-test the latter with https://bodhi.fedoraproject.org/updates/FEDORA-2024-e8733f31e3 which is supposed to fix the restart hang.

**Closed by martinpitt** 2024-11-14 06:09 UTC
Labels: nightly
