### ISSUE TITLE
oops, Uncaught TypeError: Cannot read property 'lookup' of null

### ISSUE THREAD

**Issue by cmurf** [cockpit-project/cockpit#2658] opened 2015-08-29 23:37 UTC
cockpit-0.67-1.fc23.i686

I'm getting a red Ooops! message in cockpit any time I click on Create New Account. The browser reports this:

DBusErrormessage: "No such file or directory"name: "org.freedesktop.DBus.Error.FileNotFound"problem: nulltoString: ()__proto__: DBusError
shell/cockpit-docker.min.js:3220 No such file or directory
shell/cockpit-docker.min.js:6401 Uncaught TypeError: Cannot read property 'lookup' of null

There's nothing reported in the journal.

**Comment by cmurf** [comment] 2015-08-29 23:45
OK after rebooting this no longer happens. So something else is putting it into a state where this problem happens and I'm not sure what it is...

**Comment by stefwalter** [comment] 2015-08-30 08:18
Fedora 23 has been pretty broken due to a major regression in the GLib library: https://bugzilla.redhat.com/show_bug.cgi?id=1225957

The problem has been fixed, but is not yet pushed out into Fedora updates. This is a probable cause of this problem.

**Comment by stefwalter** [comment] 2015-12-01 06:21
The Glib regression has been fixed in Fedora 23 and elsewhere.

**Closed by stefwalter** 2015-12-01 06:21 UTC
