### ISSUE TITLE
machines: Operating System Dropdown List empty (Host Ubuntu 20.04)

### ISSUE THREAD

**Issue by tavoc** [cockpit-project/cockpit#15381] opened 2021-02-19 09:48 UTC
Cockpit version: 215-1
OS: Ubuntu Server 20.04.1
Page: Machines

If I want to create a new virtual machine I am unable to procede. The dropdown List for Operating System is always empty. 
It does not matter if I use a local image or if I want to choose to download.

Steps I did:
delete everything with
apt-get purge cockpit-*

installed with

apt-get install cockpit cockpit-dashboard cockpit-machines cockpit-storaged
![cockpit-machines](https://user-images.githubusercontent.com/6911803/108487805-f292b700-729f-11eb-88fd-0174cb97f1fa.png)

**Comment by KKoukiou** [comment] 2021-02-19 10:24
@tavoc the operating system dropdown is filled by data we fetch from osinfo-db. Can you paste the versions of the package for libosinfo and osinfo-db? 

And if you can also run this script, https://paste.centos.org/view/8f36a966 and send me the output that would be very useful to understand your issue. Thanks for helping :)

**Comment by tavoc** [comment] 2021-02-19 10:32
Hello,

sure. Here is the requested info:

dpkg -l | grep osinfo

ii  libosinfo-1.0-0:amd64                                       1.7.1-1                                                               amd64        
ii  libosinfo-bin                                               1.7.1-1                                                               amd64        
ii  osinfo-db                                                   0.20200325-1                                                          all          


With your script I have a problem, it seems it does not find "gi":

python cockpit.py
Traceback (most recent call last):
  File "cockpit.py", line 3, in <module>
    import gi
ImportError: No module named gi

but I have the following package installed:
python3-gi ist schon die neueste Version (3.36.0-1).

Is this maybe the problem?

**Comment by KKoukiou** [comment] 2021-02-19 10:48
@tavoc this seems to be the problem indeed. And I guess you are sure your python symlink is pointing to python3.

$ ls -la $(which python)
lrwxrwxrwx. 1 root root 9 Jan 20 19:39 /usr/bin/python -> ./python3

I would suggest that we try to fix that so that:

```
$ python 
Python 3.9.1 (default, Jan 20 2021, 00:00:00) 
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> 

```

will actually work and then see if its' the actual issue here.

**Comment by tavoc** [comment] 2021-02-19 11:06
Indeed it was pointing to python 2.7

I did the following:

cd /usr/bin/
root@serverhost:/usr/bin# ln -fs python3 python

ls -la $(which python)
lrwxrwxrwx 1 root root 7 Feb 19 11:52 /usr/bin/python -> python3


Restartet the Server, but the list is still empty.
But at least I can run your script.
[output.txt](https://github.com/cockpit-project/cockpit/files/6009454/output.txt)

**Comment by martinpitt** [comment] 2021-02-19 11:15
@tavoc: Please revert that -- messing around with the OS'es packages in /usr is a no-go. Instead run @KKoukiou 's script through `python3`. It already declares that it wants to run through `python3` in its hashbang, after all :grin:

**Comment by KKoukiou** [comment] 2021-02-19 11:19
@martinpitt @tavoc the issue here is that is the script that we use to fill that list. It won't work on systems that are defaulting to python2. 
Plus the gi python2 package is called differently, `python-gobject` and it's not a recommended dependency for us, see https://github.com/cockpit-project/cockpit/blob/master/tools/debian/control#L91

So @martinpitt is this something that we need to fix on our side to support system's where python -> python2

**Comment by tavoc** [comment] 2021-02-19 11:21
Changed it again to 2.7


But it does work with using plain python:

root@serverhost:/home/martinadm# ls -la $(which python)
lrwxrwxrwx 1 root root 9 Feb 19 12:17 /usr/bin/python -> python2.7
root@serverhost:/home/martinadm# python cockpit.py
Traceback (most recent call last):
  File "cockpit.py", line 3, in <module>
    import gi
ImportError: No module named gi
root@serverhost:/home/martinadm# python3 cockpit.py

**Comment by KKoukiou** [comment] 2021-02-19 11:28
@tavoc but when you just ran the script with `# python3 cockpit.py` did you get some output? Can you create a pastebin and share the link?

**Comment by tavoc** [comment] 2021-02-19 11:29
With python3 it works. The output file resides in the post https://github.com/cockpit-project/cockpit/issues/15381#issuecomment-782005429

**Comment by KKoukiou** [comment] 2021-02-19 12:21
@tavoc so I confirm that the script does what it's supposed to do. An I actually just tested in a VM, with python defaulting to python2.7, but where python 3 is also installed that the OSes are listed in the dialog.
Do you see any other error messages when trying to expand the OS dropdown in the 'Create VM dialog'?

**Comment by martinpitt** [comment] 2021-02-19 12:44
@KKoukiou : We should depend on python3-gi, and invoke any script through `python3`, *not* `python` (on all OSes). Making "python" == "python 3"  on recent OSes was more or less a desperate move only.

**Comment by tavoc** [comment] 2021-02-19 14:11
> echo $(which /usr/libexec/platform-python 2>/dev/null || which python3 2>/dev/null || which python)

I get 
/usr/bin/python3

**Comment by KKoukiou** [comment] 2021-02-19 14:14
@tavoc and do you see any errors int the browser console when you open dev tools that might be related?

**Comment by tavoc** [comment] 2021-02-19 15:04
In the edge Console I have the following errors:

https://pastebin.com/gman7V5m

Is this what you requested?

**Comment by KKoukiou** [comment] 2021-02-19 15:11
@tavoc right, this is related but not big help still:
```
machines.js:135 get os list returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 20, in <module>\ngi.repository.GLib.Error: libosinfo: Unexpected file type (0)"}", data: """"
```

I am kinda running out of ideas though unfortunately.
Maybe
* try another browser, so let's say firefox or chrome
* try the `Download an OS` since that does not peform any autodetection, which actually happens when you insert the ISO file

Btw: I just tested with Microsoft Edge 90.0.796.0 dev and also looks ok here.

**Comment by tavoc** [comment] 2021-02-19 15:18
> @tavoc right, this is related but not big help still:
> 
> ```
> machines.js:135 get os list returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 20, in <module>\ngi.repository.GLib.Error: libosinfo: Unexpected file type (0)"}", data: """"
> ```
> 
> I am kinda running out of ideas though unfortunately.
> Maybe
> 
> * try another browser, so let's say firefox or chrome
> * try the `Download an OS` since that does not peform any autodetection, which actually happens when you insert the ISO file
> 
> Btw: I just tested with Microsoft Edge 90.0.796.0 dev and also looks ok here.

With Chrome it is the same. The list is empty for "download OS" as well.
 I think I will simply remove python2.7 and use python3?

Or do you want to leave it, if you are interested to debug it?

**Comment by KKoukiou** [comment] 2021-02-19 15:23
@tavoc I don't think that your system having python2.7 as default is actually the issue, this was just a false alarm.

Since `echo $(which /usr/libexec/platform-python 2>/dev/null || which python3 2>/dev/null || which python)` returned python3 our script will run with python3 which is correct and should make it work.

So if you want to try debugging it more with our help, maybe #cockpit on freenode (where we all devs from here are) is a better place because this is not straightforward to figure out.

**Comment by KKoukiou** [comment] 2021-02-22 08:01
So I will close this issue since we don't continue the discussion here and it's something specific to your server state @tavoc, I am happy to help you more on IRC if needed.

For clarification for people who read the issue in the future, cockpit-machines OS dropdown in the dialog, is expected to work normally even on systems with python2 default, if python3 is installed of course.

**Closed by KKoukiou** 2021-02-22 08:01 UTC
Labels: page:machines

**Comment by tavoc** [comment] 2021-02-22 09:52
@KKoukiou thanks. I will try to join the channel if I find time. 
I can confirm, that it seems like a specific problem. Removing python2 did not help. 

Thx

**Comment by netzen86** [comment] 2023-11-04 15:46
I'm getting this error too. I fixed it by installing these components:
sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0
pip3 install pycairo
pip3 install PyGObject

My OS Debian GNU/Linux 12.

**Comment by martinpitt** [comment] 2023-11-06 05:07
For everyone else following along -- Installing packages via `pip` **is not necessary** and **not a bug fix**. You potentially break unrelated software by doing this. Nor are the development packages necessary. There is possibly some missing dependency here, but `sudo apt install gir1.2-libosinfo-1.0` should be sufficient. (It's a recommends of cockpit-machines for good reasons)
