### ISSUE TITLE
Notify when the system goes down for reboot

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1153] opened 2014-09-10 16:33 UTC
Usecase: Me and my friend Kalev administers a bunch of servers together. If I'm in the middle of something and Kalev decides to reboot the machine for some reason, it would be good to get a notification about this. A heads up. Related to issue #1134

**Comment by martinpitt** [comment] 2019-01-11 08:12
Still valid. We need to find something subscribable similar to the `wall` message that a scheduled shutdown sends around, maybe systemd has something.

**Comment by marusak** [comment] 2019-11-05 09:45
I believe this is duplicate of #2468 (I know, the other way around, but I decided to close this as the othe one has more discussion and some mockups)

**Closed by marusak** 2019-11-05 09:45 UTC
Labels: enhancement, review-2019-10
