### ISSUE TITLE
"Installation source must not be empty" bug?

### ISSUE THREAD

**Issue by MDail4900** [cockpit-project/cockpit#19795] opened 2024-01-01 16:42 UTC
### Explain what happens

Using Cockpit on Ubuntu to monitor/manage KVM hosts.  When I attempt to create a new VM using Cockpit, all goes well until I try to enter the "Installation source" to point to local ISO image.  

I enter the path to the ISO, and the following field, Operating system, correctly shows the ISO image.  But when I attempt to create the VM an error is displayed under the "Installation source" stating "Installation source must not be empty."  See attached image.

![Untitled](https://github.com/cockpit-project/cockpit/assets/155380971/b6ce0fa3-765a-4dd8-b3c3-ba3bf994dee2)

Is this a bug, or a configuration issue?  This is my first time using Cockpit, so if I've borked something, please point me in the right direction.

### Where is the problem in Cockpit?

None

### Server operating system

Ubuntu

### Server operating system version

ubuntu-22.04.3

### What browsers are you using?

Firefox

**Comment by subhoghoshX** [comment] 2024-01-02 09:01
Looks like a duplicate of #19793

**Comment by martinpitt** [comment] 2024-01-02 09:34
Right, it is. Plus, this needs to go against cockpit-machines, I'll transfer the other one.

Duplicate of #19793

**Closed by martinpitt** 2024-01-02 09:34 UTC
Labels: bug
