### ISSUE TITLE
Safari Incompatability

### ISSUE THREAD

**Issue by nthisler** [cockpit-project/cockpit#3640] opened 2016-01-29 17:20 UTC
I have tried to access the Cockpit web interface from multiple versions of Safari and keep getting the message "Server has closed the connection".  This same behavior occurs on OSX 10.11 El Capitan both on version 10.11.3 and 10.11.4beta.  This also happens on an iPhone 6S Plus on iOS 9.2.1 and an iPad Pro on 9.3 beta 2.  However on the 2 Macs tested, switching to Chrome resolved the issue.  On the two iOS devices using Chrome didn't affect the outcome (Chrome on iOS is required to use the Safari Web View...so this was expected).

**Comment by Endogen** [comment] 2016-02-05 22:16
I have the same problem. Would like to use cockpit with Safari but since i have installed version 0.77 (on CentOS 7 from extras repo) and there is something wrong with the https stuff, i can only connect to cockpit via Chrome. I think Safari blocks non https connections in this case(?).

It should be possible to disable SSL for cockpit if you with to use it with Safari. See [here](https://jreypo.wordpress.com/2015/01/09/how-to-install-cockpit-on-centos-7/)

**Comment by petervo** [comment] 2016-02-17 17:12
Safari doesn't support self-signed certificates over wss. Users need to either install a known ca issued certificate or disable tls.

@andreasn do we think we should design a message for this or just document it clearly somewhere?

**Comment by andreasn** [comment] 2016-02-17 19:25
We might as well document there and then in the browser if we can.
Do they have to disable tls alltogether, or only for that particular address/port?

**Comment by petervo** [comment] 2016-02-17 19:27
They need to disable tls in cockpit, the --no-tls flag. But really a proper certificate is the better fix.

**Comment by Endogen** [comment] 2016-02-17 19:37
I have a free Let's Encrypt certificate and have that problem with Safari. Is the normal? I would expect cockpit to work with that.

**Comment by petervo** [comment] 2016-02-17 19:41
@Endogen, is it trusted by your system and did you include the chain in the certificate file?

**Comment by Endogen** [comment] 2016-02-17 20:10
I honestly have to say that i don't know. All i know is that my server is now accessible via https and i followed the Let's Encrypt install guide. Meaning, i got this message `No installers are available on your OS yet; try running "letsencrypt-auto certonly" to get a cert you can install manually` which is ok because i use CentOS and there is no automatic installer. So i executed `letsencrypt-auto certonly`, configured virtual hosts, restarted the apache service and that's it.

**Comment by marmeladema** [comment] 2016-04-13 07:40
I have the same problem with a letsencrypt certificate using chromium on debian 8
> Server has closed the connection

But it works with firefox and I'm using the same certificate for other services on the same host with nginx and it works fine with every browers i've tested. It seems to be a problem related to cockpit, not to the certificate.

The certificate incluses my cert, letsencrypt intermediate ca cert and my private key, in this order. I tried to shuffle things around but then, it never works on any browser.

**Comment by igorSmirnovPlexi** [comment] 2016-07-17 08:13
Is any solution for this behaviour, except --no-tls flag?

**Comment by petervo** [comment] 2016-07-18 01:49
The solution should be to use a valid trusted certificate. @igorSmirnovPlexi are you trying with a self-signed cert or Let's Encrypt?

**Comment by rhwood** [comment] 2016-08-13 10:56
If it's of any interest, I created certificates using Let's Encrypt using the following commands:
```
sudo firewall-cmd --add-port=443/tcp
sudo letsencrypt certonly --standalone -d $( hostname )
sudo cat /etc/letsencrypt/live/$( hostname )/fullchain.pem /etc/letsencrypt/live/$( hostname )/privkey.pem > $( hostname ).cert
sudo cp $( hostname ).cert /etc/cockpit/ws-certs.d/
sudo chown root:cockpit-ws /etc/cockpit/ws-certs.d/$( hostname ).cert 
sudo chmod 640 /etc/cockpit/ws-certs.d/$( hostname ).cert
sudo firewall-cmd --remove-port=443/tcp
```
Some notes:
- I use Safari as my primary browser
- The system I use is not running a service on port 443. If you have a service running on that port, stop and start that service instead

**Comment by munkale** [comment] 2017-03-23 07:28
Had this issue and solved it this way:
1. Installed self-signed or iOS-untrusted Cockpit SSL certificate on iOS (if you have a certificate from a trusted authority you don't need to do this)
2. Ensured the URL that Safari used to browse to Cockpit matched the URL in the certificate (of your server is called "host.domain" the certificate will be issued with that name, hence the URL in Safari must match "host.name" for Safari to accept the connection)

**Comment by garrett** [comment] 2017-09-27 12:33
Epiphany also has the same issue. It shows a blank page after signing in, without any visible issues, unless one looks in the development tools.

The dev console states:

_WebSocket network error: Unacceptable TLS certificate_ 
...and then there are a bunch of issues loading resources (due to rejecting the certificate).

**Comment by petervo** [comment] 2017-09-27 12:57
This is because safari doesn't let you 'proceed anyways' for websocket connections. So this is only an issue with untrusted certs. And not one that we can fix.

**Comment by garrett** [comment] 2017-09-27 16:39
It's worth noting that this issue breaks browsing from iOS (iPhone & iPad) devices as well, as all the browsers on iOS depend on WebKit. This even includes third-party browsers, such as Firefox for iOS (as iOS has a restriction on web engines used).

Until it is fixed, we might want to somehow message the issue, probably checking if WebSockets work and show an appropriate error message if not. (If we can detect it is a cert issue, try to at least mention it... and have some sort of fix or workaround mentioned, if possible.)

**Comment by iGeorgeX** [comment] 2017-09-27 17:11
Well with Safari 11 klick on "View Details" and then "visit this Website" and you are down... and with Safari < 11 add the Certificate to the Keychain and you are down.

**Comment by garrett** [comment] 2019-01-10 09:42
As @iGeorgeX mentions, Safari has since been fixed to allow self-signed certs — even for wss. Also, thanks for confirming it works on iOS 11 too!

Locally, I confirmed working here on Safari 11.1.2 on OS X 10.11.6 and also on Epiphany 3.30. (It's worked on both my very old MacBook Pro and on Epiphany for quite some time now. I've tested a bunch of Cockpit-related things in Safari & Epiphany for at least a year or two.)

Sorry for closing this bug a bit late; it was a bit of an oversight. Better late than never, right? :wink:

**Closed by garrett** 2019-01-10 09:42 UTC
