### ISSUE TITLE
Software Updates: Show history

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7063] opened 2017-06-21 10:50 UTC
During usability testing, a lot of the participants were looking for which packages were recently updated. They often upgraded first and then checked service logs etc. for errors/messages, but it's difficult to remember which packages/services were affected.

PackageKit does provide that information (check `pkcon get-transactions`), but no changelogs, just names/versions. It also gives us the entire history, not just the last update, so we should probably cut that off in some sensible manner.

At least this should be shown in the "System is up to date" state, where we have plenty of screen real estate. I wouldn't want to mix it  with the "Available updates" table, it might be too confusing/cluttering. This should mostly be fine except for the cases where one installs only security updates - then history plus available packages makes sense. Perhaps with an expander?

CC @garrett, @andreasn

**Comment by martinpitt** [comment] 2017-06-21 13:31
![](https://github.trello.services/images/mini-trello-icon.png) [OS updates: reboot required detection](https://trello.com/c/8F1d2nOk/517-os-updates-reboot-required-detection)

**Comment by garrett** [comment] 2017-06-22 16:01
Here's an updates changelog:

![progress log](https://raw.githubusercontent.com/cockpit-project/cockpit-design/d534abb44b2334db992c413821123ccac28cc5ea/software-updates/software-updates-packages-progress-log.png)

It basically is a log of what happens in above the progress bar (or it could just be the ongoing output of `pkgcon`). It would be collapsed by default. 

When it's shown, that state should be saved somehow (to the user or in a cookie or something) so it is remembered for next time. Also, the same collapse/expand state should also apply for when it's time to reboot.

---

I added an information toggle to display packages on the reboot screen;

![suggestion-info](https://raw.githubusercontent.com/cockpit-project/cockpit-design/5de9253718ef30238d506afae4d5685877ab6d5a/software-updates/software-updates-packages-upgrade-suggestion.png)

![suggestion-info-expanded](https://raw.githubusercontent.com/cockpit-project/cockpit-design/5de9253718ef30238d506afae4d5685877ab6d5a/software-updates/software-updates-packages-upgrade-suggestion-expanded.png)

---

In the updated view, I had an earlier draft with more details (version numbers):

![](https://raw.githubusercontent.com/cockpit-project/cockpit-design/d04b950b71d784e577025b682f87a5fb9368e50c/software-updates/software-updates-packages-noupdates.png)

But I changed it to this (removed the versions and collapsed the list to make more space — needed when there are a ton of packages):

![](https://raw.githubusercontent.com/cockpit-project/cockpit-design/f0e4d3c568f29634e2441553f94d4744a520bd91/software-updates/software-updates-packages-noupdates.png)

We could change the package names to blue to click to get more details, but I guess the only details we would know would be the version number, right?

Also: Should I add the date the update was performed?

---

In parallel (and one of the reasons for the change to simplify the summary), I made a mockup of how it would look in the package updates overview when there are pending packages to update:

![with updates & history](https://raw.githubusercontent.com/cockpit-project/cockpit-design/d534abb44b2334db992c413821123ccac28cc5ea/software-updates/software-updates-packages-merged.png)

It's the same summary as the simplified one above, except:

- left-aligned
- outside of the parent element's max-width constraint
- with a link for viewing all the history (which should appear on the updated view — oops! I'll update that soon)

---

These are WIPs, and we should _probably_ converge the lists a little more where applicable. That is: if versions are cared about in one place — are they cared about in all places? Or does this look pretty good so far?

**Comment by martinpitt** [comment] 2017-06-23 10:51
Thanks @garrett, these look nice already! Some questions/remarks:

 * "When it's shown, that state should be saved somehow (to the user or in a cookie or something) so it is remembered for next time." - What do you mean with "next time"? If you log out and back in and it resumes watching the ongoing update? The only place to store that information would be PackageKit itself, but it doesn't currently provide that. Of course one would see the log since resuming the upgrade view. But I'm not sure this corner case is worth putting major changes into PackageKit (aside from the fact that it wouldn't  be available on existing stable releases anyway).

 * To be honest I don't like the horizontal enumeration of packages a lot, it somehow looks untidy: package names tend to vary a lot in length, so there is no vertical alignment if they span multiple lines. I bow to your judgement, but I at least wanted to bring it up.

 * If we keep the horizontal package list: I wouldn't make them full links as there's not much to show; but we could show the package version in a tooltip.

 * Update history: I'd like to show the actual date/time instead of "recently". This would then also be consistent with "View all updates...".

 * Update history, "View all updates": should this be a new page, or just an expander that opens the earlier ones?

**Comment by garrett** [comment] 2017-07-04 16:34
I'm working on HTML demos to play around with how it'd look with lots of packages.

So far, I have the following:

- Big long list with versions: http://garrettlesage.com/cockpit-mockweb/updates/list
- Same as above, but scrolly in-page: http://garrettlesage.com/cockpit-mockweb/updates/list-scroll
- A "flow list" with just the names: http://garrettlesage.com/cockpit-mockweb/updates/flow

The third one, the "flow list", is like the names-only mockup above. The trick was to make some CSS That would allow it to work as intended and not make a huge mess (as you've seen). It still works when you resize the browser or relax the max-width on its ancestor's container.

(Perhaps, tomorrow, I should make a relaxed mode so the same HTML & CSS could be used on the overview page too.)

**Comment by martinpitt** [comment] 2017-07-06 10:33
@garrett: Thanks for figuring this out! Your CSS for "flow list" looks by and large great, I just added a `font-weight` to match the design:

![flow](https://user-images.githubusercontent.com/200109/27907145-bdc8bc76-6246-11e7-973a-dd2c73e34002.png)

For testing I reduced the `<li>` width to 20ex to see the ellipsizing:

![flownarrow](https://user-images.githubusercontent.com/200109/27907175-e05173d2-6246-11e7-9f15-cdf3f8b423c2.png)

It now only looks wrong if the number of items is not divisible by the number of columns. This isn't predictable well as it depends on the window width, so I can't just fill up with empty `<li>`s. I think overall it looks better if I move the `.flow-list` to `text-align: left` - then single-item lists look a bit odd, but multi-line lists are properly aligned then:

![flownarrowleft](https://user-images.githubusercontent.com/200109/27907236-2bc54320-6247-11e7-84f7-ceab53b79512.png)

(Of course I'll crank it back to 30ex per item). Do you agree?

**Comment by garrett** [comment] 2017-07-06 10:48
Oh, I have it aligned to center to make the whole thing center. When aligned to the left, it's off. My testing set had a round number though, so, yeah, I didn't see the last line being off.

Thanks for making it match the mockup — I was racing against the clock to get the HTML mockup out and omitted the boldness! :wink:

Hmm; I wonder if we can use a little more CSS to make the list centered but have the not-quite-full line left-aligned.

**Comment by garrett** [comment] 2017-07-06 14:33
So I was playing around with the mockup (with flexbox and what-not) to try to make it handle the more generic cases, but in the end, I couldn't find the perfect version of the columns that wrap across that would auto-center. The best thing to do is have the widths of the elements be exactly ⅓ of the container (with the max-width), or to have the container exactly 3× the width of the elements. It's basically the same thing, but you'll probably have whole numbers instead.

To get the exact same sizes, I'd suggest using rem units at the approximate width, so it's based on typography (of the page), but it's not relative to the font-size in use.

**Comment by garrett** [comment] 2017-07-06 14:34
But, yeah, overall: looks really great, and I agree the block should be centered, but the text should be left-aligned.

**Closed** 2017-07-12 14:04 UTC
