### ISSUE TITLE
Tests failed on 132300e09cc45cbd8f3b2aec760b1b213ae40d85

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21273] opened 2024-11-15 02:27 UTC
The job `fedora-40/updates-testing` failed on commit 132300e09cc45cbd8f3b2aec760b1b213ae40d85.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-132300e0-20241115-013150-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-15 06:04
Duplicate of #21237

**Closed by martinpitt** 2024-11-15 06:04 UTC
Labels: nightly
