### ISSUE TITLE
Unable to get 'rhost' client ip in auth.log to make Fail2Ban custom jail/filter

### ISSUE THREAD

**Issue by blephy** [cockpit-project/cockpit#15760] opened 2021-04-29 10:22 UTC
Cockpit version: 215
OS:
```shell
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

I'm trying to make a specific fail2ban filter for Cockpit web UI. It's seems like cockpit-session is logging in the `/var/log/auth.log`. But i'm unable to see the rhost value (client ip) in the log line.

> My server, which run cockpit, is behind a router with port forwarding. This port is allowed in the firewall (ufw). The cockpit web UI is accessible from internet by a personal domain (home.mydomaine.com).

When i tried to make invalid session (with unexistant root account) in the web UI to see log line in `auth.log`, i saw that :  

```txt
Apr 29 12:02:03 blephy-server cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Apr 29 12:02:25 blephy-server cockpit-session: pam_unix(cockpit:auth): check pass; user unknown
Apr 29 12:02:25 blephy-server cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=
```

Is this normal ?

I searched on repository issues and saw some logs which include ip. So, what's wrong ?

I first thought this was because my client was using a VPN, but stopping the VPN does not change anything

Regards,

**Comment by marusak** [comment] 2021-04-30 07:25
Please see https://github.com/cockpit-project/cockpit/issues/722 (second to last comment).
We track this internally so closing as duplicate of https://github.com/cockpit-project/cockpit/issues/722

**Closed by marusak** 2021-04-30 07:25 UTC
