### ISSUE TITLE
Tests failed on fa8d9c1e6cb568af529c08c5b9bc221080eaf7a4

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21057] opened 2024-10-01 03:10 UTC
The job `fedora-40/updates-testing` failed on commit fa8d9c1e6cb568af529c08c5b9bc221080eaf7a4.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-fa8d9c1e-20241001-013137-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-01 04:15
Duplicate of #21048

**Closed by martinpitt** 2024-10-01 04:15 UTC
Labels: nightly
