### ISSUE TITLE
cockpit.service fails to start because cockpit-certificate-ensure returns error

### ISSUE THREAD

**Issue by Procsiab** [cockpit-project/cockpit#16652] opened 2021-11-26 09:52 UTC
**Cockpit version**: 257-1
**OS**: Fedora IoT AARCH64 35.20211118.0
**cockpit-certificate-ensure**: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=fefe3baa8650fc38840f8149f7218faae5b07bba, for GNU/Linux 3.7.0, stripped

_Description_
Upon attempting the connection to the Cockpit web interface, the cockpit.service exits with an error code and cannot be restarted.
Below I attached the reference of the error found in the log files.

_Journal logs_
`journalctl -fu cockpit.service`
```
Nov 26 10:12:34 canopus systemd[1]: Starting Cockpit Web Service...
Nov 26 10:12:35 canopus cockpit-certificate-ensure[3021]: cockpit-certificate-ensure: mkdir: /run/cockpit/tls/server: File exists
Nov 26 10:12:35 canopus systemd[1]: cockpit.service: Control process exited, code=exited, status=1/FAILURE
Nov 26 10:12:35 canopus systemd[1]: cockpit.service: Failed with result 'exit-code'.
Nov 26 10:12:35 canopus systemd[1]: Failed to start Cockpit Web Service.
```
_Reproduce it_

1. Install Fedora IoT version 35.20211118.0 for ARM 64bit
2. Enable and start cockpit.service
3. Connect to cockpit's web interface
4. Log out and wait until the service is stopped again
5. Try to log in a second time
6. The service will fail to start

_Workaround_
This is my quick and dirty workaround to be able to avoid this issue: since the binary `cockpit-certificate-ensure` gives an error on the runtime directory `/run/cockpit/tls/server`, I added an ExecStop line to the cockpit.service unit to delete that particular folder.
I'm not aware of the inner workings of this application, so this may be a terrible idea, however this fixes it for me.
My custom systemd unit looks like the following (I put it into `/etc/systemd/system`):

```
# /usr/lib/systemd/system/cockpit.service
[Unit]
Description=Cockpit Web Service
Documentation=man:cockpit-ws(8)
Requires=cockpit.socket
Requires=cockpit-wsinstance-http.socket cockpit-wsinstance-http-redirect.socket cockpit-wsinstance-https-factory.socket
After=cockpit-wsinstance-http.socket cockpit-wsinstance-http-redirect.socket cockpit-wsinstance-https-factory.socket

[Service]
RuntimeDirectory=cockpit/tls
# systemd ≥ 241 sets this automatically
Environment=RUNTIME_DIRECTORY=/run/cockpit/tls
ExecStartPre=+/usr/libexec/cockpit-certificate-ensure --for-cockpit-tls
ExecStart=/usr/libexec/cockpit-tls
ExecStop=/usr/bin/sh -c 'rm -rf /run/cockpit/tls/server || echo "cockpit tls/server runtime folder not present"'
User=cockpit-ws
Group=cockpit-ws
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
ProtectKernelTunables=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
MemoryDenyWriteExecute=true
```

**Comment by martinpitt** [comment] 2021-11-28 12:16
This was fixed in commit 25259205b7012bf71360ce1639b95c66448ed2eb and released in 258. That update is still [stuck in updates-testing](https://bodhi.fedoraproject.org/updates/FEDORA-2021-0f278d8cbd) due to a bodhi/gating bug, though -- I nudged it a bit.

**Closed by martinpitt** 2021-11-28 12:16 UTC

**Comment by ThubLives** [comment] 2022-10-01 02:35
I ran into this exact problem on Fedora Server 36 x86_64 (Cockpit version 276.1).  I had a look at commit 2525920 and I don't understand how proper detection of SELinux has anything to do with this error and how this has been fixed.

FWIW, @Procsiab's systemd unit workaround is working for me.

**Comment by martinpitt** [comment] 2022-10-01 05:39
@ThubLives : Do you get an SELinux AVC denial when starting the unit? Note that you will *not* see this in `journalctl -fu cockpit.service`, but they should appear in the unfiltered log. Please copy&paste the output of `sudo journalctl -f` and then try to start the unit.

What does `sudo semodule -lfull |grep cockpit` show for you?

As your unit extension hack worked, it's probably the same root cause, but then we need to know how it failed -- i. e. what went wrong on package installation.

**Comment by ThubLives** [comment] 2022-10-03 19:12
No, in fact I've turned on Permissive mode due to a relabelling debacle and I haven't changed it back.  I don't see any related AVC message in any case.
