### ISSUE TITLE
rpmbuild --rebuild creates two packages, what causes blocking of installation

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#3417] opened 2016-01-05 11:44 UTC
I have recent master from git, I've done ../tools/make-srpm then rpmbuild --rebuild cockpit-wip*src.rpm and then trying to install compiled packages, but without success. My machine is F23, there are two issues, first is that there are compiled two packages: Error: cannot install both
cockpit-shell-wip-1.fc23.noarch and cockpit-shell-wip-0.1.noarch
and in case I've excluded one it shows:  
file /usr/share/polkit-1/rules.d from install of cockpit-test-assets-wip-1.fc23.x86_64 conflicts with file from package polkit-0.113-4.fc23.x86_64

**Comment by stefwalter** [comment] 2016-01-05 12:54
I've opened a pull request for the latter issue. For the first issue, I can't reproduce. You likely have files laying around from before the build in your rpmbuild output tree. If that's not the case, could you post verbose build output?

**Comment by jscotka** [comment] 2016-01-05 13:35
Hi,
yea, seems like that, 
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-bridge-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-doc-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-pcp-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-ws-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-debuginfo-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/noarch/cockpit-shell-wip-1.fc23.noarch.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/noarch/cockpit-sosreport-wip-1.fc23.noarch.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/noarch/cockpit-storaged-wip-1.fc23.noarch.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/noarch/cockpit-subscriptions-wip-1.fc23.noarch.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/noarch/cockpit-networkmanager-wip-1.fc23.noarch.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-docker-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-kubernetes-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-ostree-wip-1.fc23.x86_64.rpm
Wrote: /home/jscotka/rpmbuild/RPMS/x86_64/cockpit-test-assets-wip-1.fc23.x86_64.rpm

so probably I had there one old package from previous testing.

**Comment by stefwalter** [comment] 2016-01-06 07:02
This should be fixed now that a81a08bbc9af7bbc0133b51bc4d66abc719af601 has been merged.

**Closed by stefwalter** 2016-01-06 07:02 UTC
