### ISSUE TITLE
Loading of units failed (system)

### ISSUE THREAD

**Issue by potens1** [cockpit-project/cockpit#17899] opened 2022-11-10 10:31 UTC
### Explain what happens

On Arch Linux, cockpit version 279-1, loading the **system** units always results in

`Loading unit failed: The maximum number of pending replies per connection has been reached`

This is what I see in dbus logs:

[system] The maximum number of pending replies for ":1.57" (uid=0 pid=3415 comm="cockpit-bridge --privileged") has been reached (max_replies_per_connection=128)

```sh
busctl |grep 1.57
:1.57                      3415 cockpit-bridge  root             :1.57         session-6.scope           6       -
```

I guess I can push `max_replies_per_connection` to 256 or any number, in dbus configuration (default one, right now, not existing), but is this something desired ?

### Version of Cockpit

279-1

### Where is the problem in Cockpit?

Services

### Server operating system

Arch Linux

### Server operating system version

updated on 20221110

### What browsers are you using?

Firefox

### System log

```shell
dbus-daemon[401] [system] The maximum number of pending replies for ":1.57" (uid=0 pid=3415 comm="cockpit-bridge --privileged") has been reached (max_replies_per_connection=128) 

repeated ≃90 times.
```

**Comment by KKoukiou** [comment] 2022-11-15 12:11
This is a duplicate of https://github.com/cockpit-project/cockpit/issues/1649#issuecomment-1305250921

**Closed by KKoukiou** 2022-11-15 12:11 UTC
Labels: bug
