### ISSUE TITLE
Unable to connect to remote server when the remote server has hardened SSH algorithms

### ISSUE THREAD

**Issue by stephane-martin** [cockpit-project/cockpit#8733] opened 2018-03-01 01:36 UTC
Hi,

My servers are configured with custom SSH algorithms for encryption, key exchange, etc.

When I try to add remote hosts in cockpit, it fails ("unable to connect").

```
cockpit-ssh-Message: cockpit-ssh ***: -1 couldn't connect: kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160], client [hmac-sha1] '***' '22'
```

I grokked the source a bit, but I can't seem to find a way to configure cockpit to tell libssh to use other algorithms than the default hmac-sha1 for kex. (Should probably be done with SSH_OPTIONS_KEY_EXCHANGE in ssh_options_set.)

Thank you

**Comment by dwebber** [comment] 2018-04-16 23:06
I'm having the same issue from an Ubuntu 16.04 machine using the 16.04 package.

    1.  Is there a way to configure Cockpit to use the OpenSSH client on host running cockpit?

    2.  If no to #1, and I'm assuming that cockpit-ssh is an OpenSSH derivative, what is the OpenSSH version cockpit-ssh  is derived from so that I can add a limited number of MACs, KexAlgorithms, and Ciphers to the remote hosts per the remote server security requirements.

**Comment by Nebucatnetzer** [comment] 2018-12-17 19:43
I'm getting the same error. Is there a workaround for this other than weakening the SSH?

**Comment by martinpitt** [comment] 2019-02-15 16:52
It's possible that this was fixed with newer libssh versions. cockpit-ssh leaves all the protocol negotation (as well as the ssh protocol at large) to libssh.

**Comment by Nebucatnetzer** [comment] 2019-02-15 19:51
I don't think it's working. I just reinstalled it quickly and wasn't able to connect to my servers. The connection from the management server to the less secure desktop system worked however.
Can someone tell me where the log files are so that I can check it for sure? I forgot where they are stored.

**Comment by ebal** [comment] 2019-06-23 09:32
Just to provide some extra feedback/analysis on the issue/problem:

disclaimer `1.2.3.4:2222` is just for notes, not the actual server/port

```
Jun 22 20:31:54 cockpit cockpit-ssh[3506]: cockpit-ssh 1.2.3.4:2222:
 -1 couldn't connect: kex error : no match for method kex algos: server 
[diffie-hellman-group-exchange-sha256], client [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1]
 '1.2.3.4' '2222'
```

ssh seems to work 

`ssh 1.2.3.4 -p 2222`

but not cockpit-ssh

`$ /usr/libexec/cockpit-ssh 1.2.3.4:2222`

```
73

{"command":"authorize","challenge":"*","cookie":"session35751561224805"}

cockpit-ssh-Message: 20:33:29.632: couldn't read control message: Bad message
cockpit-ssh-Message: 20:33:29.854: cockpit-ssh 1.2.3.4:2222: -1 couldn't connect: kex error : no match for method kex algos: server [diffie-hellman-group-exchange-sha256], client [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1] '1.2.3.4' '2222'

82

{"command":"init","problem":"no-host","error":"no-host","auth-method-results":{}}

```

I believe the issue is with libssh which I dont see **diffie-hellman-group-exchange-sha256** support

```
$ ldd /usr/libexec/cockpit-ssh | egrep -i ssh
	libssh.so.4 => /lib64/libssh.so.4 (0x00007f5f3dc95000)
```


```
$ strings /lib64/libssh.so.4  | egrep -i sha

EVP_sha384
EVP_sha256
EVP_sha512
EVP_sha1
Invalid state in dh_handshake(): %d
dh_handshake
SHA1
SHA256
 SHA512
rsa-sha2-512
ecdsa-sha2-nistp521
diffie-hellman-group1-sha1
diffie-hellman-group14-sha1
diffie-hellman-group16-sha512
diffie-hellman-group18-sha512
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521
curve25519-sha256@libssh.org
curve25519-sha256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp256
curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss
hmac-sha2-256,hmac-sha2-512,hmac-sha1
Only RSA keys support non-SHA1 hashes.
hmac-sha1
hmac-sha2-256
hmac-sha2-512
,rsa-sha2-512,rsa-sha2-256
dh_handshake_server
```

The destination server is a CentOS with hardering ssh configuration 

```json
$ python -m sshsec 1.2.3.4 -p 2222|jq .
{
  "gex": {
    "1024": {
      "g": 2,
      "p": 1.7976931348623157e+308
    },
    "2048": {
      "g": 2,
      "p": 1.7976931348623157e+308
    },
    "3072": {
      "g": 2,
      "p": 1.7976931348623157e+308
    },
    "4096": {
      "g": 5,
      "p": 1.7976931348623157e+308
    },
    "6144": {
      "g": 2,
      "p": 1.7976931348623157e+308
    },
    "768": "EOF",
    "8192": {
      "g": 2,
      "p": 1.7976931348623157e+308
    }
  },
  "host_keys": {
    "ssh-rsa": {
      "algorithm": "ssh-rsa",
      "ascii": "AAAXXXXXXXXYYYYYYYYYYYY==",
      "e": 35,
      "fingerprint": "82:cb:ad:64:4e:cd:c0:51:f0:74:a6:ce:6a:95:e7:a3",
      "n": 1.7976931348623157e+308
    }
  },
  "ident": "SSH-2.0-OpenSSH_5.3",
  "ip": "1.2.3.4",
  "supported": {
    "compression_algorithms_client_to_server": [
      "none",
      "zlib@openssh.com"
    ],
    "compression_algorithms_server_to_client": [
      "none",
      "zlib@openssh.com"
    ],
    "encryption_algorithms_client_to_server": [
      "aes128-ctr",
      "aes192-ctr",
      "aes256-ctr"
    ],
    "encryption_algorithms_server_to_client": [
      "aes128-ctr",
      "aes192-ctr",
      "aes256-ctr"
    ],
    "kex_algorithms": [
      "diffie-hellman-group-exchange-sha256"
    ],
    "languages_client_to_server": [
      ""
    ],
    "languages_server_to_client": [
      ""
    ],
    "mac_algorithms_client_to_server": [
      "hmac-sha2-256",
      "hmac-sha2-512"
    ],
    "mac_algorithms_server_to_client": [
      "hmac-sha2-256",
      "hmac-sha2-512"
    ],
    "server_host_key_algorithms": [
      "ssh-rsa"
    ]
  }
}
```

But **libssh2** has such support for **diffie-hellman-group-exchange-sha256**

```
# rpm -qa | grep -i libssh
libssh-0.8.7-1.fc30.x86_64
libssh2-1.8.2-1.fc30.x86_64
```

```
# strings /usr/lib64/libssh2.so.1 | grep sha

EVP_sha1
EVP_sha512
EVP_sha256
libssh2_session_handshake
diffie-hellman-group14-sha1
diffie-hellman-group1-sha1
diffie-hellman-group-exchange-sha256
diffie-hellman-group-exchange-sha1
hmac-sha1-96
hmac-sha1
hmac-sha2-256
hmac-sha2-512
sha256
```

**Comment by martinpitt** [comment] 2019-11-13 08:23
I tested this on current Fedora 31, with libssh 0.9.0. I configure sshd to start with `-oKexAlgorithms=diffie-hellman-group-exchange-sha256`, that's the one you apparently used above. `ssh -vv localhost` confirms that it's being used:

    debug1: kex: algorithm: diffie-hellman-group-exchange-sha256

`/usr/libexec/cockpit-ssh localhost` works fine. I was also doing this with a "full connection":

```
# cockpit-bridge --interact=---

{ "command": "open", "channel": "c", "payload": "echo", "host": "m1.cockpit.lan", "user": "admin" }
---

{"command":"authorize","challenge":"*","cookie":"session246661573633246"}
---

{"command":"authorize", "response": "password foobar", "cookie":"session246661573633246"}
---

{"command":"ready","channel":"c"}
---
```

So I'm closing this, as availability of key exchange algorithms is a libssh/distro thing, outside of cockpit upstream.

**Closed by martinpitt** 2019-11-13 08:23 UTC
Labels: review-2019-10
