### ISSUE TITLE
Blank page after login with Apache reverse proxy

### ISSUE THREAD

**Issue by ccaceres** [cockpit-project/cockpit#15651] opened 2021-04-05 13:01 UTC
Hi,

My installation shows the javascript error on the login page:
VM456:1 GET https://host.recao.app/cockpit/login 401 (Authentication failed)

**My apache conf host file**
<IfModule mod_ssl.c>
<VirtualHost *:443>
  ServerName host.recao.app
  SSLCertificateFile /etc/letsencrypt/live/host.recao.app/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/host.recao.app/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf

  ProxyPreserveHost On
  ProxyRequests Off

  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://127.0.0.1:9090/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://127.0.0.1:9090/$1 [P,L]

  ProxyPass / http://127.0.0.1:9090/
  ProxyPassReverse / http://127.0.0.1:9090/

</VirtualHost>
</IfModule>

**journalctl --since -1m**
-- Logs begin at Fri 2021-04-02 20:26:22 UTC, end at Mon 2021-04-05 12:49:42 UTC. --
Apr 05 12:49:42 recao.app systemd[1]: Starting Cockpit Web Service...
Apr 05 12:49:42 recao.app systemd[1]: Started Cockpit Web Service.
Apr 05 12:49:42 recao.app cockpit-ws[6885]: Using certificate: /etc/cockpit/ws-certs.d/host.recao.app.cert
Apr 05 12:49:42 recao.app cockpit-session[6889]: pam_ssh_add: Failed adding some keys
Apr 05 12:49:42 recao.app cockpit-session[6889]: pam_unix(cockpit:session): session opened for user recao by (uid=0)
Apr 05 12:49:42 recao.app systemd[1]: Created slice User Slice of recao.
Apr 05 12:49:42 recao.app systemd[1]: Starting User Manager for UID 1000...
Apr 05 12:49:42 recao.app systemd[6904]: pam_unix(systemd-user:session): session opened for user recao by (uid=0)
Apr 05 12:49:42 recao.app systemd-logind[924]: New session 22 of user recao.
Apr 05 12:49:42 recao.app systemd[1]: Started Session 22 of user recao.
Apr 05 12:49:42 recao.app systemd[6904]: Reached target Paths.
Apr 05 12:49:42 recao.app systemd[6904]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Apr 05 12:49:42 recao.app systemd[6904]: Listening on GnuPG network certificate management daemon.
Apr 05 12:49:42 recao.app systemd[6904]: Reached target Timers.
Apr 05 12:49:42 recao.app systemd[6904]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Apr 05 12:49:42 recao.app systemd[6904]: Listening on REST API socket for snapd user session agent.
Apr 05 12:49:42 recao.app systemd[6904]: Listening on GnuPG cryptographic agent and passphrase cache.
Apr 05 12:49:42 recao.app systemd[6904]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Apr 05 12:49:42 recao.app systemd[6904]: Reached target Sockets.
Apr 05 12:49:42 recao.app systemd[6904]: Reached target Basic System.
Apr 05 12:49:42 recao.app systemd[1]: Started User Manager for UID 1000.
Apr 05 12:49:42 recao.app systemd[6904]: Reached target Default.
Apr 05 12:49:42 recao.app systemd[6904]: Startup finished in 42ms.
Apr 05 12:49:42 recao.app polkitd(authority=local)[977]: Registered Authentication Agent for unix-session:22 (system bus name :1.59 [cockpi
Apr 05 12:49:42 recao.app cockpit-ws[6885]: logged in user session
Apr 05 12:49:42 recao.app cockpit-bridge[6915]: invalid or unusable locale: en_GB.UTF-8

**My ws-folder**: /etc/cockpit/ws-certs.d# ls
host.recao.app.cert  update-cert.sh

**apt show -a cockpit**
Package: cockpit
Version: 215-1~ubuntu18.04.1
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 63.5 kB
Depends: cockpit-bridge (>= 215-1~ubuntu18.04.1), cockpit-ws (>= 215-1~ubuntu18.04.1), cockpit-system (>= 215-1~ubuntu18.04.1)
Recommends: cockpit-storaged (>= 215-1~ubuntu18.04.1), cockpit-networkmanager (>= 215-1~ubuntu18.04.1), cockpit-dashboard (>= 215-1~ubuntu18.04.1), cockpit-packagekit (>= 215-1~ubuntu18.04.1)
Suggests: cockpit-doc (>= 215-1~ubuntu18.04.1), cockpit-pcp (>= 215-1~ubuntu18.04.1), cockpit-machines (>= 215-1~ubuntu18.04.1), xdg-utils
Homepage: https://cockpit-project.org/
Download-Size: 18.0 kB
APT-Sources: http://mirrors.digitalocean.com/ubuntu bionic-backports/universe amd64 Packages
Description: Web Console for Linux servers
 The Cockpit Web Console enables users to administer GNU/Linux servers using a
 web browser.
 .
 It offers network configuration, log inspection, diagnostic reports, SELinux
 troubleshooting, interactive command-line sessions, and more.

Package: cockpit
Version: 164-1
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 58.4 kB
Depends: cockpit-bridge (>= 138), cockpit-dashboard (>= 164-1), cockpit-dashboard (<< 164-1.1~), cockpit-ws (>= 164-1), cockpit-ws (<< 164-1.1~), cockpit-system (= 164-1)
Recommends: cockpit-storaged (= 164-1), cockpit-networkmanager (= 164-1)
Suggests: cockpit-doc (= 164-1), cockpit-docker (= 164-1), cockpit-packagekit (>= 164-1), xdg-utils
Homepage: http://cockpit-project.org/
Download-Size: 16.0 kB
APT-Manual-Installed: yes
APT-Sources: http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 Packages
Description: User interface for Linux servers
 Cockpit runs in a browser and can manage your network of GNU/Linux
 machines.

Any help?
Thanks

**Comment by morphet81** [comment] 2021-07-17 07:08
Hi. Have you tried disabling SSL for web service? Create a `cockpit.conf` file in `/etc/cockpit` then add the following

```
[WebService]
AllowUnencrypted = true
```

**Comment by martinpitt** [comment] 2021-08-06 09:35
Can you please check the JS console (Ctrl+Shift+J) for errors during login? I just debugged #12745 (which has the same symptom) and found a fix for it.

**Comment by martinpitt** [comment] 2021-08-08 05:44
I updated the title as the pam_ssh_add message is unrelated, and expected. The log clearly shows that the login was successful, but the session crashed. Thus #12745 is at least a highly plausible candidate for the cause. To know for sure, we need the JS logs as I asked above.

**Comment by marusak** [comment] 2022-12-15 07:42
No reply, closing

**Closed by marusak** 2022-12-15 07:42 UTC
Labels: question, review-2022-12
