### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19955] opened 2024-02-07 02:28 UTC
Tests failed on 730876b7e95f846a3615bb53f1a16775e219f6bd, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240207-012309-730876b7-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment] 2024-02-07 05:39
Duplicate of #19822

**Closed by martinpitt** 2024-02-07 05:39 UTC
Labels: nightly
