### ISSUE TITLE
machines: Launch Remote Viewer fails when the VM is created using the Create New VM dialogue

### ISSUE THREAD

**Issue by qiyuann** [cockpit-project/cockpit#9028] opened 2018-04-23 14:47 UTC
Create a VM using the Create New VM dialogue, after the VM is installed, try to connect the desktop viewer by clicking the "Launch Remote Viewer" button on Consoles page, it fails with "Unable to connect the graphic server *.vv, Could not connect to 127.0.0.1: Connection refused" , the content of the .vv file is:
[virt-viewer]
type=spice
host=127.0.0.1
port=5900
delete-this-file=1
fullscreen=0

Versions:
cockpit-machines-165-3.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64
cockpit-ws-154-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64

**Comment by mareklibra** [comment] 2018-04-25 10:01
Please confirm, the in-broswer VNC session works for this case. It's proxied via host machine, so `127.0.0.1` works.

If so, the issue is in connecting to the VM remotely (from "browser-machine").

To make it work, we can 
- add configuration of console IP to the UI (simplest, straight-forward, requires awareness of the user)
- get value from guest-agent (quite complex, better to leave that on higher-level tool like oVirt)
- add IP/FQDN to the Create VM Dialog (not preferred)

**Comment by qiyuann** [comment] 2018-04-26 07:58
> Please confirm, the in-browser VNC session works for this case. It's proxied via host machine, so 127.0.0.1 works.

The in-browser VNC session works.

**Comment by mareklibra** [comment] 2018-04-27 11:41
My preference is in adding configuration of Consoles.

Initially, it can consist of
- protocol - SPICE, VNC, serial or none (multiple options are possible)
- Spice, VNC: IP, port
- Serial: pty device

For now, I would not complicate things with i.e. TLS.

What others think? @andreasn , @garrett,  @tjelinek, @suomiy

**Comment by mareklibra** [comment] 2018-04-27 11:52
Related to: https://github.com/cockpit-project/cockpit/issues/8140

**Comment by garrett** [comment] 2018-05-02 15:28
As the browser-based VM works, is there any way to determine the IP address from that?

---

Adding configuration is basically a no-go, as [it violates the ideals of Cockpit](http://cockpit-project.org/ideals.html); specifically: in "Cockpit directly interacts with and reacts to the system", where it states "Cockpit does not store its own opinion of the state of the server anywhere. The UI always reflects the actual current state of the server." 

It also trips over the "Cockpit is not configuration management" section, at "Cockpit itself has no concept of [...] a desired state for the server.".

Additionally, "requires awareness of the user" violates the "Cockpit is discoverable" principle.

It's better if we make an implementation that jumps through hoops instead of forcing someone using our implementation to do the hoop-jumping. (Yes, it's more difficult for us, but that's the way it needs to be, to make it easier for everyone using our software.)

**Comment by garrett** [comment] 2018-05-02 15:41
* Is it possible to store additional custom values in machine's definition using libvirt? 
* Could we do a best attempt at guessing the IP or name and then make that optionally editable in the UI and store it on the system in a non-Cockpit way (such as in the machine definition)?

**Comment by mareklibra** [comment] 2018-05-04 09:48
> As the browser-based VM works, is there any way to determine the IP address from that?

No, it's proxied via host-machine, so i.e. 127.0.0.1 works.

> Is it possible to store additional custom values in machine's definition using libvirt?

In metadata. But AFAIK, they have no value for the libvirt itself. But we are almost free to store whatever **we** want.

> Could we do a best attempt at guessing the IP or name and then make that optionally editable in the UI

Maybe `hostname -f` might make sense here. I would not guess IPs, the network topology can be complex.

> and store it on the system in a non-Cockpit way (such as in the machine definition)?

I don't think domain xml has field for it. @Antique ?

What about following:
- explicit IP entered by user (any host external plus 127.0.0.1 plus "whatever user desires")

  If the entered IP is not visible from the client-machine, I would not handle it explicitly since this is probably the desired state.

  Maybe we can handle the 127.0.0.1 case by warning the user that this might not work (the browser can still be running locally on the host).

- special case of 0.0.0.0

  For the 0.0.0.0 case, the server listens on all host IPs.
  So when a `.vv` file is requested, the user can be provided with a list of host addresses (sort of `hostname --all-ip-addresses` maybe merged with FQDNs from `hostname -A`) to choose one.
  The selected value will be used within the `.vv` file and stored to browser's local storage to be pre-selected next time.

  In addition, within the console configuration dialog, the user can supply an IP in addition to the 0.0.0.0. This value can be stored to libvirt domain's metadata and pre-selected if there's is no preferred one in the local-storage yet.

Cc @Antique, @jelkosz

**Comment by KKoukiou** [comment] 2019-03-29 10:02
This is duplicated from BZ https://bugzilla.redhat.com/show_bug.cgi?id=1558219 
I would rather close this one, and have the tracking in the BZ, since there is a lot of useful information there on how to approach this issue.

**Closed by KKoukiou** 2019-03-29 10:02 UTC
Labels: review-2019-01
