### ISSUE TITLE
disk I/O performance 2x factor discrepancy between Storage and System view

### ISSUE THREAD

**Issue by cmurf** [cockpit-project/cockpit#3403] opened 2015-12-30 05:52 UTC
In System under Disk I/O, I'm seeing roughly 2x MB/s reported compared to Storage under Reading/Writing combined. 

Storage > Reading appears to be correct (~124MB/s in screenshot), matches up with iotop results and also on the same page under Drives the combined R value for all three drives (59MB/s + 63MB/s in the screenshot).
![screenshot from 2015-12-29 22-43-28](https://cloud.githubusercontent.com/assets/10091077/12046857/788ac0c8-ae7e-11e5-9f1e-d6b9528a330a.png)

System > Disk I/O appears to be incorrect (~250MB/s in screenshot).
![screenshot from 2015-12-29 22-43-37](https://cloud.githubusercontent.com/assets/10091077/12046862/a3f5d036-ae7e-11e5-90a8-ad5ea6dab785.png)

The only disk I/O processing going on at the time of any significance is a Btrfs raid1 volume (2 devices) undergoing a scrub.

**Comment by mvollmer** [comment] 2016-01-04 12:59
I can't reproduce this, unfortunately.  Both PCP and the internal metrics seem to behave correctly.

Here is what I did:

- Cockpit in a Fedora 23 VM
- Added two VirtIO SCSI 1 GiG disks as /dev/sda and /dev/sdb
- Ran `dd if=/dev/sda of=/dev/null bs=1` and `dd if=/dev/sdb of=/dev/null bs=1` concurrently.

This gives about 2.8 MiB/s disk I/O in total:

![disk-io-system](https://cloud.githubusercontent.com/assets/3228183/12090047/c83ae624-b2f3-11e5-8c76-ad583fd106de.png)
![disk-io-system](https://cloud.githubusercontent.com/assets/3228183/12090049/cc80c104-b2f3-11e5-8b4d-453ff4d717a4.png)

**Comment by mvollmer** [comment] 2016-01-04 13:02
My hunch is that the system plot is counting traffic twice, somehow.  I know that it does that for network bridges, for example.  (Once for the bridge, and once for the member.)

On the storage page, only block devices are plotted that Cockpit knows to be disks.  On the system page, all block devices are added together and plotted.

Is it possible that this is happening with btrfs somwhow?

**Comment by mvollmer** [comment] 2016-01-04 13:28
Okay, our internal metrics are not very good at identifying partitions and other mapping schemes.  I'll try to improve that.  I'll also try to test with btrfs. 

Could you try to install `cockpit-pcp` and see whether that helps?  We try to offload all these details to PCP, but fall back to old, internal code when PCP is not available.

**Comment by mvollmer** [comment] 2016-01-04 13:47
Well, turns out our internal disk sampler was not used at all, so this is all a bit confusing.

Could you try https://github.com/cockpit-project/cockpit/pull/3409 and see whether it helps?

**Comment by cmurf** [comment] 2016-01-05 04:48
Now on cockpit-0.89-1.fc23.x86_64, reproduced the problem (2x what's expected) Disk I/O value on System page with a single Btrfs volume scrub and also just dd'ing a file to /dev/null. Then I installed cockpit-pcp, restarted cockpit, and now the problem isn't reproducible.

I can try 3409 (without pcp) once there's either a f23 or f24 build in koji.

**Comment by mvollmer** [comment] 2016-01-05 07:57
> I can try 3409 (without pcp) once there's either a f23 or f24 build in koji.

Thank you!  #3409 was merged to master, and will thus be in the next release.  So you should get it as a normal update in about a week, I guess.

**Comment by mvollmer** [comment] 2016-01-05 08:09
> Now on cockpit-0.89-1.fc23.x86_64, reproduced the problem (2x what's expected) Disk I/O value on System page with a single Btrfs volume scrub and also just dd'ing a file to /dev/null. Then I installed cockpit-pcp, restarted cockpit, and now the problem isn't reproducible.

Ok, thanks.  That's good news.  The internal block I/O metrics turn out to be quite unsuitable for the summary plot, and this area is unfortunately severely under-tested.

I wasn't able to reproduce the effect with btrfs, unfortunately.  Can you show your `/proc/diskstats`?  That might give a hint how the internal metrics go wrong.  Please show two snapshots of the file while the operation is ongoing, a couple of seconds apart.  (The numbers don't matter, I just want to see what block devices are in it, and which are changing.)

Thanks!

**Comment by cmurf** [comment] 2016-01-17 05:19
OK I've erased cockpit-pcp, and then upgraded to cockpit*0.91-1.fc23.x86_64 and the problem is still not reproducible.

[chris@f23s ~]$ sudo btrfs scrub start /
scrub started on /, fsid d65458bc-a2b9-4c0a-8860-ffbd9de27f1e (pid=1609)
[chris@f23s ~]$ sudo cat /proc/diskstats
   8       0 sda 90976 47568 24046371 9878945 609 421 136785 34359 64 247774 9926696
   8       1 sda1 90578 47566 24023632 9861619 565 421 136784 30197 64 244242 9905047
   8       2 sda2 51 0 4168 2203 0 0 0 0 0 1932 2203
   8       3 sda3 21 0 168 1296 0 0 0 0 0 1296 1296
   8       4 sda4 21 0 168 1717 0 0 0 0 0 1717 1717
   8       5 sda5 53 0 4432 2328 0 0 0 0 0 2324 2328
   8       6 sda6 207 2 11515 9319 1 0 1 0 0 7464 9318
[chris@f23s ~]$ sudo cat /proc/diskstats
   8       0 sda 91520 47568 24055235 9988555 609 421 136785 34359 65 249634 10032990
   8       1 sda1 91122 47566 24032496 9971229 565 421 136784 30197 65 246102 10011341
   8       2 sda2 51 0 4168 2203 0 0 0 0 0 1932 2203
   8       3 sda3 21 0 168 1296 0 0 0 0 0 1296 1296
   8       4 sda4 21 0 168 1717 0 0 0 0 0 1717 1717
   8       5 sda5 53 0 4432 2328 0 0 0 0 0 2324 2328
   8       6 sda6 207 2 11515 9319 1 0 1 0 0 7464 9318

**Comment by mvollmer** [comment] 2016-02-02 12:22
Okay, so both sda and sda1 show the traffic, and the summary plot used to count them both.  This fits our observations here.

So, I think this is fixed, right?

**Closed by mvollmer** 2016-02-02 12:22 UTC
Labels: question
