### ISSUE TITLE
Tests failed on 2e2198d967b8e5905345d656b4dde25d3a939339

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21285] opened 2024-11-19 02:27 UTC
The job `fedora-40/updates-testing` failed on commit 2e2198d967b8e5905345d656b4dde25d3a939339.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2e2198d9-20241119-013145-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-19 05:31
Duplicate of #21237

**Closed by martinpitt** 2024-11-19 05:31 UTC
Labels: nightly
