### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19778] opened 2023-12-24 02:38 UTC
Tests failed on e70b470c1ef028b91484f90e762aa108735621f4, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231224-012910-e70b470c-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment] 2023-12-24 09:45
Duplicate of #19772

**Closed by martinpitt** 2023-12-24 09:45 UTC
Labels: nightly
