### ISSUE TITLE
Image refresh for debian-8

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#6355] opened 2017-04-19 06:17 UTC
Image creation for debian-8 in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-8-2017-04-19/

**Comment by cockpituous** [comment] 2017-04-19 06:24
Image creation aborted

**Comment by martinpitt** [comment] 2017-04-19 06:36
Dupe of #6356

**Closed** 2017-04-22 05:09 UTC
Labels: bot
