### ISSUE TITLE
machines: Disks list layout does not wrap well

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12946] opened 2019-10-09 12:41 UTC
A VM's list of disks has grown organically and was also ported to PF4. The result of all of this means it is now cramped, wraps oddly, and has a few other issues (such as having a button in the th).

Here's the screenshot:

![Screenshot_2019-10-09 Virtual Machines - Rain(1)](https://user-images.githubusercontent.com/10246/66482087-847e9300-eaa2-11e9-8c49-bef822fbeec6.png)

Perhaps we should combine a few of these columns into a meta-column, like what I suggested for Podman the other day:

![mockup of podman's containers list](https://user-images.githubusercontent.com/10246/65867624-0968fe80-e377-11e9-86e2-17551f2ce68f.png)

We could either extend the list or use something like a card concept.

**Comment by garrett** [comment] 2019-10-09 12:50
If we drop the list concept and use cards, we could have a header at the top... something like:

|Sort by [ Device ⏷ ] | | [ Add Disk ] |
|---|---|---|

And the actual card (or whatever) would look like:


  |   |  
-- | -- | --
disk | ###===== 7.6 GiB / 28.7 GiB | [ Detach ] [ Edit ]
sata, writable |  
File /home/foo/bar/baz/disk.img |   |  

(except the file location would span columns, there wouldn't be headings (empty or otherwise), and such — GitHub tables are limited)

**Comment by garrett** [comment] 2019-10-09 15:44
Here's a mockup based on the screenshot above, to show what I meant by those tables in the previous comment:

![vm-disks](https://user-images.githubusercontent.com/10246/66496807-c2d47c00-eabb-11e9-8ca2-f5494fb8f407.png)

It has all the same information as the screenshot (except I noticed I copied a different VM; whoops), but it's organized in a different manner. 

We could use flex (or grid) to get the spacing right and have it work in mobile too.

@andreasn: What do you think?

**Comment by andreasn** [comment] 2019-10-10 13:00
Looks good to me!

**Comment by KKoukiou** [comment] 2020-03-25 12:21
This is a duplicate of: https://github.com/cockpit-project/cockpit/issues/12843

**Closed by KKoukiou** 2020-03-25 12:21 UTC
Labels: enhancement, needsdesign
