### ISSUE TITLE
Storage modifications

### ISSUE THREAD

**Issue by Takxy** [cockpit-project/cockpit#14253] opened 2020-06-19 03:36 UTC
Cockpit version: 217
OS: CentOS 8.1
Page: Storage

<! I did some changes to one of my disks using #parted and #mkfs (created a new single partition and formatted to xfs), it was ntfs. The problem is that this change on command line does not show on cockpit storage page, it keeps the old information (nfts), tried restart services and rebooting the server, but didn't solve.

Searched on google for some kind of force sync but found nothing, guess it is a bug.>

**Comment by mvollmer** [comment] 2020-07-07 12:30
>  tried restart services and rebooting the server, but didn't solve.

If Cockpit still shows unexpected information after a reboot, then something is very likely wrong with the disk itself. Are you sure you are looking at the right disk? What do lsblk etc say?

**Comment by marusak** [comment] 2020-09-08 12:25
Closing due to lack of information, if you can still reproduce please reopen and provide us with more information. Thanks!

**Closed by marusak** 2020-09-08 12:25 UTC
Labels: question
