### ISSUE TITLE
Allow Cockpit machines to take an image from a path with space's

### ISSUE THREAD

**Issue by ValkyrieUK** [cockpit-project/cockpit#9575] opened 2018-07-04 00:29 UTC
Trying to provide a installation source for a file path like
`/mnt/My - Folder/downloads/image.iso`

Trying to start the machines reports this error in the JS console.

```
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: - Folder/Homes/brad/.local/share/libvirt/images/Windows10.qcow2,device=disk,bus=ide,readonly=off,shareable=off,driver_name=qemu,driver_type=qcow2 - Folder/Homes/brad/Win10_1803_English_x64.img
```

**Comment by ValkyrieUK** [comment] 2018-07-04 00:31
Easy fix for anyone running into the same issue just create a symbolic link to the file

**Comment by martinpitt** [comment] 2018-07-04 07:00
What exactly did you run there? This looks like bots/image-create with some twist?

**Comment by martinpitt** [comment] 2019-01-11 07:46
Duplicate of #9623

**Closed by martinpitt** 2019-01-11 07:46 UTC
Labels: review-2019-01
