### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19776] opened 2023-12-23 02:26 UTC
Tests failed on d90a4645f0c13ea268de270946f9139db46172ea, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231223-012458-d90a4645-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2023-12-23 06:02
Duplicate of #19772

**Closed by martinpitt** 2023-12-23 06:02 UTC
Labels: nightly
