### ISSUE TITLE
Tests failed on 6af58ad6655d7b9de0358e9a701081e7e6014c36

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21123] opened 2024-10-16 02:30 UTC
The job `fedora-40/updates-testing` failed on commit 6af58ad6655d7b9de0358e9a701081e7e6014c36.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6af58ad6-20241016-013145-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-16 06:44
Duplicate of #21108

**Closed by martinpitt** 2024-10-16 06:44 UTC
Labels: nightly
