### ISSUE TITLE
Font size in alerts is incorrect

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15690] opened 2021-04-14 10:32 UTC
PatternFly 4 alerts set the font size in the alert, yet they use elements like H4 inside, which may have their own font size rules when mixing basically _anything_ with PatternFly 4, which includes PF3, reset stylesheets, and so on.

A fix to workaround this issue is to use the following CSS:

```css
.pf-c-alert__title {
    font-size: inherit;
}
```

This tells the title text to use the font size that is specified at the alert level instead of something that might be at the title level, such as an H4 font-size rule.

As it's pretty common for projects to mix PF4 with other CSS (including non-PF widgets, PF3, and reset stylesheets), this should probably be filed and fixed upstream as well. Meanwhile, adding a local override wouldn't hurt.

**Comment by garrett** [comment] 2021-04-14 10:33
Note, this also applies to cockpit-*, such as cockpit-machines, cockpit-podman, and so on. Anything that uses an alert may be affected.

**Comment by garrett** [comment] 2021-04-14 10:35
Examples of where this happens in pending PRs:

![sudo prompt](https://user-images.githubusercontent.com/3228183/114694415-2d0a5480-9d23-11eb-8f70-92f1b7f9f3c7.png)

![machines migration](https://user-images.githubusercontent.com/42733240/114538597-d7b34200-9c53-11eb-9e50-c8339774d3a2.png)

And the font size should be `sm`, such as this screenshot of the PF4 alert demo:

![Screenshot_2021-04-14 PatternFly 4 • Alert](https://user-images.githubusercontent.com/10246/114697204-e7975880-9d1d-11eb-9a1a-725af375f14f.png)

**Comment by KKoukiou** [comment] 2021-04-14 11:24
Duplicate of https://github.com/cockpit-project/cockpit/issues/15639

**Closed by KKoukiou** 2021-04-14 11:24 UTC

**Comment by garrett** [comment] 2021-04-14 11:38
Whoops! Sorry for reporting it as a duplicate.

Fix is to add this to overrides:

```css
.pf-c-alert__title {
    font-size: inherit;
}
```

And report upstream. (It's not directly related to PF4, but when PF4 is used with anything else whatsoever, it can introduce this problem. Therefore, it should be fixed upstream, as nearly every project uses PF4 and something else from time to time.)

I'll submit a PR and make sure a bug is submitted upstream too.
