### ISSUE TITLE
Firewall options not showing

### ISSUE THREAD

**Issue by bomberlord** [cockpit-project/cockpit#10856] opened 2018-12-19 12:01 UTC
Hi,
I have installed an Ubuntu 18.04Lts and Cockpit. Everything is working fine except for the firewall management. I've already installed the firewalld packages and it is working but i still can't see the firewall menus in cockpit. Am i missing something?

Best regards

**Comment by martinpitt** [comment] 2018-12-19 13:36
Whether or not the "Networking" page shows the firewall depends entirely on the `firewalld.service` unit to be existing (it does not need to be enabled). Can you please copy&paste the output of `systemctl status firewalld`?

Also, just to clarify: firewall is *not* in the menus, it's a part of the "Networking" page.

**Comment by bomberlord** [comment] 2018-12-19 14:31
The command output is the following. The service is running and working. I've added some services to allow access to cockpit, http and https.

`rvadmin@sprdefm1:~$ sudo systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset
   Active: active (running) since Wed 2018-12-19 12:42:05 WET; 1h 47min ago
     Docs: man:firewalld(1)
 Main PID: 754 (firewalld)
    Tasks: 2 (limit: 4631)
   CGroup: /system.slice/firewalld.service
           └─754 /usr/bin/python3 -Es /usr/sbin/firewalld --nofork --nopid

dez 19 12:42:02 sprdefm1 systemd[1]: Starting firewalld - dynamic firewall daemo
dez 19 12:42:05 sprdefm1 systemd[1]: Started firewalld - dynamic firewall daemon`

**Comment by martinpitt** [comment] 2018-12-19 16:17
OK, then I'm out of immediate ideas, I'm afraid. We do test Ubuntu 18.04 in CI, including the firewall UI. So the "Firewall" table does not appear at all on the Networking page for you? If you go directly to https://localhost:9090/network/firewall , what happens there?

**Comment by bomberlord** [comment] 2018-12-19 16:37
I get a message saying "Not Found". I suspect that i am missing a package to allow firewall management but the repositories don't have any "cockpit-firewall" package to install.

**Comment by bomberlord** [comment] 2018-12-20 10:32
Yes. I need to troubleshoot the solution because i'm also having a problem with the policy kit. Some actions are not allowed by Active Directory users and there could be a problem with permissions.

**Comment by bomberlord** [comment] 2018-12-20 19:12
I'm still struggling with the permissions in polkit. Couldn't manage my users that authenticate with kerberos to have administration privileges. Apart from this, the root user can't also see the Firewall tab in the Networking page.

**Comment by bomberlord** [comment] 2019-01-08 16:07
Still no success with this. Tried reinstalling everything and i still don't get the firewall options in the networking pane. Can anybody give me an example of the polkit configurations required to get it working?
Thanks

**Comment by martinpitt** [comment] 2019-01-08 21:06
I'm 99% sure that PR #10926 fixed this today in master. To confirm, your user is *not* in the `sudo` or `admin` group, but gets its sudo privileges via an explicit /etc/sudoers rule?

**Comment by martinpitt** [comment] 2019-01-08 21:07
Closing for now, as this is very probably fixed in master now.

**Closed by martinpitt** 2019-01-08 21:07 UTC

**Comment by ChengYen-Tang** [comment] 2019-10-15 17:25
I also encountered the same problem, my environment is Ubuntu 18.04Lts. 😭

**Comment by rthery** [comment] 2019-11-13 09:57
For people looking for a solution to this, this is most likely caused by #9795, your version is too old because it was not installed from bionic-backports.
To resolve this, you can create/edit `/etc/apt/preferences` with:
```
Package: *
Pin: release a=bionic-backports  
Pin-Priority: 500
```

I used a wild star because there are so many cockpit feature packages. Also you'll need to change the name of your release, as this is for Ubuntu 18.04

Then redo a `sudo apt-get install cockpit`, this will upgrade your cockpit with the latest version that will include support for firewalld.

**Comment by ChengYen-Tang** [comment] 2019-11-14 05:28
Thank you, this works.
