### ISSUE TITLE
Virtual machines: problem with filenames containing spaces

### ISSUE THREAD

**Issue by schopenhauer** [cockpit-project/cockpit#14524] opened 2020-08-29 08:11 UTC
Cockpit version: 226
OS: Fedora 32
Page: Virtual Machines

The creation of a new VM fails, when the filename of an ISO image contains spaces (e.g. "Windows Server X64 2019.iso"). This will lead to the following error message:

`Creation of VM failed: usage: virt-install --name NAME --memory MB STORAGE INSTALL [options] virt-install: error: unrecognized arguments: Server X64 2019.iso`

The above filenames should probably be in quoted/escaped before the command is executed.

**Comment by marusak** [comment] 2020-08-29 08:24
Duplicate of https://github.com/cockpit-project/cockpit/issues/9623
We had some fixes for things in VMs containing spaces lately, like VM names in https://github.com/cockpit-project/cockpit/issues/12893 or storage pool names in https://github.com/cockpit-project/cockpit/issues/13998

@KKoukiou maybe #9623 should be properly addressed?

(not closing for now even though it is dupe as we might want to fix this separately from #9623 which may be a bigger task to analyse all such places)

**Closed** 2020-10-30 13:13 UTC
