### ISSUE TITLE
Tests failed on d2e1f5d8f2345aa378803a8a939cb98f5a45b712

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21070] opened 2024-10-03 03:14 UTC
The job `fedora-40/updates-testing` failed on commit d2e1f5d8f2345aa378803a8a939cb98f5a45b712.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-d2e1f5d8-20241003-013105-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-03 05:11
Duplicate of #21048

**Closed by martinpitt** 2024-10-03 05:11 UTC
Labels: nightly
