### ISSUE TITLE
Image refresh for ipa

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#6535] opened 2017-05-13 06:02 UTC
Image creation for ipa in process on cockpit-tests-8srl2.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-ipa-2017-05-13/

**Comment by cockpituous** [comment] 2017-05-13 06:08
Image creation aborted

**Comment by stefwalter** [comment] 2017-05-18 07:40
Duplicate of #6334

**Closed by stefwalter** 2017-05-18 07:40 UTC
Labels: bot
