### ISSUE TITLE
Allow browser to remember login

### ISSUE THREAD

**Issue by jniederm** [cockpit-project/cockpit#6399] opened 2017-04-27 16:56 UTC
Please wrap the 'username' and 'password' input fields in login page to `form` tag to allow browser to remember credentials.

demo: https://jsfiddle.net/mdq538wm/1/

**Comment by stefwalter** [comment] 2017-04-28 11:12
Cockpit is a Linux session. I guess some other Linux sessions have auto-login too, but it's usually something that's explicitly enabled per user session. This needs some thought.

@andreasn @petervo What do you think about auto-login to Cockpit using browser password caching?

**Comment by petervo** [comment] 2017-05-01 15:13
From a linux session point of view, i don't really like it. But I'm not really able to articulate a clear reason why we shouldn't do it other than it makes me a bit uncomfortable. Unless someone else is I think it's sort of a default expectation people have in browsers these days and we should probably allow it to happen.

**Comment by martinpitt** [comment] 2017-05-01 19:49
TBH I don't see why we wouldn't do it - the browser keyring already has all sorts of credentials and is meant for that. It's usually protected by the user's password (in most cases) already anyway, so one has to enter it at least once.

**Comment by rhwood** [comment] 2018-04-11 18:19
FWIW, on my MacBook, running macOS High Sierra, all browsers except Firefox already offer to remember the login of cockpit running in a vagrant image (that's Google Chrome, Opera, and Safari that make the offer). Not sure if Firefox is not offering to save credentials only because the connection is not encrypted.

**Comment by rhwood** [comment] 2018-04-28 12:42
[NIST 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html#-5112-memorized-secret-verifiers) specifically encourages supporting the use of password managers (10th paragraph).

**Comment by Limero** [comment] 2018-04-28 16:48
This would be very useful. Those not interested in saving the login can just choose "no" when prompted by their browser.

**Comment by sergiomb2** [comment] 2018-10-22 12:49
+1

**Comment by sergiomb2** [comment] 2018-10-22 12:49
+1

**Comment by AndreasKieling** [comment] 2019-06-16 11:54
+9001

**Comment by martinpitt** [comment] 2019-10-21 08:25
I tried this again, and I can't make Firefox remember the password for the life of me. The current web page already has the required input types (text and password) for user and password lines.

I tried converting into a proper `<form>` and even tried to change the login button into a "submit" input (which is wrong from a UI POV, but I wanted to check if it helps). Nothing.

```
--- src/ws/login.html
+++ src/ws/login.html
@@ -23,7 +23,7 @@
         </div><!--/.col-*-->
 
         <div id="login" class="col-sm-7 col-md-6 col-lg-5 login-area" style="visibility: hidden;">
-          <div role="form">
+          <form>
 
             <div id="error-group" class="alert alert-danger" hidden>
               <span id="login-error-message"></span>
@@ -80,13 +80,12 @@
 
             <div class="form-group">
               <div class="col-md-3 col-sm-3 login-button-container">
-                <button class="btn btn-primary col-xs-12" id="login-button">
+                <input type="submit" class="btn btn-primary col-xs-12" id="login-button" translate="value" value="Log In">
                   <span class="spinner"></span>
-                  <span id="login-button-text" translate>Log In</span>
                 </button>
               </div>
             </div>
-          </div>
+          </form>
         </div><!--/.col-*-->
 
         <div class="col-sm-5 col-md-6 col-lg-7 details" id="login-details">
```

**Comment by Neustradamus** [comment] 2019-11-20 03:19
It is an important missing feature.

**Comment by agneevX** [comment] 2020-05-28 08:31
Any update on this issue?

**Comment by marusak** [comment] 2020-09-09 08:51
It seems to work just fine as is.
On firefox (firefox-79.0-5) I don't get the popup, but if I click on the key icon I can save the name and passowrd:
![Screenshot from 2020-09-09 10-26-11](https://user-images.githubusercontent.com/12330670/92576008-475dea80-f289-11ea-9e62-ca378c18f778.png)
And then on login page I can use it as expected:
![Screenshot from 2020-09-09 10-39-53](https://user-images.githubusercontent.com/12330670/92576160-75432f00-f289-11ea-9fff-d7ccb9d47e8c.png)
Same behaviour in chromium:
![Screenshot from 2020-09-09 10-40-51](https://user-images.githubusercontent.com/12330670/92576271-9efc5600-f289-11ea-930e-757ad96483b4.png)

I like this behaviour that the popup is not opened by default but user can find it and save the passoword. (Not sure if this was by design or not, if it was than hats off)

I would be happy if someone from this thread could also give it a shot, thanks! Closing in the meantime.

**Closed by marusak** 2020-09-09 08:51 UTC

**Comment by Neustradamus** [comment] 2020-09-09 18:58
@marusak: What is the cockpit version?

**Comment by sergiomb2** [comment] 2020-09-09 19:15
> @marusak: What is the cockpit version?

Version 226 of Fedora 31 is working

**Comment by marusak** [comment] 2020-09-09 19:33
> What is the cockpit version?

I have 227 here.

> Version 226 of Fedora 31 is working

Awesome, thanks for verifying it!

**Comment by ririko5834** [comment] 2022-04-22 12:35
Chrome did not ask me if I want to save password, I have long auto generated password and I am lazy to copy it every time from txt file.

**Comment by LordMilutin** [comment] 2022-11-04 09:43
Still no update on this feature?

**Comment by sergiomb2** [comment] 2022-11-04 11:12
I reported that Version 226 of Fedora 31 is working , isn't it ?

**Comment by LordMilutin** [comment] 2022-11-04 11:44
On Ubuntu 22.04.1 LTS and Google Chrome, it isn't working. 
I have no popup or option to save the username and password...

**Comment by marusak** [comment] 2022-11-04 13:32
You need to click on the key icon. But we shipped a few weeks ago even better version where it should work more smoothly. This is in version 277. What version are you running?

**Comment by LordMilutin** [comment] 2022-11-04 14:28
I am using the latest version 
```
(cockpit/jammy-updates,now 264-1ubuntu0.22.04.1 all [installed])
cockpit is already the newest version (264-1ubuntu0.22.04.1).
```
There is no key...
![image](https://user-images.githubusercontent.com/76582100/199998570-9b78bd61-1ced-4302-bf6d-084bb688e38a.png)
![image](https://user-images.githubusercontent.com/76582100/199998935-67a477db-d1a6-4176-bc9b-1436f7ff61fc.png)

**Comment by martinpitt** [comment] 2022-11-04 14:37
[backports](https://launchpad.net/ubuntu/+source/cockpit) still has 276.1, I'll update that to 277 now. (I can't yet do 278 as Ubuntu development release is still frozen). @LordMilutin : See https://cockpit-project.org/running.html#ubuntu for how to install from backports.

**Comment by LordMilutin** [comment] 2022-11-04 15:03
@martinpitt Ah okay, that explains it. Thank you.

**Comment by EliasGagnef** [comment] 2022-12-19 22:57
So I do not appear to have any key icon and I installed cockpit today and it says that the system is up to date, any idea how I could get it? My log in page looks the same as @LordMilutin s screenshot
