### ISSUE TITLE
Unable to connect to graphic server 

### ISSUE THREAD

**Issue by mrpg99** [cockpit-project/cockpit#12886] opened 2019-09-27 09:07 UTC
Dear Sir/Madam,

I have installed cockpit onto a debian 9.10 server.

i can access the cockpit webserver, and i can see my two virtual machines i created manually with virsh.

However i have two issues in cockpit -

1 i cannot view the vm console , i am trying from a fedora 28 client, where i have installed virt-viewer
i get this message : 
"Unable to connect to the graphic server /home/mrpg/Downloads/download - could not connect to 127.0.0.1: connection refused"

2 seocnd issue is trying to create vm:s through cockpit , i click on "Create VM"
i choose QEMU/KVM
give it a hostname
pick the .iso file i want to use to install from
and i get -

Creation of vm test failed ERROR    internal error: process exited while connecting to monitor: 2019-09-27T09:06:17.181594Z qemu-system-x86_64: -vnc 127.0.0.1:2: Failed to start VNC server: Failed to bind socket: Address already in use
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start test
otherwise, please restart your installation.

Please note that i am also running openmediavault on this machine, could that be interfering with vnc?
Best Regards
Patric

**Comment by KKoukiou** [comment] 2019-09-27 12:57
@mrpg99 please create two issues instead of one when there are two seperate bugs.

* The first issue has a BZ - see https://bugzilla.redhat.com/show_bug.cgi?id=1558219
* The second issue looks like an kernel bug that was never fixed in debian stretch that you are using, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923398

**Comment by mrpg99** [comment] 2019-09-27 15:35
ok understood, i am not allowed to view this bugreport : 
https://bugzilla.redhat.com/show_bug.cgi?id=1558219
could you please post what is needed to fix it for me?

Br
Patric

**Comment by KKoukiou** [comment] 2019-09-27 15:43
> ok understood, i am not allowed to view this bugreport :
> https://bugzilla.redhat.com/show_bug.cgi?id=1558219
> could you please post what is needed to fix it for me?
> 
> Br
> Patric

Oh right. So basically it's not implemented yet. You can't get a SPICE console in a different machine than your VM is running on through cockpit.

**Comment by iokaravas** [comment] 2019-09-30 15:40
> > ok understood, i am not allowed to view this bugreport :
> > https://bugzilla.redhat.com/show_bug.cgi?id=1558219
> > could you please post what is needed to fix it for me?
> > Br
> > Patric
> 
> Oh right. So basically it's not implemented yet. You can't get a SPICE console in a different machine than your VM is running on through cockpit.

I was about to start an issue about this myself, but:

If you wish you can edit the configuration via CLI: (`domain-name` being the virtual machine's name)
```
    sudo virsh edit domain-name
```

Locate the SPICE line and put your HOST's IP address in `listen` and `address`.
```
    <graphics type='spice' autoport='yes' listen='XXX.XXX.XXX.XXX'>
      <listen type='address' address='XXX.XXX.XXXXXX'/>
      <image compression='off'/>
    </graphics>
```

After that you'll be able to connect to it, just fine. Unfortunately 0.0.0.0 (bind to any) doesn't seem to work as currently the spice connection uri generated in Cockpit uses the exact value you use in the configuration file (XML). Although again, if you type in your browser the same URI and change the 0.0.0.0 to an IP address of the host, it works fine.

Unfortunately I do not have access to the bug, so hopefully I'm making sense here :)

**Comment by mrpg99** [comment] 2019-10-02 06:32
Thank you so much iokaravas!

This works!

now its just the issue of spinning up new vm:s from cockpit left to fix!

but if thats a kernel bug that was never fix, i guess an update to debian 10.x is whats needed?

**Comment by iokaravas** [comment] 2019-10-02 06:47
@mrpg99 Could very well be needed, I'm on Debian 10 and it's working fine.

**Comment by KKoukiou** [comment] 2019-11-14 10:02
Closing this one since it's duplicate of https://github.com/cockpit-project/cockpit/issues/8140 and  I think the later is more descriptive.

**Closed by KKoukiou** 2019-11-14 10:02 UTC
Labels: question
