### ISSUE TITLE
RFE: Storage - device status on main page

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#9707] opened 2018-07-22 15:11 UTC
On the main storage page - it would be good to highlight if there are any issues with the devices (md, LV, disk)

for disk - SMART error
for md - anything that notes degraded status

Selecting a md device shows the correct error status, but the icon/box on the summary page does not reflect any issues.

**Comment by martinpitt** [comment] 2019-01-15 11:37
Duplicate of #1134

**Closed by martinpitt** 2019-01-15 11:37 UTC
Labels: review-2019-01
