### ISSUE TITLE
trying to set certain images as avatars disconnects the server

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3232] opened 2015-11-25 11:00 UTC
This is an odd bug, but trying to set certain avatars disconnect the server.

**Comment by andreasn** [comment] 2015-11-25 11:03
This one works
![Uploading 2011etape21.jpg…]()

But this one doesn't
![70097 velodrome-du-mont-posters](https://cloud.githubusercontent.com/assets/209895/11395649/8d54885e-936c-11e5-9971-cc66f9d98cc4.jpg)

**Comment by stefwalter** [comment] 2015-11-25 11:44
Any messages in the journal?

**Comment by stefwalter** [comment] 2015-11-25 11:53
On IRC:

```
<andreasn> could it be "server is trying to frame of size 146251 or greater, but max supported size is 128KiB"
```

Duplicate of #2042

**Closed** 2015-11-25 11:54 UTC
Labels: question
