### ISSUE TITLE
applications: Show more available applications

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#18454] opened 2023-03-06 12:17 UTC
Right now, if you install Cockpit, you don't see all the add-ons and applications that are available.

For example, on Ubuntu 22.04.2, after doing an `apt install cockpit`, you get this:

![image](https://user-images.githubusercontent.com/10246/223090941-2e22a81a-49bc-46df-a66f-b342df77e1e5.png)

The output from the `apt` command is:

```
The following additional packages will be installed:
  cockpit-bridge cockpit-networkmanager cockpit-packagekit cockpit-storaged
  cockpit-system cockpit-ws finalrd libblockdev-mdraid2 libbytesize-common
  libbytesize1 libpwquality-tools mdadm
Suggested packages:
  cockpit-doc cockpit-pcp cockpit-sosreport udisks2-lvm2 sssd-dbus default-mta
  | mail-transport-agent dracut-core
The following NEW packages will be installed:
  cockpit cockpit-bridge cockpit-networkmanager cockpit-packagekit
  cockpit-storaged cockpit-system cockpit-ws finalrd libblockdev-mdraid2
  libbytesize-common libbytesize1 libpwquality-tools mdadm
```

So shouldn't we show other `cockpit-`* packages to remove?

And doing a search for `cockpit-`* packages shows all of these available:

```
cockpit-389-ds/jammy,jammy 2.0.15-1 all
  Cockpit user interface for 389 Directory Server

cockpit-machines/jammy,jammy 265-1 all
  Cockpit user interface for virtual machines

cockpit-networkmanager/jammy-updates,jammy-updates,now 264-1ubuntu0.22.04.1 all [installed,automatic]
  Cockpit user interface for networking

cockpit-packagekit/jammy-updates,jammy-updates,now 264-1ubuntu0.22.04.1 all [installed,automatic]
  Cockpit user interface for packages

cockpit-pcp/jammy-updates 264-1ubuntu0.22.04.1 amd64
  Cockpit PCP integration

cockpit-podman/jammy,jammy 45-1 all
  Cockpit component for Podman containers

cockpit-sosreport/jammy-updates,jammy-updates 264-1ubuntu0.22.04.1 all
  Cockpit user interface for diagnostic reports

cockpit-storaged/jammy-updates,jammy-updates,now 264-1ubuntu0.22.04.1 all [installed,automatic]
  Cockpit user interface for storage
```

Additionally, Fedora has cockpit-navigator, and that's missing. But Fedora lists a lot more — even some that are available but not shown in Ubuntu:

![image](https://user-images.githubusercontent.com/10246/223107937-191d1651-51af-4b38-9045-facfb5c0e38f.png)

**Comment by marusak** [comment] 2023-03-06 12:35
Duplicate of https://github.com/cockpit-project/cockpit/issues/17737? (on https://github.com/cockpit-project/cockpit/issues/18439)

> Additionally, Fedora has cockpit-navigator, and that's missing.

If some app is not shown it is missing [appstream xml file](https://github.com/cockpit-project/cockpit/pull/18218) and it needs to be reported for every app separately.

**Comment by garrett** [comment] 2023-03-06 12:41
@marusak those are closed, however. I looked for duplicates when opening this, after seeing someone complaining about the page not loading. We need at least one issue open and someone to look into (and fix) this.

I took a minute to look at an Ubuntu VM I already had set up (for other Cockpit related reasons) and saw that it does work, but it's basically empty and not useful, so I reported here after seeing there was no open issue for it.

**Comment by marusak** [comment] 2023-03-06 13:07
> @marusak those are closed, however. I looked for duplicates when opening this, after seeing someone complaining about the page not loading. We need at least one issue open and someone to look into (and fix) this.

https://github.com/cockpit-project/cockpit/issues/17737 is closed because it was fixed in https://github.com/cockpit-project/cockpit/pull/18218 . Now it just takes time to get into the distributions itself.

**Comment by garrett** [comment] 2023-03-06 13:09
> Now it just takes time to get into the distributions itself.

Aha, so we need a backport for it?

There are some gaps still; I guess it's a matter of making sure the missing ones (navigator, as an example) have appstream XML files too, and that these are in the packages across distros. In the case of navigator, it'd need to have a bug reported upstream and/or in Fedora.

**Comment by jelly** [comment] 2023-03-07 11:08
* [ ] cockpit-navigator - has no appstream data, so that needs to be reported upstream https://github.com/45Drives/cockpit-navigator and installed in packaging. Same for the Samba plugin etc. And probably fixing in packaging. https://src.fedoraproject.org/rpms/cockpit-navigator/blob/rawhide/f/cockpit-navigator.spec

For Ubuntu/Debian, you need to install `appstream` and then run an `apt update` as the metadata is part of the repository and not a separate package. Then I get:

```
root@7736bbb0b936:/# appstreamcli search cockpit
Identifier: org.cockpit_project.cockpit [web-application]
Name: Cockpit
Summary: Web Console for Linux servers
Package: cockpit
Homepage: https://cockpit-project.org/
---
Identifier: org.cockpit_project.podman [addon]
Name: Podman
Summary: Cockpit component for Podman containers
Package: cockpit-podman
---
Identifier: org.cockpit_project.cockpit_sosreport [addon]
Name: Diagnostic reports
Summary: Collect and package diagnostic and support data
Package: cockpit-sosreport
Homepage: https://cockpit-project.org/
---
Identifier: org.port389.cockpit_console [addon]
Name: 389 Directory Server
Summary: 389 Directory Server Management
Package: cockpit-389-ds
Homepage: https://www.port389.org/
---
Identifier: org.cockpit_project.cockpit_machines [addon]
Name: Machines
Summary: Manage your virtual machines
Package: cockpit-machines
Homepage: https://cockpit-project.org/
---
Identifier: org.cockpit_project.cockpit_storaged [addon]
Name: Storage
Summary: Manage storage
Package: cockpit-storaged
Homepage: https://cockpit-project.org/
---
Identifier: kraptor.desktop [desktop-application]
Name: Kraptor
Summary: classic shoot 'em up scroller game
Package: kraptor
Icon: kraptor
root@7736bbb0b936:/#
```

The Arch Cockpit package does not depend on `archlinux-appstream-data` so nothing will be shown. I'm not sure if it should honestly or if packagekit should depend on it?

**Comment by martinpitt** [comment] 2023-03-07 11:12
> For Ubuntu/Debian, you need to install appstream and then run an apt update

This is what the "Refresh" button 🔄 is supposed to do, doesn't that work?

**Comment by jelly** [comment] 2023-03-07 11:13
> > For Ubuntu/Debian, you need to install appstream and then run an apt update
> 
> This is what the "Refresh" button arrows_counterclockwise is supposed to do, doesn't that work?

Oh, well I was testing in a container as I have no ubuntu host :)

**Comment by jelly** [comment] 2023-03-07 12:52
cockpit-composer is notably missing on Fedora, I guess it's because the appstream xml file does not validate:

```
[jelle@t14s][~/projects/cockpit-composer]%appstream-util validate public/io.weldr.cockpit-composer.metainfo.xml
public/io.weldr.cockpit-composer.metainfo.xml: FAILED:
• tag-missing           : <url> is not present
Validation of files failed
[jelle@t14s][~/projects/cockpit-composer]%vim  public/io.weldr.cockpit-composer.metainfo.xml
[jelle@t14s][~/projects/cockpit-composer]%appstream-util validate public/io.weldr.cockpit-composer.metainfo.xml
public/io.weldr.cockpit-composer.metainfo.xml: OK
```

**Comment by lalitkumawat1m** [comment] 2023-03-28 03:13
Hi, could you please assign this issue to me?
I would love to work on it and contribute to the project

**Comment by Akshat2Jain** [comment] 2023-06-04 17:53
Hey @jelly, I understood this issue. Basically, we have to add the meta info to these separate projects. To do that first, we have to
add this  `org.cockpit-project.podman.metainfo.xml` type of file to these projects and then add a tarfile for that meta info in the makefile of that project. Correct me if I am wrong.
And I also understood that this issue is not related to this repo. 
I have gone through these projects and found that `cockpit-session-recording.noarch`  added this meta info already, this means 3 projects are left. Please suggest to me how to work on this issue.

**Comment by Akshat2Jain** [comment] 2023-06-08 06:57
I think it's valid but they have not included the tar file that would bundle this XML file in the makefile.am

> 389-ds seems to have one, so maybe it's not valid? Or included? https://github.com/389ds/389-ds-base/blob/7fbcb8da85ccb5283db110de0de3c6574629596a/src/cockpit/389-console/org.port389.cockpit_console.metainfo.xml

**Comment by jelly** [comment] 2023-06-08 07:32
```
Makefile.am:    rsync -up src/cockpit/389-console/org.port389.cockpit_console.metainfo.xml $(DESTDIR)$(metainfodir)/org.port389.cockpit_console.metainfo.xml
rpm/389-ds-base.spec.in:%{_datarootdir}/metainfo/389-console/org.port389.cockpit_console.metainfo.xml
src/cockpit/389-console/org.port389.cockpit_console.metainfo.xml:  <id>org.port389.cockpit_console</id>
```

So their package should include it.

File is indeed valid.
```
[jelle@t14s][~/projects/389-ds-base]%appstream-util validate src/cockpit/389-console/org.port389.cockpit_console.metainfo.xml
src/cockpit/389-console/org.port389.cockpit_console.metainfo.xml: OK
```

**Comment by Akshat2Jain** [comment] 2023-06-08 09:02
Should I make the pr for the other two projects

**Comment by jelly** [comment] 2023-06-08 10:37
Feel free to create a valid metainfo file for those projects and a PR. Make sure it ends being packaged as well.

**Comment by leomoty** [comment] 2023-08-31 16:25
> This is what the "Refresh" button 🔄 is supposed to do, doesn't that work?

@martinpitt nope, there is no logic to install appstream when you click that refresh button, it just lists the ones already installed.

**Comment by leomoty** [comment] 2023-09-04 12:00
@martinpitt Would something like this work?

https://github.com/cockpit-project/cockpit/commit/631b973bcdbbaf3b566189ef28798d0977f562e7

I know it would need integration tests, but I cant figure out the CDP error

**Comment by leomoty** [comment] 2023-09-04 14:21
@martinpitt I've filled #18454 for the PR

Regarding the error, here you go:
```
[leomoty@europa cockpit]$ test/verify/check-apps
# ----------------------------------------------------------------------
# testBasic (__main__.TestApps)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:9717/devtools/browser/0bf6a97d-ff09-42ae-ad78-a5419fd2c0ac
[0904/111705.039904:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.builtinStrategy (node:internal/modules/esm/translators:259:11)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
Traceback (most recent call last):
  File "/home/leomoty/cockpit/test/verify/check-apps", line 101, in testBasic
    self.login_and_go("/apps", urlroot=urlroot)
  File "/home/leomoty/cockpit/test/common/testlib.py", line 1611, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/leomoty/cockpit/test/common/testlib.py", line 790, in login_and_go
    self.open(href, tls=tls)
  File "/home/leomoty/cockpit/test/common/testlib.py", line 233, in open
    self._set_window_size(size[0], size[1])
  File "/home/leomoty/cockpit/test/common/testlib.py", line 950, in _set_window_size
    self.cdp.invoke("Emulation.setDeviceMetricsOverride",
  File "/home/leomoty/cockpit/test/common/cdp.py", line 205, in invoke
    res = self.command(cmd)
  File "/home/leomoty/cockpit/test/common/cdp.py", line 215, in command
    self.start()
  File "/home/leomoty/cockpit/test/common/cdp.py", line 327, in start
    self.invoke("Page.addScriptToEvaluateOnNewDocument", source=src, no_trace=True)
  File "/home/leomoty/cockpit/test/common/cdp.py", line 205, in invoke
    res = self.command(cmd)
  File "/home/leomoty/cockpit/test/common/cdp.py", line 222, in command
    raise RuntimeError("CDP broken")
RuntimeError: CDP broken
```

**Comment by martinpitt** [comment] 2023-09-04 15:27
Missing "node:readline/promises" smells like a too old node? https://nodejs.org/api/readline.html#class-readlinepromisesinterface says it was added in node.js 17, you may still have 16 or even older? I recommend to use the official cockpit/tasks container locally, see https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#setting-up-development-container

**Comment by leomoty** [comment] 2023-09-04 15:29
> Missing "node:readline/promises" smells like a too old node

Yep, node was too old, will take a look

**Closed** 2023-10-13 06:31 UTC
Labels: bug, page:applications
