### ISSUE TITLE
Cockpit does not load js and css resources while accessing from external domain

### ISSUE THREAD

**Issue by j3ws3r** [cockpit-project/cockpit#16121] opened 2021-07-20 11:38 UTC
Cockpit version: 215
OS: Ubuntu 20.04.2 LTS
Browsers: Chrome 91.0.4472.114, Safari 14.0.3, FF 90.0.1

Cockpit does not load some js and css resources while accessing through external domain. Login functions properly, but some tabs like accounts, overview, docker containers, networking does not load at all. Virtual machines and logs load just fine it seems. Connection between server and domain is through Argo Tunnel. 

Journalctl -f entries and view of page 
![image](https://user-images.githubusercontent.com/51436874/126316725-dd43fd3e-d77f-4a42-b24c-db39775adeae.png)

Contents of cockpit.conf: 
![image](https://user-images.githubusercontent.com/51436874/126316962-7408fd89-fe5f-444e-9a83-e22186e3bc16.png)

Nginx location block: 
`location /admin/ {
         # Required to proxy the connection to Cockpit
          proxy_bind 192.168.1.16;
          proxy_pass http://192.168.1.16;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto http;
          proxy_hide_header Content-Security-Policy;
          
          # Required for web sockets to function
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
 
          # Pass ETag header from Cockpit to clients.
          # See: https://github.com/cockpit-project/cockpit/issues/5239
          gzip off;
      }
`

If there is more info needed, I can add it.

**Comment by j3ws3r** [comment] 2021-07-21 07:45
Found interesting stuff: 
While loading from external domain and NOT through internal IP I get the following errors for network.js and services.js : 
![image](https://user-images.githubusercontent.com/51436874/126450934-78149531-e1ce-482b-88c4-1ce2ef7cc4af.png)

In the path I can see that it requests @localhost too. Can't find any report with the following problem and actually can't find any solution for this problem. 
Everything else works fine after updating ubuntu to 21.04 and upgrading cockpit along with distro.

**Comment by alucryd** [comment] 2021-07-30 10:20
Pretty much in the same boat here:
![image](https://user-images.githubusercontent.com/1561084/127639188-d4230d10-f54a-4759-8c49-c4535b181504.png)
I tried using `proxy_hide_header`, `proxy_set_header` and `add_header` to manipulate X-Frame-Options but to no avail.

**Comment by martinpitt** [comment] 2021-08-07 13:18
I just debugged and fixed that yesterday -- this is a duplicate of issue #12745, fixed in commit 16c3c16d37a6ed.

**Closed by martinpitt** 2021-08-07 13:18 UTC
