### ISSUE TITLE
Cockpit web interface is unusable after the upgrade from 204 to 205

### ISSUE THREAD

**Issue by raneon** [cockpit-project/cockpit#13042] opened 2019-10-26 10:53 UTC
Cockpit version: 205
OS: Arch Linux

Cockpit web interface is unusable after the upgrade from 204 to 205. Downgrading to 204 allows me to use cockpit normally.

After the upgrade from cockpit 204 to 205 the web interface is unusable as soon as I login to cockpit (start page: multi server dashboard) and I try to select the ssh key. But at this stage Firefox did almost freeze and I had to kill it's process (100% CPU usage on almost 5 cores). I've tried it with Chromium and Falkon, but the web interface doesn't behave normally there either, selecting the path for the ssh key is impossible too, even though CPU usage was slightly lower.

I do run on a remote machine a cockpit.socket that I access via a domain name. This remote cockpit system allows me to than monitor all my other connected systems after selecting the ssh key and typing in my password.

In journalctl of the remote host I found some error messages:

Okt 24 21:24:14 pc1 cockpit-ws[284713]: Error sending data: Broken pipe
Okt 24 21:24:14 pc1 cockpit-ws[284713]: WebSocket from (null) for session closed
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received out of order middle message fragment
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received out of order inital message fragment
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received fragmented control frame
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received fragmented control frame
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received fragmented control frame
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received out of order inital message fragment
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received unfragmented message when fragment was expected
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received fragmented control frame
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: received out of order inital message fragment
Okt 24 21:24:31 pc1 cockpit-ws[284713]: Received invalid WebSocket response from the server
Okt 24 21:24:31 pc1 cockpit-ws[284713]: WebSocket from (null) for session closed

Steps to reproduce

1. Start cockpit.socket with systemctl
2. Open Firefox and go to IPADDRESS:9090
3.  Login and try to select a ssh key

To avoid that I have a special config, I've now tested cockpit on another system.  On my desktop I started with systemd the cockpit.socket. Then I opened in Firefox "localhost:9090". After the login I was able to use the cockpit web interface normally on this single machine setup.

Then I tried the same via the IP address of the local machine (192.1.1.100:9090). In this case I could login to cockpit, but I was kicked out immediately. Then I clicked the reconnect button and I had to login again. But same result, I was kicked out again. I've tested this with the IPv6 address and it showed the same issue.

**Comment by mtorromeo** [comment] 2019-10-26 11:15
I can reproduce the issue as described.

Some more details:
- I am connecting to the web interface of a cockpit v205
- The remote cockpit instance to which I tried to connect to was an older version of cockpit (199) and I don't think it makes a difference
- By pausing the javascript execution in the browser I was able to determine that the high load is caused by the handling of thousands of non-stopping data frames incoming on the WebSocket. The messages are all identical to this one `1:1!34
[[0,1307.3852295409306,439.12175648703123]]` in my case.

**Comment by mtorromeo** [comment] 2019-10-26 15:34
I bisected the repo and found the issue to appear in commit 57ad643a44b964b45251ebcf2bd9177a02542926

**Comment by mtorromeo** [comment] 2019-10-26 15:50
Seems like it's already been fixed in 205.1 and I somehow missed the release. My bad!

**Comment by raneon** [comment] 2019-10-27 08:30
I can confirm that 205.1 works again :-) @mtorromeo Thanks for all your support and effort!

**Comment by martinpitt** [comment] 2019-10-27 09:25
Right, sorry about that blunder! Version 205 got blocked in Fedora 30/31 for that reason (and never packaged for Debian/Ubuntu).

**Closed by martinpitt** 2019-10-27 09:25 UTC
