### ISSUE TITLE
Monitor/Alert for hdd

### ISSUE THREAD

**Issue by Fredrik81** [cockpit-project/cockpit#7182] opened 2017-07-10 17:57 UTC
Would be great if the storage part in cockpit could have monitoring and alert functionality based on smarttools/smartd.
To be able to show if errors have occurred for a drive.
Perhaps by showing the log entries in combination to a status icon.

**Comment by stefwalter** [comment] 2017-07-12 09:45
@Fredrik81 Yes indeed. That would be very useful. Are you interested in working on this feature?

**Comment by martinpitt** [comment] 2019-01-15 11:37
Duplicate of #1134

**Closed by martinpitt** 2019-01-15 11:37 UTC
Labels: enhancement, review-2019-01
