### ISSUE TITLE
CentOS 7.5 Packaging Conflicts cockpit-preview copr

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#10157] opened 2018-09-25 19:36 UTC
For about a week now have been unable to update cockpit due to file conflicts in the packaging. I'm using the cockpit preview copr.

Logs below:
Transaction check error:
 ```file /usr/share/cockpit/selinux/manifest.json from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.ca.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.cs.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.de.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.es.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.eu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.fi.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.fr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.hr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.hu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.ja.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.ko.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.my.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.nl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.pa.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.pl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.pt.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.pt_BR.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.tr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.uk.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/po.zh_CN.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/selinux/selinux.min.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-selinux-172-2.el7.centos.noarch
  file /usr/share/cockpit/sosreport/manifest.json from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.ca.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.cs.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.da.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.de.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.es.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.eu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.fi.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.fr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.hr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.hu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.ja.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.ko.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.my.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.nl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.pa.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.pl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.pt.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.pt_BR.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.tr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.uk.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/sosreport/po.zh_CN.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-sosreport-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/manifest.json from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.ca.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.cs.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.da.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.de.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.es.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.eu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.fi.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.fr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.hr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.hu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.ja.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.ko.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.my.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.nl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.pa.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.pl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.pt.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.pt_BR.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.tr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.uk.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/po.zh_CN.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/firewall.min.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/networkmanager/network.min.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-networkmanager-177-1.el7.noarch
  file /usr/share/cockpit/kdump/manifest.json from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/kdump.min.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.ca.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.cs.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.da.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.de.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.es.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.eu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.fi.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.fr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.hr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.hu.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.ja.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.ko.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.my.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.nl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.pa.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.pl.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.pt.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.pt_BR.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.tr.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.uk.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch
  file /usr/share/cockpit/kdump/po.zh_CN.js.gz from install of cockpit-system-178-1.el7.noarch conflicts with file from package cockpit-kdump-177-1.el7.noarch

Error Summary
-------------```

**Comment by PeterFalken** [comment] 2018-09-25 20:55
@dcrdev I'm experiencing the same issue.
I've documented it on #10132

**Comment by martinpitt** [comment] 2018-10-02 14:51
Closing as duplicate of #10132.

**Closed by martinpitt** 2018-10-02 14:51 UTC
