### ISSUE TITLE
Paste function doesn't work (Chrome 86.0.4240.75, Firefox 81.0.2, Edge 86.0.622.48)

### ISSUE THREAD

**Issue by ybshin** [cockpit-project/cockpit#14774] opened 2020-10-20 02:54 UTC
Cockpit version: 211.3-1
OS:Windows 10 (10.0.18363 Build 18363)
Page: 

Copy is working but paste doesn't work.

I already tried 'Ctrl + Insert and Shift + Insert' but I just got '^[[2~'

Steps to reproduce

1. Login cockpit and copy any text on Windows
2. Paste with shortcut 'Ctrl + Insert' and 'Shift + Insert'
3.

**Comment by marusak** [comment] 2020-10-20 09:49
What browser are you on?
Are you using http or https to login into Cockpit?
Have you tried right mouse click? Does that work?

**Comment by marusak** [comment] 2021-02-18 16:21
ctrl+insert and shift-insert seem to work fine both in chrome and firefox. Cannot reproduce and we did not get any more reply, closing.

**Closed by marusak** 2021-02-18 16:21 UTC
Labels: question, review-2021-02
