### ISSUE TITLE
Tests failed on 6f53f89568ec9e91528689a03a61d7f17dd25b11

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20194] opened 2024-03-19 02:31 UTC
The job `fedora-39/updates-testing` failed on commit 6f53f89568ec9e91528689a03a61d7f17dd25b11.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6f53f895-20240319-012418-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-03-19 05:35
Duplicate of #20184

**Closed by martinpitt** 2024-03-19 05:35 UTC
Labels: nightly
