### ISSUE TITLE
Tests failed on 6a22cba5d61500f8f6f3f428cf6ba407340e0221

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20424] opened 2024-05-03 02:22 UTC
The job `fedora-40/updates-testing` failed on commit 6a22cba5d61500f8f6f3f428cf6ba407340e0221.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6a22cba5-20240503-012750-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-05-03 02:48
Duplicate of #20338.

**Closed by martinpitt** 2024-05-03 02:48 UTC
Labels: nightly
