### ISSUE TITLE
Tests failed on 49d67d29bc7f962b6a3ab4d31fde86e8df2819b1

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21113] opened 2024-10-14 02:35 UTC
The job `fedora-40/updates-testing` failed on commit 49d67d29bc7f962b6a3ab4d31fde86e8df2819b1.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-49d67d29-20241014-013125-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-14 05:07
Duplicate of #21108

**Closed by martinpitt** 2024-10-14 05:07 UTC
Labels: nightly
