### ISSUE TITLE
Tests failed on a30106a40b4fdc752194447b663e5d32c8638ff5

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21109] opened 2024-10-13 02:30 UTC
The job `fedora-40/updates-testing` failed on commit a30106a40b4fdc752194447b663e5d32c8638ff5.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-a30106a4-20241013-013127-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-10-14 05:07
Duplicate of #21108

**Closed by martinpitt** 2024-10-14 05:07 UTC
Labels: nightly
