### ISSUE TITLE
System date cannot be changed manually

### ISSUE THREAD

**Issue by AntonPetrochenko** [cockpit-project/cockpit#15071] opened 2020-12-23 09:57 UTC
Cockpit version: 233.1.
OS: Arch Linux
Page: Overview

It would appear that the Bootstrap datepicker component used in system time modal conflicts with the underlying Patternfly field. Date entered into the field using the datepicker will be displayed but will not actually be used when submitting the form. When observed through the debugger, the `<input>` value remains unchanged when the datepicker is used to enter a date.

If your date was not initially in en_US or RFC3339 format due to client-side locale, it will always be invalid even if date was selected with the datepicker. Any invalid input entered into the form and then overwritten with the datepicker will revert back to the manually entered invalid input.

Original issue bellow, which turned out to be just a symptom: 

> It becomes impossible to manually set server time if the _client_ locale is not en_US due to the date format becoming "invalid". Server-side locales don't matter.
> 
> Steps to reproduce
> 
> 1. Set your client side locale to something with a non-english time format e.g. ru_RU
> 2. Try changing the system time
> 3. The form will not submit, as the date format becomes invalid

It was later observed that while the system time changes using the "correct" client-side locale, system date does not.

**Comment by marusak** [comment] 2021-01-04 13:31
I'll try to reproduce this. If it is really issue with client locale, then we should write also proper tests for it as we have mentioned in this ancient issue https://github.com/cockpit-project/cockpit/issues/1957

**Comment by KKoukiou** [comment] 2023-02-08 16:47
This is already fixed once we moved the serverTime.js to DatePicker component. Looks like in release 253.

**Closed by KKoukiou** 2023-02-08 16:47 UTC
Labels: review-2022-12
