### ISSUE TITLE
Pipe character not working in terminal with Swedish keyboard

### ISSUE THREAD

**Issue by fredcb** [cockpit-project/cockpit#7360] opened 2017-07-24 07:48 UTC
The pipe character doesn't work in  the terminal when using Swedish keyboard layout. This makes the terminal rather useless. Workaround exist, e.g. use alt+124 or swap keyboard layout but both are both unpractical.

**Comment by lindhor** [comment] 2017-12-19 20:50
Totally agree! Even if national characters works (ÅÄÖåäö) pipe does not. Same results in Firefox, and Chrome. Pressing `|` makes the prompt turn into `(arg: 7)` (i.e. repeat character) rather than showing the pipe. Exactly the same goes for the backslash character `\` which is also handy to be able to type to be able to specify escape characters etc. Running on a Mac, I have not found any workaround, like AltGr+ASCII on Windows.

**Comment by bousquetfrederic** [comment] 2018-03-05 10:00
I have the same problem with a French keyboard on CentOS 7.4.
I use a laptop with no numpad so alt-124 does not help.

**Comment by marusak** [comment] 2019-02-21 09:40
There is a new release 188, that uses new library for terminal. Can someone test it and let us know if this is still issue? (I tried using swedish keyboard but could not reproduce this).

**Comment by marusak** [comment] 2019-09-16 13:22
Hopefully fixed with xterm.js :)

**Closed by marusak** 2019-09-16 13:22 UTC
Labels: question
