### ISSUE TITLE
Cockpit 285-1 shows constantly 105 degrees of CPU after update

### ISSUE THREAD

**Issue by mat-sienczyk** [cockpit-project/cockpit#18440] opened 2023-03-03 07:02 UTC
### Explain what happens

After latest update (via software updates tool) Cockpit shows constantly 105 degrees on my Dell Wyse 5070 - before update everything was ok.

I see that version 286 is available on website, but I cannot see that update:

![image](https://user-images.githubusercontent.com/9090434/222653118-1069d7a2-fd85-4c33-954d-8ff57d3d6c42.png)
![image](https://user-images.githubusercontent.com/9090434/222653207-90df6c8b-3667-4e02-9b3c-675faab85ca6.png)

### Version of Cockpit

285-1

### Where is the problem in Cockpit?

Metrics

### Server operating system

Debian

### Server operating system version

11

### What browsers are you using?

Chrome

**Comment by marusak** [comment] 2023-03-03 07:15
Duplicate of https://github.com/cockpit-project/cockpit/issues/18397

**Comment by martinpitt** [comment] 2023-03-03 07:15
Duplicate of issue #18335. This is fixed in versino 286, please update.

**Closed by marusak** 2023-03-03 07:15 UTC
Labels: bug

**Comment by mat-sienczyk** [comment] 2023-03-03 07:26
> Member

I would love to, but as I wrote in bug, no system updated nor apt update is not updating.

**Comment by martinpitt** [comment] 2023-03-03 07:30
@mat-sienczyk : I updated Ubuntu backports this morning, see https://launchpad.net/ubuntu/+source/cockpit . In a few hours 286 should be available.

**Comment by mat-sienczyk** [comment] 2023-03-03 07:36
@martinpitt what about Debian backports?

**Comment by martinpitt** [comment] 2023-03-03 07:42
@mat-sienczyk : I need to wait for another day for 286 to go into testing, see https://tracker.debian.org/pkg/cockpit
