### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19769] opened 2023-12-21 02:29 UTC
Tests failed on 5a872683db3d00a27064d24ab7e1011b7fd46baa, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231221-012659-5a872683-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2023-12-21 03:05
Duplicate of #19765

**Closed by martinpitt** 2023-12-21 03:05 UTC
Labels: nightly
