### ISSUE TITLE
Tests failed on a0bbcab243f2a0a29b9b37931103603e90484ec9

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20808] opened 2024-07-28 02:26 UTC
The job `fedora-40/daily` failed on commit a0bbcab243f2a0a29b9b37931103603e90484ec9.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-a0bbcab2-20240728-013042-fedora-40-daily/log.html

**Comment by jelly** [comment] 2024-07-29 07:45
Duplicate of https://github.com/cockpit-project/cockpit/issues/20764

**Closed by jelly** 2024-07-29 07:45 UTC
Labels: nightly
