### ISSUE TITLE
lxc management

### ISSUE THREAD

**Issue by bitchecker** [cockpit-project/cockpit#9058] opened 2018-04-26 17:44 UTC
i've installed the latest version of cockpit on Fedora 27 from package manager, i think is very complete but it gaves you the possibility to manage docker containers via dedicated plugin, there will be possible in the future to manage lxc containers?

**Comment by q2dg** [comment] 2018-05-08 14:56
Duplicate of https://github.com/cockpit-project/cockpit/issues/8215

**Closed** 2018-05-15 08:39 UTC
