### ISSUE TITLE
Metrics page using significant memory on Safari

### ISSUE THREAD

**Issue by noahkamara** [cockpit-project/cockpit#16242] opened 2021-08-18 14:54 UTC
Cockpit version: 250
OS: Fedora Server (5.13.10-200.fc34.x86_64)
Page: Overview > Metrics

Description: 
The Metrics page uses 4 gigabytes of memory when opened. (Safari)
On iPad 

Logs:
Output of `journalctl --since -1m`: [gist](https://gist.github.com/noahkamara/fc470263d3ef268d6855e84af407fae2)
Output of `journalctl -u cockpit -u cockpit-pcp`: [gist](https://gist.github.com/noahkamara/c735fc7b61209e062f2079bafe5373b8)

Steps to reproduce
1. Open Overview page
2. Click on "View details and history"

PS: Is there a way to disable metrics in a config file without breaking cockpit? I can't disable it on the page because it reloads before I'm able to open metrics settings

**Comment by PeterFalken** [comment] 2021-08-18 15:59
I have the same issue on Safari for macOS 11.5.2 (also on macOS 12 Beta) when browsing to the Metrics page - the OS becomes unresponsive and at some point Safari reload the page back to the login screen with a message saying that the page was using too many resources.
When using Firefox on macOS the Metrics page works fine.

**Comment by garrett** [comment] 2021-08-18 21:18
>  The Metrics page uses 4 gigabytes of memory when opened. (Safari)

Wow!

I wonder if we'll see the issue with Epiphany (GNOME Web) on Linux too, as it also uses WebKit. Otherwise debugging this might be a tad difficult. (I have an iPhone for testing, but will be AFK for a couple weeks.)

I'm assuming it has something to do with the page using a lot of SVGs inside of flex elements and wonder if we can do anything to speed that up for Safari.

//cc: @marusak & @martinpitt

**Comment by garrett** [comment] 2021-08-19 15:30
I've checked in GNOME Web (Epiphany) on Linux + Wayland and I see it does spike RAM from around  200 Mb to 2 Gb when the page loads or the window is resized. After a short while, the RAM usage starts to settle back down, but CPU usage is still rather high.

Additionally, at least in Epiphany, sizing for events is incorrect, as they seem to be stretched to around a full page (100vh) worth of content. This might be related?

Is anyone seeing the graph vertically stretched too tall for events in Safari on iOS and/or macOS?

While the rendering stack is undoubtedly different between Linux (even between Wayland and X11), iOS, and macOS, I think it's similar enough in the WebKit stack to trigger this same bug, so this should help us fix it, I hope.

**Comment by garrett** [comment] 2021-08-19 16:00
Oh, the odd vertical stretching is not due to the browser. I see it in Firefox too. I had to load old data, as it didn't have anything recent (oddly). So that's a "red herring" (misdirection), but still a bug (at least on my machine, with the code from the main branch, after loading older data).

I haven't been able to figure out the sizing problem or resource issue.

I think @marusak will have to look at this, as I'm headed on PTO for a few weeks.

**Comment by PeterFalken** [comment] 2021-08-19 16:07
Thanks for looking into this @garrett , I can confirm that the graph is stretched a lot vertically on Safari - prior to getting the message about too much resources being used. Enjoy your PTO.

**Comment by garrett** [comment] 2021-08-20 07:58
@PeterFalken: Just to clarify; the graph is supposed to be stretched to the height of the events (it's important, so it's fine if the graph has more details during that time — and things need to align too), but it should not be taller than the event log on the left. It's absurdly high where I'm seeing it.

I think when you say "stretched a lot vertically", you're seeing this too? :cry: It looks like we have a few regressions that slipped in despite the tests somehow.

**Comment by PeterFalken** [comment] 2021-08-23 19:26
> I think when you say "stretched a lot vertically", you're seeing this too? 😢 It looks like we have a few regressions that slipped in despite the tests somehow.

Yes, this what I'm seeing, and also the huge memory usage and being kicked out of the session while trying to view the Metrics page on Safari.

**Closed** 2021-09-23 14:33 UTC
Labels: page:metrics

**Comment by PeterFalken** [comment] 2021-09-23 16:58
Thank you @garrett for looking into this.

**Comment by tgwaste** [comment] 2021-10-05 18:24
Has this gone out?  I still have the same issues.

**Comment by garrett** [comment] 2021-10-05 20:56
@tgwaste: The fix is included in Cockpit 254. https://cockpit-project.org/blog/cockpit-254.html

Which version of Cockpit are you using? If you're having the same issue with Safari on 254, I'd like to know.

(You may need to use use a backport if you're using Cockpit on a Debian or Ubuntu OS to get the latest version of Cockpit. Otherwise, most distributions include the latest version of Cockpit. See https://cockpit-project.org/running.html for details.)
