### ISSUE TITLE
Navigation constantly re-homes Cockpit navigation to System plugin

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#13029] opened 2019-10-23 15:55 UTC
Cockpit version: 194
OS: Atomic Centos 7.1905.9
Browser version: Chrome 77.0.3865.120 (64-bit) with disabled uBlock Origin extension on Windows 10 <= **_bad_** behavior
Browser version: Chrome 77.0.3865.90 (64-bit) on Centos 7.5 <= **_good_** behavior
Browser version: FireFox 70.0 on Windows 10 <= **_good_** behavior

I've been trucking along developing a couple of nice cockpit plugins in my dev env (Centos 7.5) using the same bridge and cockpit-ws contain base. The cockpit.ws version is 194 and bridge protocol version is 195.1 in both cases.

```
$ cockpit-bridge --version
Version: 195.1
Protocol: 1
Payloads: dbus-json3 http-stream1 http-stream2 stream packet fsread1
    fsreplace1 fswatch1 fslist1 null echo websocket-stream1
Authorization: crypt1
```
From my Windows test box using Chrome 77.0.3865.120 (latest stable) when I navigate in my Atomicos cockpit to a built-in plugin or my own, the browser will navigate back to the system plugin after a bit of time. Meaning when I login, I'll see the system plugin, I'll click on another one, it'll reload the system plugin and I'll have to re-click the original plugin to get to it. After that I can navigate fine. If I wait a bit (5 secs or so), when I navigate I'll again be brought to the system plugin (which is a default I suppose).

In Chrome's console I see the follow when the hicup occurs:
```
system.js:48 PackageKit went away from D-Bus
system.js:48 Checking for available updates failed: not-found
```

I think this is a red herring maybe because I see those errors when loading the system plugin. I don't think it's the cause.

If I click around generally I can get the navigation to screw up and display the System menu item being highlighted while the actual displayed plugin is another (Kernel Dump or SE Linux).

I have no clue how to debug this behavior and it makes using the actual interface impossible because when you do any navigation the UI will randomly send you to the System plugin,

When I try this with a slightly old Chrome on my Centos dev box its fine. When I use Firefox on the same Windows box it's fine. I have only the uBlock Origin Chrome extension, which I disabled to see if it affected anything. 

Any ideas? I can do some digging if it helps. I wanted to record a small video, but there's some stuff in there I would rather not have to edit out.

**Comment by mckenziec** [comment] 2019-10-29 20:01
I won't close this just yet in case anyone wants to comment, but just after a reboot (not on purpose) the problem seems to have gone away. I have no clue what the problem was but navigation works fine again now in Chrome 77.0.3865.120 on Windows 10.

If you guys want, just close this issue.

**Comment by marusak** [comment] 2019-11-13 20:35
Well, without proper reproducer we won't be able to fix it. And since not even OP can reproduce this anymore, closing.

**Closed by marusak** 2019-11-13 20:35 UTC
