### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19850] opened 2024-01-17 02:29 UTC
Tests failed on e2f3e9eb7c3635e7ac3ddf751c6bb3ff5351062e, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240117-012821-e2f3e9eb-fedora-39-daily/log.html)

**Comment by martinpitt** [comment] 2024-01-17 02:37
Duplicate of #19822

**Closed by martinpitt** 2024-01-17 02:37 UTC
Labels: nightly
