### ISSUE TITLE
ON/OFF button layout breaks in brazilian portugese translation

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9408] opened 2018-06-18 08:30 UTC
![screenshot from 2018-06-18 10-29-39](https://user-images.githubusercontent.com/209895/41525840-9fa1ad04-72e2-11e8-9a89-771f2923348e.png)
![screenshot from 2018-06-18 10-30-03](https://user-images.githubusercontent.com/209895/41525844-a4cfeaca-72e2-11e8-88e9-8d48a08fa6a8.png)

**Comment by leomoty** [comment] 2018-06-19 13:03
In Portuguese, "(a) Política" is a feminine word, thus it should be "Ligada" instead of "Ligado", same with "Desligado". That depends on the noun being considered.

As a follow up, more examples can be seen here: http://www.easyportuguese.com/portuguese-lessons/feminine/

That being said, we are quite used to "ON/OFF" terminology and that should be fine for someone handling an UI for servers.

**Comment by martinpitt** [comment] 2018-10-26 15:09
I cannot reproduce this. We don't have "Brazilian Portugese" in Cockpit's language menu. But I can select ptr-br in the browser as preferred language, then I also get the login page in pt. But after logging in, everything is in English, and the  On/Off buttons seem okay.

**Comment by leomoty** [comment] 2018-10-26 15:17
I don't think I understand @martinpitt, I can easily reproduce this by selecting:

![image](https://user-images.githubusercontent.com/1463740/47575697-08368280-d919-11e8-80c8-ad76488ca353.png)

I am not sure this is a "pt-br" issue.

![image](https://user-images.githubusercontent.com/1463740/47575738-200e0680-d919-11e8-843a-479228c0af62.png)

**Comment by martinpitt** [comment] 2018-10-26 16:55
This should actually be fixed with PR #10451. I was just curious how to confirm this, as I'm unable to get Portugese translations.

**Comment by leomoty** [comment] 2018-11-08 17:04
Noticed a case where this is actually annoying:

![image](https://user-images.githubusercontent.com/1463740/48214632-80646580-e367-11e8-9f3e-32340d5ad83c.png)

Since the text covers most of the plus button:

![image](https://user-images.githubusercontent.com/1463740/48214652-8d815480-e367-11e8-8dde-afe53eef82ba.png)

**Closed** 2019-05-14 18:58 UTC
