### ISSUE TITLE
Tests failed on 75b4087cbfad1218dbebce57913a73d59d92a107

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20577] opened 2024-06-12 02:26 UTC
The job `fedora-40/updates-testing` failed on commit 75b4087cbfad1218dbebce57913a73d59d92a107.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-75b4087c-20240612-012956-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-06-13 06:39
More SELinux.. Srsly, this needs to stop. I'll just consider this a duplicate of #20542

**Closed by martinpitt** 2024-06-13 06:39 UTC
Labels: nightly
