### ISSUE TITLE
Terminal height is too small

### ISSUE THREAD

**Issue by qooob** [cockpit-project/cockpit#2517] opened 2015-07-29 09:54 UTC
Guys, hi!

I have made a small fix that makes the terminal look like this:

![screenshot from 2015-07-29 12-52-07](https://cloud.githubusercontent.com/assets/4426533/8954792/aa72b1a6-35f0-11e5-8e34-acc7a7ccfce2.png)

Here is the both CSS and JS that you could add to the bundle to make things work. Notice it will require to make some changes to the Terminal so inner part of it will also stretch:

```CSS
.panel.panel-default.console-container { 
	width: 98%;
	width: 98.6%;
	}
 
#terminal.console > .terminal {
     width: 100%;
     height: 100%;
}
```

```JS

function setTerminalHeight() {
	if ($('#terminal.console').length) {
          $('#terminal.console > .terminal').css('height', parseInt(window.parent.$('.container-frame').css('height')) - 75);
     }
}

$(window).on('load, resize', function(){
      setTerminalHeight();
});

```

Will you fix it? Because now it super annoying?

**Comment by andreasn** [comment] 2015-07-29 11:02
This sounds like a duplicate of https://github.com/cockpit-project/cockpit/issues/2001

**Comment by qooob** [comment] 2015-07-29 11:06
Yes, right!

**Comment by qooob** [comment] 2015-07-29 12:43
I could contribute if I knew you would commit.

**Comment by andreasn** [comment] 2015-07-29 13:33
Closing due to duplicate of #2001

**Closed** 2015-07-29 13:33 UTC

**Comment by andreasn** [comment] 2015-07-29 13:35
> I could contribute if I knew you would commit.

Yes, as long as a fix follows the design in #2001 and passes code-review, it would be committed to master.

**Comment by qooob** [comment] 2015-07-29 14:23
Meaning default will stay small and could be streched?

**Comment by qooob** [comment] 2015-07-29 14:23
Is anyone working on it already?

**Comment by qooob** [comment] 2015-07-29 14:44
I just dug a bit, it seems that the output pre-generated with fixed amount of lines by both width and height. This is what really requires the change. In case it's hard to make it dynamically, I would suggest using `screen.width()` and `screen.height()` for generating different pre-defined output. 

Better to start with:

```JavaScript
if (screen.width() === 1920 && screen.height() === 1080 ) {
     //generate predefined amount of lines in width and height
}
```

Then for example,

if (screen.width() === 2560 && screen.height() === 1080 ) {
     //generate predefined amount of lines in width and height
}

..and so on. I didn't see the way it works yet but I would think that it's not easy to make align well dynamically.

Anyway, it should talk just couple of hours for the terminal developer, as it would take more time for the other to figure out what is what.

**Comment by andreasn** [comment] 2015-07-29 16:56
I think it's best to continue this discussion on #2001
