### ISSUE TITLE
Display error in Cockpit Terminal without HTML Canvas permission

### ISSUE THREAD

**Issue by AliAsgerSaify** [cockpit-project/cockpit#19345] opened 2023-09-18 06:26 UTC
### Explain what happens

1.  No text is being displayed in terminal. No doubt it works but when you can't see then you can just guess what you are typing in terminal which could be dangerous.
2. In the below image, I haven't blured the image; this is how it is displayed
3. 
![image](https://github.com/cockpit-project/cockpit/assets/120162464/2da242a2-1be4-4c49-8acf-47bfd988cb0a)

### Version of Cockpit

299-1

### Where is the problem in Cockpit?

Terminal

### Server operating system

Arch Linux

### Server operating system version

Manjaro

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment] 2023-09-29 05:27
Hm, that looks like Windows -- is that really Arch or Manjaro, with some Windows theme or so?

Anyway, can you please check https://xtermjs.org/ if the demo terminal works there? Please also try to type something, like `chars` + Enter

**Comment by pythonmkl** [comment] 2023-10-17 17:47
> Hm, that looks like Windows -- is that really Arch or Manjaro, with some Windows theme or so?
> 
> Anyway, can you please check https://xtermjs.org/ if the demo terminal works there? Please also try to type something, like `chars` + Enter

In xtermjs.org the terminal is ok, it works.
The terminal also works on Chromium but not on my Firefox or LibreWolf. It has something to do with plugins or user.js definitions because on a new profile on Firefox, it works.

My base OS is ArchLinux but cockpit is installed on a CentOS Strem 9 VM in VirtualBox. So it is not a Cockpit problem.

**Comment by martinpitt** [comment] 2023-10-18 04:01
Thanks for confirming. Any idea which plugin it is? If we can reproduce, we may be able to do something about it.

**Comment by AliAsgerSaify** [comment] 2023-10-18 12:32
I got the solution for this error. You have to enable and/or give permission to site to use HTML Canvas. It will appear to the address bar in left corner probably besides the lock icon. Enabling the HTML Canvas and re-opening the cockpit will solve the issue.
Thanks.

**Comment by martinpitt** [comment] 2023-10-18 12:34
I've never heard of that permission. Is that some Firefox extension or some configuration option? Out of interest, what's bad about allowing a canvas? Rendering is pretty much a browser's raison d'être, no?

**Comment by AliAsgerSaify** [comment] 2023-10-19 06:21
Well I don't even know why it is so, why they need graphics permissions where they just have to display and process text. Well HTML <canvas> element is used to draw graphics, on the fly, via JavaScript. To know more I am dropping a [link here](https://www.w3schools.com/html/html5_canvas.asp)

**Comment by martinpitt** [comment] 2023-10-31 05:21
Closing -- there's nothing that we can do on our end short of finding a simpler (and thus much less powerful) terminal widget, and disabling `<canvas>` feels obscure enough that we don't want to support this.

**Closed by martinpitt** 2023-10-31 05:21 UTC
Labels: question, bug
