### ISSUE TITLE
Browser support for Qutebrowser

### ISSUE THREAD

**Issue by anjoweichbrodt** [cockpit-project/cockpit#17751] opened 2022-09-21 11:36 UTC
Page: Browser support

When opening the cockpit login page a warning is returned:
`This web browser is too old to run the Web Console (missing selector(:is():where()))`

Is it possible to support Qutebrowser for the usage of the cockpit web-interface?

**Comment by garrett** [comment] 2022-09-21 12:34
## Intro

Firstly, I think Qutebrowser is a neat project. I use both vim and VS Codium with neovim embedded and can appreciate a browser that acts like vim also.

But Qutebrowser has a serious problem: Its engine is around two years old (or older).

## Explanation

We don't block Qutebrowser (or any other browser) from working with Cockpit.

The login page does check for certain browser _features_ that are used by Cockpit and its dependencies (notably: PatternFly). But it intentionally doesn't check specific browsers or browser versions.

PatternFly started using `:is()` and `:where()` earlier this year. Therefore, Cockpit has been using it as well. As `:is()` and `:where()` usage will break the layout in browser that don't support these features, they were added to the feature check on the main page. (PatternFly — probably rightfully — does not handle fallbacks for browsers that do not support either, as any browser that doesn't support the feature is older than a year or two and is therefore considered insecure.)

### Browser versions

These two selectors landed quite some time ago, according to
https://caniuse.com/mdn-css_selectors_where

- **Gecko** browsers, 2020
   - Firefox 78, 2020-Jun-30
   - Tor Browser 10.0, 2020-Sep-22
- **Chromium** browsers, 2021
   - Chrome 88, 2021-Jan-19
   - Edge 88, 2021-Jan-23
   - Opera 74, 2021-Feb-2
- **WebKit** browsers, 2020
   - Safari 14, 2020-Jul-20
   - GNOME Web, sometime in 2020 (I didn't find an obvious version, but WebKitGTK releases sometime after)
- Qt WebEngine 
   - Qt 5.x: Not supported, as its version of Chromium is very old
   - Qt 6.x ??? (I'm not sure, as Qt doesn't list the version or featureset, and all Qt browsers seem to still be using Qt 5.x.)

### Qutebrowser and Qt specifics

This means Qutebrowser's engine, which is using either QtWebKit (which is _very much NOT recommended_) or QtWebEngine from Qt 5.12 LTS or 5.15 or later is _ancient_ in browser time. I'm going to assume you're _not_ using QtWebKit (as that would be a bad idea). That means your browser engine's version is from late 2020 (the release prior to the 2021 January release that adds the feature) or before.

While the authors of Qutebrowser have personally assured me in the past that they and the Qt team take security seriously and do backport critical fixes, it's odd that all Qt browsers are stuck on such an old version of Chromium. This includes Qutebrowser.

So, this bug is really not about Cockpit. It's actually a bug that should be filed against QtWebEngine to upgrade to a more recent version of Chromium. (They've had a couple years to do it, but haven't yet. It's likely that they're working on it, but it's a big task.) 

It's also very likely that Qutebrowser is using such an old version as that's what Qt 5.x is using and once they upgrade to Qt 6.x, they'll get a newer version. This is what I was told a few months ago from a Qutebrowser developer.

Therefore, there should also be a bug filed for all the Qt browsers that are still using Qt 5.x. Getting a better maintained browser engine is a good reason for them to port to Qt 6.x.

## Summary

0. Cockpit specifically does not exclude _any_ browsers, but does feature checks for the features Cockpit uses.
1. PatternFly uses `:is()` and `:where()`, so Cockpit needs to check for it so Cockpit won't randomly break in browsers.
2. Qt browsers need to use newer engines. This likely means porting to Qt 6.
3. Qt itself needs to get better about maintaining their Chromium port and communicating the exact version of Chromium and patches for the version of Qt. This is _especially_ true for their LTS version of Qt.

In other words, Qutebrowser is as "supported" as Chromium is. The problem is that we support recent versions of Chromium (and our tests even specifically run in Chromium)... but we don't support Chromium >= 2 years old, as PatternFly also does not. (And basically nobody does. "Evergreen support" is typically current browser plus previous version, for the major browsers.)

In other other words, when Qutebrowser upgrades to Qt 6.x to get the new Qt WebEngine based on Chromium, then it will probably be recent enough to work with Cockpit again.

(I have specifically informally chatted with Qt-based browser makers about this exactly subject several months ago. It's frustrating, as I do want more great FOSS browsers — including Qutebrowser — to be viable options. But right now they're not really a recommendable option, util they can update their browser engines in a timely fashion. Once they do improve browser engine support, then they'll be great.)

**Closed by garrett** 2022-09-21 12:34 UTC
Labels: enhancement
