### ISSUE TITLE
Tests failed on c037dc3338790167402a3fbdd75fbc3e1727a85e

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20588] opened 2024-06-14 02:27 UTC
The job `fedora-40/updates-testing` failed on commit c037dc3338790167402a3fbdd75fbc3e1727a85e.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c037dc33-20240614-012941-fedora-40-updates-testing/log.html

```
audit: type=1400 audit(1718330665.362:4): avc:  denied  { getattr } for  pid=674 comm="systemd-fstab-g" path="/home" dev="vda4" ino=257 scontext=system_u:system_r:systemd_fstab_generator_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
```

```
 selinux-policy         noarch 40.22-1.fc40               updates          58 k
 selinux-policy-devel   noarch 40.22-1.fc40               updates         915 k
 selinux-policy-targeted
```

**Comment by martinpitt** [comment] 2024-06-15 05:58
Duplicate of #20542

**Closed by martinpitt** 2024-06-15 05:58 UTC
Labels: nightly
