### ISSUE TITLE
Reports disk temperatures as 112  C, which is a normalized value

### ISSUE THREAD

**Issue by gzcwnk** [cockpit-project/cockpit#7649] opened 2017-09-11 23:20 UTC
On my config  cockpit says the disks are 112 and then the "Celcius"    In fact this is I suspect its actually F and 112F = 44C it does this for both harddrives so I am pretty confident its not the disks over-heating, plus I cant cook an egg on them either.

It would be nice to have the dashboard report in C but F will do just as long as its not making this mistake.   PS I have seen this before in other apps and other hardware so it seems a common issue maybe at the bios level?  and the software mis-reads it?

**Comment by gzcwnk** [comment] 2017-09-12 04:02
PS

root@dell6430-001:~# hddtemp /dev/sda
/dev/sda: WDC WD3200BEKT-75PVMT1: 32°C
root@dell6430-001:~# hddtemp /dev/sdb
/dev/sdb: WDC WD3200BEKX-75B7WT0: 31°C
root@dell6430-001:~#

**Comment by stefwalter** [comment] 2017-09-12 06:01
@mvollmer Is this a udisks/storaged bug?

**Comment by martinpitt** [comment] 2017-09-12 06:04
In fact it's supposed to show the temperature in both Celsius and Fahrenheit. This is how it looks like for me:

![disk](https://user-images.githubusercontent.com/200109/30310307-1e51e58a-9790-11e7-9bb9-713d4ad54371.png)

Cockpit assumes that it gets the temperature in Kelvin from udisks. Can you please run `udisksctl dump | grep Temp` in a terminal and tell the result here?

**Comment by martinpitt** [comment] 2017-09-12 06:05
udisks in turn gets it through libatasmart. Can you please run `sudo skdump /dev/sda` and copy&paste the result here?

**Comment by gzcwnk** [comment] 2017-09-12 07:30
So actually now I look closer  in the log I see,

"15:45 Device: /dev/sda [SAT], SMART Usage Attribute: 194 Temperature_Celsius changed from 112 to 111"

So actually its not cockpit picking it up but "something" is dumping in the logs that cockpit picks up.

**Comment by gzcwnk** [comment] 2017-09-12 07:32
###
root@dell6430-001:~# skdump /dev/sda
Device: sat16:/dev/sda
Type: 16 Byte SCSI ATA SAT Passthru
Size: 305245 MiB
Model: [WDC WD3200BEKT-75PVMT1]
Serial: [WD-WX41AA2F6538]
Firmware: [01.01A01]
SMART Available: yes
Quirks:
Awake: yes
SMART Disk Health Good: yes
Off-line Data Collection Status: [Off-line data collection activity was never started.]
Total Time To Complete Off-Line Data Collection: 6300 s
Self-Test Execution Status: [The previous self-test routine completed without error or no self-test has ever been run.]
Percent Self-Test Remaining: 0%
Conveyance Self-Test Available: yes
Short/Extended Self-Test Available: yes
Start Self-Test Available: yes
Abort Self-Test Available: yes
Short Self-Test Polling Time: 2 min
Extended Self-Test Polling Time: 65 min
Conveyance Self-Test Polling Time: 5 min
Bad Sectors: 0 sectors
Powered On: 3.1 years
Power Cycles: 450
Average Powered On Per Power Cycle: 2.6 days
Temperature: 33.0 C
Attribute Parsing Verification: Good
Overall Status: GOOD
ID# Name                        Value Worst Thres Pretty      Raw            Type    Updates Good Good/Past
  1 raw-read-error-rate         200   200    51   0           0x000000000000 prefail online  yes  yes
  3 spin-up-time                157   154    21   1.1 s       0x750400000000 prefail online  yes  yes
  4 start-stop-count            100   100     0   452         0xc40100000000 old-age online  n/a  n/a
  5 reallocated-sector-count    200   200   140   0 sectors   0x000000000000 prefail online  yes  yes
  7 seek-error-rate             200   200     0   0           0x000000000000 old-age online  n/a  n/a
  9 power-on-hours               63    63     0   3.1 years   0xc96b00000000 old-age online  n/a  n/a
 10 spin-retry-count            100   100     0   0           0x000000000000 old-age online  n/a  n/a
 11 calibration-retry-count     100   100     0   0           0x000000000000 old-age online  n/a  n/a
 12 power-cycle-count           100   100     0   450         0xc20100000000 old-age online  n/a  n/a
191 g-sense-error-rate           79    79     0   21          0x150000000000 old-age online  n/a  n/a
192 power-off-retract-count     200   200     0   30          0x1e0000000000 old-age online  n/a  n/a
193 load-cycle-count              1     1     0   678518      0x765a0a000000 old-age online  n/a  n/a
194 temperature-celsius-2       110   101     0   33.0 C      0x210000000000 old-age online  n/a  n/a
196 reallocated-event-count     200   200     0   0           0x000000000000 old-age online  n/a  n/a
197 current-pending-sector      200   200     0   0 sectors   0x000000000000 old-age online  n/a  n/a
198 offline-uncorrectable       100   253     0   0 sectors   0x000000000000 old-age offline n/a  n/a
199 udma-crc-error-count        200   200     0   0           0x000000000000 old-age online  n/a  n/a
200 multi-zone-error-rate       100   253     0   0           0x000000000000 old-age offline n/a  n/a
240 head-flying-hours            66    66     0   2.9 years   0x076300000000 old-age online  n/a  n/a
241 total-lbas-written          200   200     0   502499.480 TB 0xac4e9e7c0300 old-age online  n/a  n/a
242 total-lbas-read             200   200     0   634293.037 TB 0x0414bb660400 old-age online  n/a  n/a
254 attribute-254               198   198     0   n/a         0x020000000000 old-age online  n/a  n/a
root@dell6430-001:~#
###

**Comment by gzcwnk** [comment] 2017-09-12 07:33
So I really need to find what the application that is dumping wrong and fix it, doh

**Comment by gzcwnk** [comment] 2017-09-12 07:41
We can close this, I see I got confused somewhat not cockpit's issue but something else.  Sorry about that.

**Comment by martinpitt** [comment] 2017-09-12 10:25
Thanks, so skdump (and thus libatasmart) is able to read the correct temperatures, that's good as it excludes some hardware and low-level problems:
```
Temperature: 33.0 C
194 temperature-celsius-2       110   101     0   33.0 C      0x210000000000 old-age online 
```

To compare, my hard disk has a different attribute, but it also gets interpreted correctly:
```
Temperature: 37.0 C
190 airflow-temperature-celsius  37    54     0   37.0 C      0x250036000900 old-age online  n/a  n/a 
```
My suspicion is that udisks does not interpret `temperature-celsius-2` correctly, it's using the normalized value "110" directly as Celsius. Also see [these two FAQs](https://www.smartmontools.org/wiki/FAQ#Whyismydisktemperaturesreportedbysmartdas150Celsius).

Don't worry about the `Temperature_Celsius changed from 112 to 111` log message, that's just a normal operation - the temperature changes from time to time, after all. But both are normalized values.

Can you please still run `udisksctl dump | grep Temp` and give the result here, to have all the data?

**Comment by gzcwnk** [comment] 2017-09-13 21:33
I am not worried about the change from 111C to 112C just that it says Celsius and 111C is way to hot for a disk.

====
root@dell6430-001:/media/2tb/etc/sysconfig/network-scripts# udisksctl dump | grep Temp
    SmartTemperature:                           304.15000000000003
    SmartTemperature:                           303.15000000000003
root@dell6430-001:/media/2tb/etc/sysconfig/network-scripts# 
====

**Comment by gzcwnk** [comment] 2017-09-13 21:38
Also I have or will have ppl who know nothing (or enough to be dangerous) about Linux looking at this so its quite important they dont see an error like this without an explanation.

**Comment by martinpitt** [comment] 2017-09-13 21:48
Thanks, so it's really an udisks problem. In order for me to reproduce this and send it to the right place, can you please do one more thing:

    sudo skdump --save /dev/sda | gzip -9 | base64

and copy&paste the output here? With that I can upload your drive's SMART data into udisks and reproduce the problem. Thanks!

**Comment by gzcwnk** [comment] 2017-09-13 21:51
##
root@dell6430-001:/var/lib# skdump --save /dev/sda | gzip -9 | base64
H4sIADeouVkCA+WTP0/bQBjGn4sJaQKoXkAZELGQUNshYF9I6ebEGEQFKZHiEtoNJa1UsWQAVLVq
ywfoxlJVZezOB0AComD8STp0KbAW7PqwG7+BDCxk4fHyu8fvH917d8/N+VdADB8MT59xZAjpCKT4
qipZc7WqTReL8zz/9FnOt7c5NFWdLGqaalaVWbPKc6o6Z1iLM9lyvrSiWcoNydt+3hQriKoJeLrs
95Av/kJmnuc9FJ6E9+FHlUF/BliCCZcB6xvJT7W1dxvJ/dral4ICBS5cryMBe7+NCbpm5V8vyqu7
fZ1R6UK60Ok8aZM7orPOf9eS23osxnWIO1e+0c1VRv/TmNw9z9+GfLsOP79VShUr3CqrlExL3AkZ
bAqOE8ZIj7D7fTOYRR9Hvd4KxhTPRTGJyYiTHLr+Z/2KUyI+9AcIDwpuBnUOOJaXhwP/kPt1xgI+
4mBs63VKcHMcjTeZwG/xqNcxYVtF/TLkE+I7DyL/lMMwsrUrPhMxqUb/Zwk4F/xyx37rb9PlsO0Y
eqQfafZR8k8sVozTE+xZ/y6aqJSshfAe5NpjhDTc/WXEv0aciMaOJIlJER4gPEj4gDB9XEeEm4Rb
hI8J24RPCDuETwmfET4n7OKea+gf5hQsZyQGAAA=
root@dell6430-001:/var/lib# skdump --save /dev/sdb | gzip -9 | base64
H4sIAD2ouVkCA/N0cYtkYGBiqHL6b29+QoABBOwZIEABCMIVdF0iwg3NnRy9jE0tzIyBwg1GDIYG
BnqOhoYGLuEKzi7hRsYGBq5OEd7muk6m4eYGIQoYQKABqE+f0QFkKjvDf3sBoB0Cf34zCDD+//+f
HyTGzFABhchAnoFvPhuDD4MLwz9GBobsksxa5cTMEs89yon1DooMigz/GP79R9HAsOGVkyoynzHg
mV88y6xLqKokHCQcUEU04ax/YvaMqHIsDNiBBii4HBhoDrYWYBNVkIGx7ASw6wN6Q4A4G5ZGBvsG
h0C9yhjs6xICShMCDIz6DCdOQNUwqzNMn9zACgkRI4bkZElIuLAaI9Sw6yHYnEYMsbEdomA2lxFD
SgpUnBuJzYNkzn4jBg8PqJ8OGAHNgbr9oBHDxo0GEuA4OaTEUJggBxE/YoSw6ygS+5gBQ8pfKPs4
kvgJDoT4B5Db3ouA2R9Bapa3PJ8DtOETiD05/NJJIPsfkl7agwBJxmpmYIwxObMixyATw8CBY8G+
IR7QdGCMCApmUew5g7UHwWZHCjpOJDVcSGxuJDYPEns/EvsAEvsgEvsQEvsIEvsosvOR2MeR2Mhx
+gGJ/RGJ/QmJ/Y9hhANeABrVT+YkBgAA
root@dell6430-001:/var/lib# 
##

**Comment by martinpitt** [comment] 2017-09-14 06:49
Oh, hang on - in your `udisksctl dump` comment above (https://github.com/cockpit-project/cockpit/issues/7649#issuecomment-329303491) the temperature is *not* wrong - 303 Kelvin is a perfectly plausible temperature (30 Celsius). I loaded your smart data into udisks and it is fine.

Are you really seeing that temperature on the Storage page, like in the screenshot I posted? Or are you *only* referring to that log entry that you saw ("Temperature_Celsius changed from 112 to 111"): I think you meant that all along, and I just *assumed* that you meant it was displayed wrongly on the Storage page. Now, Cockpit doesn't control these log entries (not sure where they come from, but not udisks -- it's straight from the kernel I think), and it is just a raw SMART value, so this really can just be ignored.

**Comment by stefwalter** [comment] 2018-01-04 12:49
No reply from @gzcwnk ... closing this issue.

**Closed by stefwalter** 2018-01-04 12:49 UTC
Labels: question

**Comment by antoniovazquezblanco** [comment] 2023-01-03 14:18
Same thing happeing to me. Seems libatasmart related. Opened a bug report upstream... Thanks for the pointers in the above replies.

**Comment by antoniovazquezblanco** [comment] 2024-05-05 17:02
This has been fixed in an independent fork of the original lib that it is not currently recognized as official upstream by maintainers at https://github.com/libatasmart/libatasmart.
